and-period/furumaru

api/internal/user/api/user.go
api/internal/user/api/user_test.go
api/mock/pkg/cognito/client.go
api/pkg/cognito/auth.go
api/pkg/cognito/client.go

feat(user/api): implement create user with oauth

---

api/internal/user/api/user.go
api/internal/user/api/user_test.go
api/internal/user/database/database.go
api/internal/user/database/user.go
api/internal/user/database/user_test.go
api/mock/user/database/database.go

feat(api/user): implement delete user api

---

api/internal/gateway/user/v1/handler/api.go
api/internal/gateway/user/v1/handler/auth.go
api/internal/gateway/user/v1/handler/auth_test.go
api/internal/gateway/user/v1/handler/user.go
api/internal/gateway/user/v1/handler/user_test.go
api/internal/gateway/user/v1/request/user.go
api/internal/gateway/user/v1/response/user.go
docs/swagger/user/components/schemas/v1/users.request.yaml
docs/swagger/user/components/schemas/v1/users.response.yaml
docs/swagger/user/openapi.yaml
docs/swagger/user/paths/v1/auth/index.yaml
docs/swagger/user/paths/v1/users/index.yaml
docs/swagger/user/paths/v1/users/me/email/index.yaml
docs/swagger/user/paths/v1/users/me/email/verified.yaml
docs/swagger/user/paths/v1/users/me/forgot-password/index.yaml
docs/swagger/user/paths/v1/users/me/forgot-password/verified.yaml
docs/swagger/user/paths/v1/users/me/index.yaml
docs/swagger/user/paths/v1/users/me/password.yaml
docs/swagger/user/paths/v1/users/oauth.yaml
docs/swagger/user/paths/v1/users/verified.yaml

フロントエンドの実装が進められるように認証関連APIのMockを作成しておきました。
(Swagger周りの追記もしていて型定義の配布もできる状態になっているので、 #18 のマージがされ次第配布したいと思います)
レビュー観点としては、Swaggerで書いたものから生成された↓の中身を見ていただければ大丈夫です🙏
[swagger.zip](https://github.com/and-period/marche/files/8240219/swagger.zip)

feat: create auth api mock

---

api/internal/gateway/user/v1/handler/api_test.go
api/internal/gateway/user/v1/handler/auth.go
api/internal/gateway/user/v1/handler/auth_test.go

feat(gateway): implement get auth api

---

infra/mysql/schema/2022061801-messengers-create-notifications.sql

-  migrationに失敗するので、作成前にDROP TABLE命令を入れるようにした

fix: migrationに失敗するので、作成前にDROP TABLE命令を入れるようにした

---

.github/workflows/ci-backend-for-all.yaml
Makefile

- Makefileのタスクの`docker-compose`を`docker compose`コマンドに変更
変更理由は`docker-compose`は非推奨となるため。
https://www.docker.com/blog/announcing-compose-v2-general-availability/

fix: docker-composeをdocker composeコマンドに変更

---

web/admin/src/store/administrator.ts
web/admin/src/store/auth.ts
web/admin/src/store/index.ts
web/admin/src/store/producer.ts

- 自動生成されるAPIクライアントコードのAPIのベースパスの変更が難しい問題への対応
- 自動生成されるAPIクライアントのコードを使い回せるようにAPIClientのfactoryクラスを作った。

ApiClientのfactoryを作って環境変数で柔軟にAPIの向き先を変える

---

web/admin/src/store/auth.ts

- リフレッシュトークンで取得した認証情報にはリフレッシュトークンが含まれておらず、ミドルウェアのCookieの部分で空文字がセットされていたので修正した。

fix: refreshTokenで認証情報を取ったあとはcookieを再セットしない

---

web/admin/nuxt.config.ts
web/admin/src/assets/main.scss
web/admin/src/components/molecules/TheHeaderSelectForm.vue
web/admin/src/components/molecules/TheProfileSelectForm.vue
web/admin/src/pages/producers/add.vue
web/admin/src/store/producer.ts

- 生産者登録でアイコン画像とヘッダー画像がアップロードできるようにした
- 住所をAPIを使って入力補完する
- 生産者登録後のユーザーフィードバックの実装

feat: 生産者登録機能の改善

---

api/config/messenger/mailer/dev.yaml
api/config/messenger/mailer/stg.yaml
api/internal/messenger/entity/mail.go
api/internal/messenger/entity/mail_test.go
api/internal/messenger/entity/payload.go
api/internal/messenger/entity/received_queue_test.go
api/internal/messenger/service/notify.go
api/internal/messenger/service/notify_test.go
api/internal/messenger/worker/mailer.go
api/internal/messenger/worker/mailer_test.go
api/internal/messenger/worker/worker.go
api/internal/messenger/worker/worker_test.go

お問い合わせ受領通知用のメールテンプレート設定を追加しました。

feat(messenger): add email template for received contact

---

api/internal/user/service/admin_auth.go
api/internal/user/service/admin_auth_test.go
docs/swagger/admin/paths/v1/auth/email/index.yaml

管理者が自分のメールアドレスを変更するためのAPIについて、以下フロントエンドからの要望を満たすような修正を行いました。
* 変更後のメールアドレスが現在と同じ場合、4xx系エラーを返す -> 412(Precondition Failed)を割り当てています

fix(user): add error handling for update admin email

---

api/internal/gateway/admin/v1/handler/contact.go
api/internal/gateway/admin/v1/handler/contact_test.go
api/internal/gateway/admin/v1/handler/message.go
api/internal/gateway/admin/v1/handler/message_test.go
api/internal/messenger/database/contact.go
api/internal/messenger/database/contact_test.go
api/internal/messenger/database/database.go
api/internal/messenger/database/message.go
api/internal/messenger/database/message_test.go
api/internal/messenger/database/notification_test.go
api/internal/messenger/entity/contact.go
api/internal/messenger/entity/message.go
api/internal/messenger/entity/notification.go
api/internal/messenger/input.go
api/internal/messenger/service/contact.go
api/internal/messenger/service/contact_test.go
api/internal/messenger/service/message.go
api/internal/messenger/service/message_test.go
docs/swagger/admin/paths/v1/contacts/index.yaml
docs/swagger/admin/paths/v1/messages/index.yaml
web/admin/src/types/api/api.ts

feat(messenger): add sort query for list api

---

web/admin/src/middleware/auth.ts
web/admin/src/plugins/firebase.ts
web/admin/src/store/auth.ts
web/admin/test/store/auth.spec.ts
web/admin/test/store/producer.spec.ts

サインイン後もしくはサインイン後の画面を描画したタイミングでPush通知の有効化ダイアログが出るようにしました。
また、有効にした後、API側へデバイストークンを共有するような設定を追加しました。

feat(web/admin): implement register device token client

---

api/internal/messenger/database/database.go
api/internal/messenger/database/notification.go
api/internal/messenger/database/notification_test.go
api/internal/messenger/entity/notification.go
api/mock/messenger/database/database.go
infra/mysql/schema/2022082501-messengers-add-column.sql

- deleted_atカラムを追加するSQL作成
- notificationのentityにDeletedAtを追加
- DeleteNotificationのデータベース層の実装
SQL追加したので、`make migrate`は必要

Feat/delete notification/database layer

---

web/admin/src/lib/validations/index.ts
web/admin/src/lib/validations/message.ts
web/admin/src/lib/validations/rule.ts
web/admin/src/pages/accounts/password/index.vue
web/admin/src/pages/coordinator/add.vue
web/admin/src/pages/products/add.vue

- コーディーネータ登録時にバリデーションを追加
- パスワード変更画面にバリデーションを追加

管理者ページのフロントエンドバリデーションを追加

---

api/internal/store/entity/live.go
api/internal/store/entity/live_test.go
api/internal/store/input.go
api/internal/store/service/live.go
api/internal/store/service/live_test.go
api/internal/store/service/service.go
api/internal/store/service/service_test.go
api/mock/pkg/ivs/client.go
api/pkg/ivs/channel.go
api/pkg/ivs/client.go
api/pkg/ivs/stream.go
infra/mysql/schema/2022111901-stores-alter-column-lives.sql

- livesテーブルにstreamkey_arn 用のカラムを追加
- GetLiveのservice層実装
- Liveのentity修正
- LiveのentityにFillIVSメソッド追加
- GetLiveのテスト実装
https://calmato.kibe.la/notes/727#%E8%A6%96%E8%81%B4%E8%80%85%E6%95%B0%E3%82%92%E5%8F%96%E5%BE%97
- [channel](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ivs@v1.18.6/types#Channel)
- [stream](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ivs@v1.18.6/types#Stream)
- [streamKey](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ivs@v1.18.6/types#StreamKey)
gateway実装

Feat/get live/service layer

---

api/config/gateway/admin/rbac/policy.csv
api/internal/gateway/admin/v1/handler/api.go
api/internal/gateway/admin/v1/handler/live.go
api/internal/gateway/admin/v1/handler/live_test.go
api/internal/gateway/admin/v1/response/live.go
api/internal/gateway/admin/v1/service/live.go
api/internal/gateway/admin/v1/service/live_test.go
api/internal/store/service.go
api/mock/store/service.go

- 権限追加
- liveのresponse修正
- GetLiveのGateway追加
- make mockgen
https://calmato.kibe.la/notes/727#%E3%83%95%E3%83%AD%E3%83%BC
テスト落ちます…助けてください…
```
=== CONT  TestGetLive/success
/Users/kaito/Documents/calmato/marche/api/internal/gateway/admin/v1/handler/api_test.go:246:
Error Trace:	/Users/kaito/Documents/calmato/marche/api/internal/gateway/admin/v1/handler/api_test.go:246
/Users/kaito/Documents/calmato/marche/api/internal/gateway/admin/v1/handler/api_test.go:154
/Users/kaito/Documents/calmato/marche/api/internal/gateway/admin/v1/handler/live_test.go:280
Error:      	Not equal:
expected: 200
actual  : 404
Test:       	TestGetLive/success
/Users/kaito/Documents/calmato/marche/api/internal/gateway/admin/v1/handler/controller.go:269: missing call(s) to *mock_store.MockService.MultiGetProducts(is …
```

Feat(store) implement GetLive gateway

---

web/admin/src/components/molecules/ShippingRateForm.vue
web/admin/src/components/organisms/ShippingForm.vue
web/admin/src/components/templates/ContactList.vue
web/admin/src/lib/prefectures/helper.ts
web/admin/src/lib/validations/rule.ts
web/admin/src/pages/contacts/index.vue
web/admin/src/pages/coordinators/edit/[id].vue
web/admin/src/pages/coordinators/index.vue
web/admin/src/pages/customers/edit/[id].vue
web/admin/src/pages/customers/index.vue
web/admin/src/pages/notifications/index.vue
web/admin/src/pages/orders/[id].vue
web/admin/src/pages/orders/index.vue
web/admin/src/pages/producers/index.vue
web/admin/src/pages/promotions/index.vue
web/admin/src/pages/shippings/add.vue
web/admin/src/pages/shippings/edit/[id].vue
web/admin/src/pages/shippings/index.vue

- データテーブルから「編集」ボタンで詳細画面に遷移する部分を行クリックで遷移するように書き換えた
https://calmato.atlassian.net/jira/software/c/projects/FA/boards/4?modal=detail&selectedIssue=FA-13

データテーブルから「編集」ボタンで詳細画面に遷移する部分を行クリックで遷移するように書き換えた

---

web/admin/src/components/organisms/CategoryList.vue
web/admin/src/components/templates/CategoryList.vue
web/admin/src/pages/categories/index.vue

- wip: 品目登録側は要対応
- カテゴリー登録のバリデーションを調整
- `props`書き換えまくっていたのでリファクタした。

カテゴリー登録のバリデーションを調整

---

web/admin/src/components/organisms/ProductForm.vue
web/admin/src/lib/validations/rule.ts
web/admin/src/pages/products/[id].vue
web/admin/src/pages/products/add.vue

- 商品登録・更新でサムネイルの選択肢を使えるようにした
- バリデーションをかけた

商品登録・更新の選択とバリデーションの実装

---

web/admin/src/components/templates/AuthEditEmail.vue

- メールアドレス更新フォームでフロントエンド側でバリデーションを追加した

メールアドレス更新フォームでフロントエンド側でバリデーションを追加した

---

web/admin/src/components/templates/ProductList.vue

- 削除ボタンクリックに`.stop`修飾子をつけてボタンクリック後の`row-click`イベントを伝播させないようにした。

商品削除ボタンをクリックしても詳細画面に遷移しないようにする

---

web/user/src/assets/css/tailwind.css
web/user/src/components/atoms/cards/TheCard.vue
web/user/tailwind.config.ts

- ユーザー画面側のフォント設定を`Noto Sans JP`に変更
- 認証系画面の枠内の背景色を`#FFFFFF`に変更

ユーザー側ページのフォント変更と枠内背景色の更新

---

web/user/package.json
web/user/yarn.lock

- バグるので@nuxtjs/i18nを8.0.0-beta.8に戻した。
- Dependabotでバージョンアップされていた。

@nuxtjs/i18nを8.0.0-beta.8に戻す

---

api/internal/gateway/admin/v1/handler/contact.go
api/internal/gateway/admin/v1/handler/contact_category.go
api/internal/gateway/admin/v1/handler/thread.go
api/internal/gateway/admin/v1/response/contact.go
api/internal/gateway/admin/v1/response/thread.go
api/internal/gateway/admin/v1/service/thread.go
api/internal/messenger/database/contact_category.go
api/internal/messenger/database/contact_category_test.go
api/internal/messenger/database/database.go
api/internal/messenger/entity/contact.go
api/internal/messenger/entity/contact_test.go
api/internal/messenger/entity/thread.go
api/internal/messenger/entity/thread_test.go
api/internal/messenger/input.go
api/internal/messenger/service.go
api/internal/messenger/service/contact_category.go
api/mock/messenger/database/database.go
api/mock/messenger/service.go
docs/swagger/admin/components/schemas/entity/contact-category.yaml
docs/swagger/admin/components/schemas/entity/contact.yaml
docs/swagger/admin/components/schemas/entity/thread.yaml
docs/swagger/admin/components/schemas/v1/contact-category.response.yaml
docs/swagger/admin/components/schemas/v1/contact.response.yaml
docs/swagger/admin/components/schemas/v1/thread.response.yaml
docs/swagger/admin/openapi.yaml
web/admin/src/components/templates/ContactList.vue
web/admin/src/store/contact.ts
web/admin/src/types/api/api.ts

- api
- 単体のresponse更新
- 単体のresponseを返すhandlerを更新
- swagger
- entity作成
- contactのresponse更新

Chanege architecture

---

infra/serverless/serverless.yml

MediaLiveのチャンネルを削除
アタッチされていた入力のStateがDetachedになったのを確認して入力の削除を並列実行
StepFunctionsに渡す入力値はChannelIdのみ

feat: add DeleteMediaLiveResourcesFunction

---

func/go.mod
func/go.sum

Reverts and-period/furumaru#1404

Revert "chore(deps): bump github.com/aws/aws-sdk-go-v2/config from 1.18.37 to 1.19.1 in /func"

---

api/go.mod
api/go.sum

Reverts and-period/furumaru#1414

Revert "chore(deps): bump github.com/aws/aws-sdk-go-v2/internal/ini from 1.3.42 to 1.3.45 in /api"

---

web/user/.eslintrc.cjs
web/user/src/layouts/default.vue

- ヘッダーの伸縮時にコンテンツエリアの要素の高さが安定しない挙動があったので修正した。

ヘッダーの伸縮時の挙動を修正

---

web/admin/src/components/molecules/VideoSelectForm.vue

https://calmato.atlassian.net/browse/FA-94
mp4以外を選択すると、アップロード失敗していたので、mp4のみ選択できるようにした

Fix: we can select only mp4 file

---

web/user/.gitignore
web/user/package.json
web/user/predev.sh

NPMスクリプトに`predev`コマンドを用意し、[mkcert](https://github.com/FiloSottile/mkcert)を使って自己証明書を生成し、その証明書を使ってhttpsでローカルの開発サーバを立ち上げるように設定を変更した。
マージ後の初回の`yarn dev`時にライブラリのインストールで自己証明書の生成が入るので、rootパスワードといろいろと設定ウィンドウが出るかもだけど、そのセットアップをすれば問題なく動作します。

ローカルの開発サーバをhttpsで立ち上げるための設定の追加

---

api/go.mod
api/go.sum

Reverts and-period/furumaru#1628

Revert "chore(deps): bump github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery from 1.8.1 to 1.8.4 in /api"

---

api/go.mod
api/go.sum

Reverts and-period/furumaru#1652

Revert "chore(deps): bump github.com/aws/aws-sdk-go-v2/service/internal/presigned-url from 1.10.1 to 1.10.5 in /api"

---

infra/serverless/functions/getExistsChannelIndex/handler.js
infra/serverless/serverless.yml

- 既存のチャンネル一覧を取得
- 一つもチャンネルがない場合チャンネル作成
- Inputのチャンネル名と一致するチャンネルがあれば情報を抽出して作成をスキップ
- 一致するチャンネルがなければチャンネル作成

チャンネル作成時に重複を回避する処理を追加

---

api/internal/store/service/schedule.go
api/internal/store/service/schedule_test.go

feat(messenger): ライブ開始通知の送信予約処理を追加

---

web/admin/src/components/organisms/LiveList.vue
web/admin/src/components/organisms/ScheduleShow.vue
web/admin/src/components/templates/ProductEdit.vue
web/admin/src/components/templates/ProductNew.vue
web/admin/src/components/templates/ScheduleNew.vue

- Admin側のHTMLエディタをtextareaに変更
- 商品説明
- 配信スケジュール
- 配信詳細

Admin側のHTMLのエディタを取り除く

---

web/user/src/pages/index.vue

fix: アーカイブに表示するコンテンツが少ない場合にレイアウトが崩れる問題に対応

---

CHANGELOG.md

This pull request is for the next release as v1.11.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.3

---

CHANGELOG.md

This pull request is for the next release as v1.11.4 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.4 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.4

---

CHANGELOG.md

This pull request is for the next release as v1.11.5 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.5 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.4" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.5

---

CHANGELOG.md

This pull request is for the next release as v1.11.7 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.7 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.6" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.7

---

CHANGELOG.md

This pull request is for the next release as v1.11.8 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.8 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.7" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.8

---

CHANGELOG.md

This pull request is for the next release as v1.11.13 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.13 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.12" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.13

---

CHANGELOG.md

This pull request is for the next release as v1.11.14 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.14 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.13" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.14

---

infra/serverless/serverless.yml

originAccessControlの削除処理を追加
挙動確認したStep Function
https://ap-northeast-1.console.aws.amazon.com/states/home?region=ap-northeast-1#/v2/executions/details/arn:aws:states:ap-northeast-1:386661535629:execution:deleteCloudFrontResoursesFunction-stg:6cb83c29-131e-42ee-b30e-8978aca424d4

feat(serverless): originAccessControlの削除処理を追加

---

CHANGELOG.md

This pull request is for the next release as v1.11.15 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.15 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.14" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.15

---

CHANGELOG.md

This pull request is for the next release as v1.11.17 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.17 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.16" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.17

---

CHANGELOG.md

This pull request is for the next release as v1.11.18 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.18 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.17" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.18

---

CHANGELOG.md

This pull request is for the next release as v1.11.19 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.19 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.18" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.19

---

CHANGELOG.md

This pull request is for the next release as v1.11.20 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.20 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.19" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.20

---

CHANGELOG.md

This pull request is for the next release as v1.11.21 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.21 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.20" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.21

---

CHANGELOG.md

This pull request is for the next release as v1.11.22 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.22 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.21" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.22

---

CHANGELOG.md

This pull request is for the next release as v1.11.23 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.23 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.22" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.23

---

CHANGELOG.md

This pull request is for the next release as v1.11.24 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.24 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.23" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.24

---

CHANGELOG.md

This pull request is for the next release as v1.11.25 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.25 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.24" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.25

---

CHANGELOG.md

This pull request is for the next release as v1.11.26 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.26 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.25" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.26

---

CHANGELOG.md

This pull request is for the next release as v1.11.27 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.27 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.26" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.27

---

CHANGELOG.md

This pull request is for the next release as v1.11.28 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.28 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.27" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.28

---

CHANGELOG.md

This pull request is for the next release as v1.11.29 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.29 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.28" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.29

---

CHANGELOG.md

This pull request is for the next release as v1.11.30 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.30 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.29" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.30

---

CHANGELOG.md

This pull request is for the next release as v1.11.31 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.31 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.30" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.31

---

CHANGELOG.md

This pull request is for the next release as v1.11.32 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.32 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.31" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.32

---

CHANGELOG.md

This pull request is for the next release as v1.11.33 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.33 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.32" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.33

---

CHANGELOG.md

This pull request is for the next release as v1.11.34 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.34 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.33" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.34

---

CHANGELOG.md

This pull request is for the next release as v1.11.35 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.35 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.34" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.35

---

CHANGELOG.md

This pull request is for the next release as v1.11.36 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.36 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.35" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.36

---

CHANGELOG.md

This pull request is for the next release as v1.11.37 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.37 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.36" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.37

---

CHANGELOG.md

This pull request is for the next release as v1.11.38 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.38 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.37" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.38

---

CHANGELOG.md

This pull request is for the next release as v1.11.39 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.39 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.38" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.39

---

CHANGELOG.md

This pull request is for the next release as v1.11.40 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.40 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.39" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.40

---

CHANGELOG.md

This pull request is for the next release as v1.11.41 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.41 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.40" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.41

---

CHANGELOG.md

This pull request is for the next release as v1.11.42 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.42 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.41" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.42

---

CHANGELOG.md

This pull request is for the next release as v1.11.43 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.43 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.42" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.43

---

CHANGELOG.md

This pull request is for the next release as v1.11.44 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.44 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.43" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.44

---

CHANGELOG.md

This pull request is for the next release as v1.11.46 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.46 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.45" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v1.11.46

---

CHANGELOG.md

This pull request is for the next release as v2.0.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v2.0.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.46" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v2.0.0

---

CHANGELOG.md

This pull request is for the next release as v2.0.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v2.0.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v2.0.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v2.0.1

---

CHANGELOG.md

This pull request is for the next release as v3.0.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.1

---

CHANGELOG.md

This pull request is for the next release as v3.0.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.2

---

CHANGELOG.md

This pull request is for the next release as v3.0.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.3

---

CHANGELOG.md

This pull request is for the next release as v3.0.5 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.5 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.4" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.5

---

CHANGELOG.md

This pull request is for the next release as v3.0.6 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.6 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.5" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.6

---

CHANGELOG.md

This pull request is for the next release as v3.0.7 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.7 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.6" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.7

---

CHANGELOG.md

This pull request is for the next release as v3.0.8 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.8 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.7" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.0.8

---

CHANGELOG.md

This pull request is for the next release as v3.1.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.1.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.8" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.1.0

---

CHANGELOG.md

This pull request is for the next release as v3.1.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.1.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.1.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.1.1

---

CHANGELOG.md

This pull request is for the next release as v3.1.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.1.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.1.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.1.2

---

CHANGELOG.md

This pull request is for the next release as v3.2.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.2.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.1.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.2.0

---

CHANGELOG.md

This pull request is for the next release as v3.2.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.2.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.2.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.2.2

---

CHANGELOG.md

This pull request is for the next release as v3.2.5 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.2.5 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.2.4" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.2.5

---

CHANGELOG.md

This pull request is for the next release as v3.2.6 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.2.6 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.2.5" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.2.6

---

CHANGELOG.md

This pull request is for the next release as v3.2.7 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.2.7 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.2.6" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.2.7

---

CHANGELOG.md

This pull request is for the next release as v3.2.8 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.2.8 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.2.7" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.2.8

---

CHANGELOG.md

This pull request is for the next release as v3.3.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.3.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.2.8" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.3.0

---

CHANGELOG.md

This pull request is for the next release as v3.4.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.4.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.3.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.4.0

---

CHANGELOG.md

This pull request is for the next release as v3.4.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.4.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.4.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v3.4.2

---

CHANGELOG.md

This pull request is for the next release as v4.0.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.4.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.0

---

CHANGELOG.md

This pull request is for the next release as v4.0.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.1

---

CHANGELOG.md

This pull request is for the next release as v4.0.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.2

---

CHANGELOG.md

This pull request is for the next release as v4.0.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.3

---

CHANGELOG.md

This pull request is for the next release as v4.0.4 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.4 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.4

---

CHANGELOG.md

This pull request is for the next release as v4.0.5 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.5 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.4" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.5

---

CHANGELOG.md

This pull request is for the next release as v4.0.6 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.6 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.5" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.6

---

CHANGELOG.md

This pull request is for the next release as v4.0.7 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.0.7 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.6" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.0.7

---

CHANGELOG.md

This pull request is for the next release as v4.1.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.1.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.0.7" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.1.0

---

CHANGELOG.md

This pull request is for the next release as v4.1.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.1.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.1.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.1.1

---

CHANGELOG.md

This pull request is for the next release as v4.2.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.2.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.2.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.2.1

---

CHANGELOG.md

This pull request is for the next release as v4.2.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.2.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.2.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.2.2

---

CHANGELOG.md

This pull request is for the next release as v4.3.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.3.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.2.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.3.0

---

CHANGELOG.md

This pull request is for the next release as v4.3.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.3.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.3.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.3.1

---

CHANGELOG.md

This pull request is for the next release as v4.4.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.3.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.0

---

CHANGELOG.md

This pull request is for the next release as v4.4.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.1

---

CHANGELOG.md

This pull request is for the next release as v4.4.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.2

---

CHANGELOG.md

This pull request is for the next release as v4.4.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.3

---

CHANGELOG.md

This pull request is for the next release as v4.4.4 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.4 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.4

---

CHANGELOG.md

This pull request is for the next release as v4.4.6 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.6 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.5" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.6

---

CHANGELOG.md

This pull request is for the next release as v4.4.7 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.7 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.6" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.7

---

CHANGELOG.md

This pull request is for the next release as v4.4.8 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.8 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.7" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.8

---

CHANGELOG.md

This pull request is for the next release as v4.4.9 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.9 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.8" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.9

---

CHANGELOG.md

This pull request is for the next release as v4.4.10 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.10 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.9" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.10

---

CHANGELOG.md

This pull request is for the next release as v4.4.11 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.11 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.10" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.11

---

CHANGELOG.md

This pull request is for the next release as v4.4.14 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.14 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.13" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.14

---

CHANGELOG.md

This pull request is for the next release as v4.4.15 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.15 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.14" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.15

---

CHANGELOG.md

This pull request is for the next release as v4.4.16 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v4.4.16 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v4.4.15" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v4.4.16

---

CHANGELOG.md

This pull request is for the next release as v5.0.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.1

---

CHANGELOG.md

This pull request is for the next release as v5.0.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.3

---

CHANGELOG.md

This pull request is for the next release as v5.0.4 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.4 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.4

---

CHANGELOG.md

This pull request is for the next release as v5.0.7 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.7 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.6" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.7

---

CHANGELOG.md

This pull request is for the next release as v5.0.8 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.8 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.7" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.8

---

CHANGELOG.md

This pull request is for the next release as v5.0.9 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.9 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.8" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.9

---

CHANGELOG.md

This pull request is for the next release as v5.0.11 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.0.11 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.10" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.0.11

---

CHANGELOG.md

This pull request is for the next release as v5.1.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.1.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.0.11" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.1.0

---

CHANGELOG.md

This pull request is for the next release as v5.1.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v5.1.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.1.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v5.1.2

---

CHANGELOG.md

This pull request is for the next release as v6.0.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v6.0.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v5.1.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v6.0.0

---

CHANGELOG.md

This pull request is for the next release as v6.0.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v6.0.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v6.0.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v6.0.1

---

CHANGELOG.md

This pull request is for the next release as v7.0.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v7.0.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v6.0.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v7.0.0

---

CHANGELOG.md

This pull request is for the next release as v7.1.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v7.1.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v7.1.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v7.1.1

---

CHANGELOG.md

This pull request is for the next release as v7.1.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v7.1.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v7.1.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v7.1.3

---

CHANGELOG.md

This pull request is for the next release as v7.2.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v7.2.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v7.2.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …

Release for v7.2.1
