- .github/labeler.yaml
- .github/reviewer.yaml
レビュアーの追加をしました。みんながOrganizationに参加したらうまく機能するようになるはず
GitHubのセットアップしてて思ったんだけど、最近はGitHubのデフォルトでレビューア追加する機能入ったみたいね笑
> feat(workflow): update reviewer

- api/internal/user/api/user_auth.go
- api/internal/user/api/user_auth_test.go
- api/internal/user/entity/auth.go
- api/internal/user/entity/auth_test.go
- api/proto/user/auth.proto
- api/proto/user/service.proto
> feat(api/user): implement get user auth

- api/internal/user/api/user.go
- api/internal/user/api/user_test.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/proto/user/service.proto
- api/proto/user/user.proto
購入者関連APIのProto定義を行いました。(Proto定義までで詳細実装はTODO状態になっています)
PR差分結構多いですが、4/5はテストとMock生成なのでサクッと見ていただけると助かります🙇‍♂️
> feat(user/api): define user api proto

- api/internal/user/api/user.go
- api/internal/user/api/user_test.go
- api/internal/user/database/database.go
- api/internal/user/database/user.go
- api/internal/user/database/user_test.go
- api/mock/user/database/database.go
- infra/mysql/schema/2022030801-users-change-index.sql
> feat(api/user): implement update password api

- api/internal/user/api/user.go
- api/internal/user/api/user_test.go
- api/internal/user/database/database.go
- api/internal/user/database/user.go
- api/internal/user/database/user_test.go
- api/mock/pkg/cognito/client.go
- api/mock/user/database/database.go
- api/pkg/cognito/client.go
- api/pkg/cognito/user.go
> feat(api/user): implement update email api

- api/internal/gateway/user/v1/handler/user.go
- api/internal/gateway/user/v1/handler/user_test.go
> feat(gateway): implement get user me api

- api/internal/gateway/user/v1/handler/api_test.go
- api/internal/gateway/user/v1/handler/user.go
- api/internal/gateway/user/v1/handler/user_test.go
> feat(gateway): implement create user api

- api/internal/gateway/user/v1/handler/user.go
- api/internal/gateway/user/v1/handler/user_test.go
> feat(gateway): implement update user email api

- api/internal/gateway/cmd/user/exec.go
- api/internal/user/cmd/server/exec.go
- api/internal/user/cmd/server/registry.go
- api/internal/user/database/user.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/pkg/database/client.go
- api/pkg/database/client_test.go
- api/pkg/grpc/options.go
- api/pkg/grpc/options_test.go
- api/pkg/log/gin.go
- api/pkg/log/gin_test.go
- api/pkg/log/logger.go
- api/pkg/log/logger_test.go
昔作ってからあまり更新かけられていなかった(たぶんgran作ってたときから...)共通パッケージについて、せっかくなので少しずつリファクタ進めました。
> refactor(api): refactor common package

- infra/mysql/schema/2022041501-users-add-column.sql
- infra/mysql/schema/2022042001-users-add-unique-index.sql
usersテーブルのaccount_idにユニークインデックスを追加
> feat: add unique index to account_id

- Makefile
> feat: update Makefile

- api/proto/user/user.proto
InitializeUser用にuser.protoにおけるUser定義を修正
pull後にmake protoc
> feat(user_api): add account_id,  username to proto

- web/user/src/components/molecules/TheHeaderMenuButton.vue
- web/user/src/components/organisms/TheAppHeader.vue
- web/user/src/layouts/default.vue
- web/user/src/locales/en_us.ts
- web/user/src/locales/ja_jp.ts
- web/user/src/types/locales/i18n.ts
> ホーム画面のヘッダーコンポーネントを実装

- api/internal/gateway/admin/v1/handler/store_test.go
- api/internal/gateway/admin/v1/service/staff.go
- api/internal/user/database/database.go
- api/internal/user/database/shop.go
- api/internal/user/database/shop_test.go
- api/internal/user/entity/shop.go
- api/internal/user/entity/shop_test.go
- api/internal/user/service/input.go
- api/internal/user/service/service.go
- api/internal/user/service/service_test.go
- api/internal/user/service/shop.go
- api/internal/user/service/shop_test.go
- api/mock/user/database/database.go
- api/mock/user/service/service.go
- infra/mysql/schema/2022050701-users-alter-column-shops.sql
> feat(user): implement get shop api

- api/internal/user/database/database.go
- api/internal/user/database/shop.go
- api/internal/user/database/shop_test.go
- api/internal/user/entity/shop.go
- api/internal/user/entity/shop_test.go
- api/internal/user/service/input.go
- api/internal/user/service/service.go
- api/internal/user/service/shop.go
- api/internal/user/service/shop_test.go
- api/mock/pkg/cognito/client.go
- api/mock/user/database/database.go
- api/mock/user/service/service.go
- api/pkg/cognito/admin.go
- api/pkg/cognito/client.go
- api/pkg/validator/validator.go
- api/pkg/validator/validator_test.go
> feat(user): implement create shop api

- api/internal/user/database/admin.go
- api/internal/user/database/admin_test.go
- api/internal/user/database/database.go
- api/internal/user/entity/admin.go
- api/internal/user/entity/admin_test.go
- api/internal/user/service/admin.go
- api/internal/user/service/admin_test.go
- api/internal/user/service/input.go
- api/mock/pkg/cognito/client.go
- api/mock/user/database/database.go
- api/pkg/cognito/admin.go
- api/pkg/cognito/client.go
> feat(user): implement admin api

- api/internal/user/service/admin_auth.go
- api/internal/user/service/admin_auth_test.go
- api/internal/user/service/user_auth.go
> feat(user): implement auth admin

- api/hack/create-admin/main.go
- api/internal/user/service/admin.go
- api/internal/user/service/service.go
- api/internal/user/service/shop.go
- api/mock/pkg/cognito/client.go
- api/mock/user/service/service.go
- api/pkg/cognito/admin.go
- api/pkg/cognito/client.go
- api/pkg/random/string.go
- api/pkg/random/string_test.go
> feat(user): implement create admin

- docs/swagger/admin/components/schemas/v1/admins.request.yaml
- docs/swagger/admin/components/schemas/v1/admins.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/admins/_adminId/index.yaml
- docs/swagger/admin/paths/v1/admins/index.yaml
- web/admin/src/types/api/api.ts
- web/admin/src/types/api/base.ts
> feat(docs): add admin api specification

- api/config/gateway/admin/rbac/policy.csv
- api/hack/create-admin/main.go
- api/internal/gateway/admin/v1/handler/admin.go
- api/internal/gateway/admin/v1/handler/admin_test.go
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/auth.go
- api/internal/gateway/admin/v1/handler/auth_test.go
- api/internal/gateway/admin/v1/handler/store.go
- api/internal/gateway/admin/v1/request/admin.go
- api/internal/gateway/admin/v1/request/auth.go
- api/internal/gateway/admin/v1/response/admin.go
- api/internal/gateway/admin/v1/response/auth.go
- api/internal/gateway/admin/v1/service/admin.go
- api/internal/gateway/admin/v1/service/admin_test.go
- api/internal/gateway/admin/v1/service/auth.go
- api/internal/gateway/admin/v1/service/auth_test.go
- api/internal/gateway/admin/v1/service/staff_test.go
- api/internal/gateway/admin/v1/service/store_test.go
- api/internal/gateway/util/request.go
- api/internal/gateway/util/request_test.go
- api/internal/user/entity/admin.go
- api/internal/user/input.go
- api/internal/user/service/admin.go
- api/internal/user/service/admin_test.go
> feat(gateway): implement admin auth api

- api/internal/gateway/admin/v1/handler/api.go
- docs/swagger/admin/components/schemas/v1/stores.request.yaml
- docs/swagger/admin/components/schemas/v1/upload.request.yaml
- docs/swagger/admin/components/schemas/v1/upload.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/stores/_storeId/index.yaml
- docs/swagger/admin/paths/v1/stores/index.yaml
- docs/swagger/admin/paths/v1/upload/stores/thumbnail.yaml
- web/admin/src/types/api/api.ts
* TODOにしていた認証周りの実装
* 管理者APIのSwagger未記載部分の追記
> feat(gateway): implement authorization middleware

- docs/swagger/admin/components/schemas/v1/admins.request.yaml
- docs/swagger/admin/components/schemas/v1/admins.response.yaml
- docs/swagger/admin/components/schemas/v1/auth.request.yaml
- docs/swagger/admin/components/schemas/v1/auth.response.yaml
- docs/swagger/admin/components/schemas/v1/upload.request.yaml
- docs/swagger/admin/components/schemas/v1/upload.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/auth/email/index.yaml
- docs/swagger/admin/paths/v1/auth/email/verified.yaml
- docs/swagger/admin/paths/v1/auth/password.yaml
- docs/swagger/admin/paths/v1/auth/user.yaml
- docs/swagger/admin/paths/v1/upload/coordinators/thumbnail.yaml
- docs/swagger/admin/paths/v1/upload/producers/thumbnail.yaml
- web/admin/src/types/api/api.ts
> feat(docs): update admin swagger

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- api/internal/gateway/admin/v1/request/producer.go
- api/internal/gateway/admin/v1/response/producer.go
- docs/swagger/admin/components/schemas/v1/producers.request.yaml
- docs/swagger/admin/components/schemas/v1/producers.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/index.yaml
- docs/swagger/admin/paths/v1/producers/index.yaml
- web/admin/src/types/api/api.ts
* 生産者関連のAPI仕様書作成
* 生産者関連のAPIモックを定義
* Admin Gatewayへのアクセス権限を整理
> feat(gateway): create producer api mock

- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/gateway/cmd/admin/exec.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/cmd/user/exec.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/router.go
- api/internal/user/service/admin.go
ginのミドルウェアの適用順によってpanic起きたときにステータス200が変えるという状態になってしまうことがわかったので、pcnicが起きたときは正常にrecovery処理に入るよう修正しました。
また、そのたミドルウェアについてもついでなので追加してみました。
> feat(api): setup http server middleware

- .github/reviewer.yaml
> feat(workflow): update pr reviewer

- api/internal/user/entity/admin_auth.go
- api/internal/user/entity/administrator.go
- api/internal/user/entity/administrator_test.go
- api/internal/user/entity/producer.go
- api/internal/user/entity/producer_test.go
- api/internal/user/entity/user.go
- api/internal/user/entity/user_test.go
- api/internal/user/service/administrator.go
- api/internal/user/service/administrator_test.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/internal/user/service/user.go
- api/internal/user/service/user_test.go
* 管理者作成メソッドのバグ修正
* ユーザー, 管理者Entity作成メソッドのリファクタ
* テストケース追加
> fix(user): fix create user and admin logic

- api/internal/user/input.go
> fix(user): fix create producer validation

- api/internal/gateway/admin/v1/request/producer.go
> fix(gateway): fix typo in create producer request

- api/pkg/cognito/user.go
> fix(cognito): fix cognito client

- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/index.yaml
> fix(docs): fix typo

- api/Makefile
- api/config/gateway/admin/.air.toml
- api/config/gateway/user/.air.toml
- api/internal/gateway/admin/v1/response/producer.go
- api/internal/gateway/cmd/admin/exec.go
- api/internal/gateway/cmd/user/exec.go
- docker-compose.yaml
- infra/docker/api/Dockerfile.development
* エンジニアの人数が増えてきたので、ローカルでAPIが動かしやすいようにいくつか設定ファイル追加しました。
* 動作検証時に見つけたtypoも併せて修正しました。
* マージ後、以下コマンドの実行お願いします
```sh
$ docker-compose build user_gateway admin_gateway
$ make migrate
```
> feat(api): setup api container

- api/internal/gateway/admin/v1/handler/uploader.go
* golangのio.Readerの仕様として、一度読んだあと再度読み込みすることは不可という仕様があり、S3に空のファイルをアップロードしている状態になっていましたため、readする前にcopyすることで正常にアップロードできるように修正しました。
* ファイル名の末尾に拡張子がない状態だったため、拡張子を付与するよう修正しました。
> fix(gateway): fix uploader

- api/internal/store/database/category.go
- api/internal/store/database/database.go
- api/internal/store/database/product_type.go
- api/internal/store/database/product_type_test.go
- api/internal/store/entity/product_type.go
- api/internal/store/entity/product_type_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/product_type.go
- api/internal/store/service/product_type_test.go
- api/internal/store/service/service_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
> feat(store): implement product type

- api/internal/store/entity/product.go
- infra/mysql/schema/2022061401-stores-add-column.sql
* 商品情報テーブルで登録者ID, 更新者IDを管理できるようにしました
> feat(store): add column to product

- api/internal/gateway/admin/v1/handler/administrator.go
- api/internal/gateway/admin/v1/handler/auth.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/user/v1/handler/auth.go
- api/internal/gateway/util/metadata.go
- api/internal/gateway/util/metadata_test.go
* マイクロサービスためたことによって不要になったメソッドを削除しました。
> refactor(gateway): remove unnecessary method

- api/mock/user/database/database.go
> fix(user): make mockgen

- api/pkg/mailer/sender_test.go
> fix(*): fix mailer test code

- web/admin/package.json
- web/admin/src/components/TiptapEditor.vue
- web/admin/src/components/atoms/TheFileUploadFiled.vue
- web/admin/src/pages/products/add.vue
- web/admin/yarn.lock
- 商品登録ページのデザイン改善
イメージと相違無いかを確認したく🙏
- 一部やっつけ実装になっているので直します。
- リッチエディタで画像アップロード機能がないのでつけます。
> 商品登録ページのデザイン改善

- api/internal/store/database/database.go
- api/internal/store/database/product.go
- api/internal/store/database/product_test.go
- api/internal/store/entity/product.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
* 商品関連メソッドのインターフェース定義を追加
* -> 詳細実装含めると差分が多くなるため、インターフェース定義までとしています
> feat(store): define product interface

- infra/mysql/schema/2022061801-messengers-create-notifications.sql
* messengers データベース作成用のDDLのtypoを修正しました
> fix(infra): fix typo in create messengers database ddl

- api/config/gateway/admin/rbac/policy.csv
- api/go.mod
- api/go.sum
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_test.go
- api/internal/gateway/admin/v1/response/product.go
- api/internal/gateway/admin/v1/service/product.go
- api/internal/gateway/admin/v1/service/product_test.go
- api/internal/gateway/admin/v1/service/product_type_test.go
> feat(gateway): implement get product api

- docs/swagger/admin/components/schemas/v1/product.request.yaml
- docs/swagger/admin/components/schemas/v1/product.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/products/_productId/index.yaml
- docs/swagger/admin/paths/v1/products/index.yaml
- web/admin/src/types/api/api.ts
* 商品関連APIの仕様書を記載しました
* [openapi.yaml.zip](https://github.com/and-period/furumaru/files/9022275/openapi.yaml.zip)
@wf-yamaday ↑に生成したyamlをアップしたので、問題なさそうか確認して欲しいです🙏
> feat(docs): define product api types

- api/internal/user/database/database.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
> feat(user): implement multi get producers logic

- api/internal/store/database/database.go
- api/internal/store/database/product_type.go
- api/internal/store/database/product_type_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/product_type.go
- api/internal/store/service/product_type_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
> feat(store): implement multi get product types logic

- api/internal/store/input.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- api/internal/user/input.go
* 商品登録/更新時に生産者,仲介者が存在するかの検証を行うようにしました
> feat(store): add validation check for create and update product

- api/config/gateway/admin/rbac/policy.csv
- api/go.mod
- api/go.sum
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_test.go
- api/internal/gateway/admin/v1/request/product.go
- api/internal/gateway/admin/v1/service/product.go
- api/internal/gateway/admin/v1/service/product_test.go
- api/internal/store/input.go
- api/internal/store/service/product_test.go
> feat(gateway): implement create and update product api

- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_test.go
* 商品一覧取得APIでTODOコメントをしていた箇所の実装をしました
> feat(gateway): implement todo of ilst products api

- web/admin/nuxt.config.ts
- web/admin/src/store/index.ts
api の向き先をlocal環境からstg環境に向くように変更
> Fix: fixed api destination

- docs/swagger/admin/components/schemas/v1/administrator.request.yaml
- docs/swagger/admin/components/schemas/v1/administrator.response.yaml
- docs/swagger/admin/components/schemas/v1/category.response.yaml
- docs/swagger/admin/components/schemas/v1/producer.request.yaml
- docs/swagger/admin/components/schemas/v1/producer.response.yaml
- docs/swagger/admin/components/schemas/v1/product_type.response.yaml
- web/admin/src/types/api/api.ts
* API仕様書から生成するAPI Clientの方指定周りについて、Array型の中身がnulableになっていたため修正しました
> fix(docs): fix required flag

- api/internal/store/input.go
- docs/swagger/admin/components/schemas/v1/administrator.request.yaml
- docs/swagger/admin/components/schemas/v1/auth.request.yaml
- docs/swagger/admin/components/schemas/v1/category.request.yaml
- docs/swagger/admin/components/schemas/v1/producer.request.yaml
- docs/swagger/admin/components/schemas/v1/product.request.yaml
- docs/swagger/admin/components/schemas/v1/product_type.request.yaml
- docs/swagger/admin/components/schemas/v1/upload.request.yaml
- docs/swagger/user/components/schemas/v1/auth.request.yaml
- web/admin/src/types/api/api.ts
- web/user/src/types/api/api.ts
クライアント実装時にバリデーション設定がわかりやすいように、API仕様書のリクエスト値にバリデーション設定を記載しました。
> feat(docs): add description of request validation

- api/internal/messenger/entity/contact.go
- api/internal/messenger/entity/contact_test.go
- infra/mysql/schema/2022070601-messengers-create-contacts.sql
> feat(messenger): define contact entity

- docs/swagger/admin/components/schemas/v1/contact.request.yaml
- docs/swagger/admin/components/schemas/v1/contact.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/contacts/_contactId/index.yaml
- docs/swagger/admin/paths/v1/contacts/index.yaml
- docs/swagger/user/components/schemas/v1/contact.request.yaml
- docs/swagger/user/openapi.yaml
- docs/swagger/user/paths/v1/contacts/index.yaml
- web/admin/src/types/api/api.ts
- web/user/src/types/api/api.ts
> feat(docs): define contact api types

- docs/swagger/admin/components/schemas/v1/contact.request.yaml
- docs/swagger/admin/components/schemas/v1/contact.response.yaml
- web/admin/src/types/api/api.ts
API仕様書でtypoしていた箇所があったため修正しました。
この修正でtypes/api.tsが原因のビルドエラーは直るはずです🙏
> fix(docs): fix typo in contact response

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/admin/v1/handler/contact.go
- api/internal/gateway/admin/v1/handler/contact_test.go
- api/internal/gateway/admin/v1/request/contact.go
- api/internal/gateway/admin/v1/response/contact.go
- api/internal/gateway/admin/v1/service/contact.go
- api/internal/gateway/admin/v1/service/contact_test.go
> feat(gateway): implement contact api for admin

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/contact_test.go
- api/internal/messenger/database/database.go
- api/internal/messenger/service/contact.go
- api/internal/messenger/service/contact_test.go
- api/internal/messenger/service/service.go
- api/internal/messenger/service/service_test.go
- api/mock/messenger/database/database.go
> feat(messenger): implement contact logic

- docs/swagger/admin/components/schemas/v1/contact.response.yaml
- web/admin/src/types/api/api.ts
> fix: typeの修正

- .github/workflows/ci-docs-for-all.yaml
> feat(workflow): update workflow for docs

- web/admin/src/pages/producers/add.vue
- web/admin/src/pages/signin.vue
- web/admin/src/store/producer.ts
- 生産者を登録できるようにした。
サムネイルや住所、バリデーションなどはこれから
> feat: サインインの部分もvalidationを追加

- web/admin/src/pages/producers/index.vue
> feat: 生産者一覧の実装

- api/internal/messenger/entity/payload.go
- api/internal/messenger/entity/received_queue_test.go
- api/internal/messenger/entity/url.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact.go
- api/internal/messenger/service/contact_test.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/messenger/worker/mailer_test.go
- api/mock/messenger/service.go
> feat(messenger): implement notify received contact

- web/admin/src/components/organisms/TheCategoryList.vue
PRが荒れそうだったので、レビュー内容一度これでマージします。
> Refactor: refactor code

- api/Makefile
- api/internal/gateway/admin/v1/handler/category.go
- api/internal/gateway/admin/v1/handler/category_test.go
- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_test.go
- api/internal/gateway/admin/v1/handler/product_type.go
- api/internal/gateway/admin/v1/handler/product_type_test.go
- api/internal/gateway/admin/v1/response/category.go
- api/internal/gateway/admin/v1/response/product.go
- api/internal/gateway/admin/v1/response/product_type.go
- api/internal/store/database/category.go
- api/internal/store/database/category_test.go
- api/internal/store/database/database.go
- api/internal/store/database/product.go
- api/internal/store/database/product_test.go
- api/internal/store/database/product_type.go
- api/internal/store/database/product_type_test.go
- api/internal/store/service.go
- api/internal/store/service/category.go
- api/internal/store/service/category_test.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- api/internal/store/service/product_type.go
- api/internal/store/service/product_type_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- docs/swagger/admin/components/schemas/v1/category.response.yaml
- docs/swagger/admin/components/schemas/v1/product.response.yaml
- docs/swagger/admin/components/schemas/v1/product_type.response.yaml
- web/admin/src/types/api/api.ts
一覧取得APIにて、データの合計数を返すのを忘れていたため修正しました。まずはstore関連です。
> fix(store): fix list api response

- web/admin/src/layouts/default.vue
- web/admin/src/store/common.ts
- web/admin/src/store/producer.ts
- ユーザーへのフィードバックメッセージを表示するための状態管理を実施するストアを実装
- 生産者登録成功時にメッセージを出すように改善
> feat: 生産者登録成功時にメッセージを出すように改善

- web/admin/src/components/molecules/TheAddressForm.vue
- web/admin/src/lib/externals/index.ts
- web/admin/src/lib/externals/zipCloud.ts
- web/admin/src/pages/producers/add.vue
- 住所入力フォームのコンポーネント化
- 郵便番号から住所を検索する関数の実装
- 住所入力支援機能の実装
> feat: 住所入力支援機能の実装

- api/internal/gateway/user/v1/handler/contact.go
Reverts and-period/furumaru#180
> Revert "debug"

- api/Makefile
- api/internal/store/database/database.go
- api/internal/store/database/shipping.go
- api/internal/store/database/shipping_test.go
- api/internal/store/entity/shipping.go
- api/internal/store/entity/shipping_test.go
- api/internal/store/input.go
- api/internal/store/service/service_test.go
- api/internal/store/service/shipping.go
- api/internal/store/service/shipping_test.go
- api/mock/store/database/database.go
- infra/mysql/schema/2022071601-stores-rename-shipping.sql
> feat(store): implement shipping method

- docs/swagger/admin/components/schemas/v1/shipping.request.yaml
- web/admin/src/types/api/api.ts
> feat(docs): define shipping api types

- web/admin/src/components/organisms/TheProducerCreateForm.vue
- web/admin/src/lib/hooks/index.ts
- web/admin/src/lib/hooks/useSearchAddress.ts
- web/admin/src/pages/producers/add.vue
- web/admin/src/types/props/forms/files.ts
- web/admin/src/types/props/forms/index.ts
- web/admin/src/types/props/index.ts
> refactor: 生産者登録の部分を整理

- web/admin/src/middleware/auth.ts
- web/admin/src/pages/signin.vue
- web/admin/src/store/auth.ts
- #182 の対応
認証画面にリダイレクトした場合、認証後はリダイレクト前のパスに飛ばすようにした。
> feat: #182の対応

- api/internal/gateway/admin/v1/handler/shipping.go
- api/internal/gateway/admin/v1/handler/shipping_test.go
- api/internal/gateway/admin/v1/service/shipping.go
- api/internal/gateway/admin/v1/service/shipping_test.go
- api/internal/store/codes/prefecture.go
- api/internal/store/codes/prefecture_test.go
> feat(gateway): implement shipping api

- .github/workflows/cd-messenger-scheduler-for-main.yaml
- api/internal/messenger/cmd/scheduler/exec.go
通知スケジュール管理ジョブの自動デプロイ設定を追加しました。
> feat(workflow): setup messenger scheduler deploy

- api/go.mod
- api/go.sum
- api/internal/gateway/cmd/admin/config.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/cmd/user/config.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/router.go
NewRelicでメトリクスを取得できるように設定しました。
> feat(gateway): setup new relic monitoring

- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/user/registry.go
アーリーリターンする必要がある箇所でできていなかったため、修正しました
> fix(gateway): add early return

- api/go.mod
- api/go.sum
- api/internal/gateway/cmd/admin/config.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/user/config.go
- api/internal/gateway/cmd/user/registry.go
- docker-compose.yaml
configのlabel部分でtypoしていた関係でnew relicのクライアントが生成されていなかったため修正しました。
> fix(gateway): fix typo in config

- api/internal/messenger/database/message_template.go
- api/internal/messenger/database/message_template_test.go
- api/internal/messenger/entity/message_config.go
- api/internal/messenger/entity/message_config_test.go
- api/internal/messenger/entity/message_template.go
- api/internal/messenger/entity/message_template_test.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/messenger/worker/messenger.go
- api/internal/messenger/worker/messenger_test.go
- api/internal/messenger/worker/worker_test.go
- infra/mysql/schema/2022072103-messengers-alter-column-messages.sql
メッセージ作成用のテンプレートについて、件名もテンプレート化しました
> fix(messenger): fix message template

- api/internal/messenger/database/database.go
- api/internal/messenger/database/message.go
- api/internal/messenger/database/message_test.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/message.go
- api/internal/messenger/service/message_test.go
- api/internal/messenger/service/notification.go
- api/mock/messenger/database/database.go
- api/mock/messenger/service.go
> feat(messenger): implement get message method

- api/internal/messenger/database/message.go
- api/internal/messenger/database/message_test.go
- api/internal/messenger/entity/message.go
- api/internal/messenger/entity/message_test.go
- api/internal/messenger/input.go
- api/internal/messenger/service/message.go
- api/internal/messenger/service/message_test.go
現状のメッセージ取得ロジックだと、他人のメッセージもみれてしまう状態となってしまっていたため修正しました。
また、メッセージ一覧取得時は受信日時の降順になっていた方がいいかと思うため、合わせて修正しました。
> fix(messenger): fix get message logic

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/message.go
- api/internal/gateway/admin/v1/handler/message_test.go
- api/internal/gateway/admin/v1/response/message.go
- api/internal/gateway/admin/v1/service/message.go
- api/internal/gateway/admin/v1/service/message_test.go
- api/internal/messenger/input.go
- docs/swagger/admin/components/schemas/v1/message.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/messages/_messageId/index.yaml
- docs/swagger/admin/paths/v1/messages/index.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): implement get message api

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- api/internal/gateway/admin/v1/request/producer.go
- docs/swagger/admin/components/schemas/v1/producer.request.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/index.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/password.yaml
- web/admin/src/types/api/api.ts
フロントエンドが生産者の更新画面の実装をすすめられるように、まずはAPI TypesとAPI Mocksの実装をしました。
> feat(gateway): define update producer api

- api/config/messenger/mailer/dev.yaml
- api/config/messenger/mailer/stg.yaml
- api/internal/messenger/entity/mail_config.go
- api/internal/messenger/entity/payload.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/user/database/database.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/administrator.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/mock/messenger/service.go
- api/mock/pkg/cognito/client.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- api/pkg/cognito/admin.go
- api/pkg/cognito/client.go
> feat(user): implement update producer logic

- api/internal/user/database/coordinator.go
- api/internal/user/database/coordinator_test.go
- api/internal/user/database/database.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
> feat(user): implement update coordinator api

- api/hack/database-migrate/main.go
- api/internal/gateway/admin/v1/service/product.go
- api/internal/gateway/admin/v1/service/product_type.go
- api/internal/messenger/entity/notification.go
- api/internal/store/codes/prefecture.go
- api/internal/store/database/shipping_test.go
- api/internal/store/entity/shipping.go
- api/internal/store/entity/shipping_test.go
- api/internal/store/service/shipping_test.go
- api/pkg/set/v2/set.go
- api/pkg/set/v2/set_test.go
共通で利用するように切り出しているパッケージについて、重複排除処理等をするように作っているパッケージの中身をすべｔえ書き直したバージョンを作成しました。
> refactor(*): implement v2 set package

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/coordinator_test.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
> feat(gateway): implement update producer and coordinator api

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/administrator.go
- api/internal/gateway/admin/v1/handler/administrator_test.go
- api/internal/gateway/admin/v1/request/administrator.go
- api/internal/user/database/administrator.go
- api/internal/user/database/administrator_test.go
- api/internal/user/database/database.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/admin_auth_test.go
- api/internal/user/service/administrator.go
- api/internal/user/service/administrator_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- docs/swagger/admin/components/schemas/v1/administrator.request.yaml
- docs/swagger/admin/components/schemas/v1/coordinator.request.yaml
- docs/swagger/admin/components/schemas/v1/producer.request.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/administrators/_adminId/email.yaml
- docs/swagger/admin/paths/v1/administrators/_adminId/index.yaml
- docs/swagger/admin/paths/v1/administrators/_adminId/password.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): implement update admin api

- web/admin/src/store/category.ts
- web/admin/src/store/product-type.ts
> conflict refactor

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/coordinator_test.go
- api/internal/user/database/coordinator.go
- api/internal/user/database/coordinator_test.go
- api/internal/user/database/database.go
- api/internal/user/entity/coordinator.go
- api/internal/user/input.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- docs/swagger/admin/paths/v1/coordinators/index.yaml
- web/admin/src/types/api/api.ts
> feat(user): add sort query for list coordinators

- api/internal/gateway/admin/v1/handler/administrator.go
- api/internal/gateway/admin/v1/handler/administrator_test.go
- api/internal/user/database/administrator.go
- api/internal/user/database/administrator_test.go
- api/internal/user/database/database.go
- api/internal/user/entity/administrator.go
- api/internal/user/input.go
- api/internal/user/service/administrator.go
- api/internal/user/service/administrator_test.go
- docs/swagger/admin/paths/v1/administrators/index.yaml
- web/admin/src/types/api/api.ts
> feat(user): add sort query for list administrators

- web/admin/nuxt.config.ts
- web/admin/package.json
- web/admin/src/plugins/amplify.ts
- web/admin/yarn.lock
> feat(web/admin): setup amplify client

- web/admin/package.json
- web/admin/src/store/auth.ts
- web/admin/src/types/exception.ts
- web/admin/test/store/auth.spec.ts
- web/admin/yarn.lock
- `store/auth`のテストケースと追加。
- ひとまず愚直にテストケースを書いた。
> test: authのテストケースを追加

- web/user/nuxt.config.ts
- web/user/package.json
- web/user/src/plugins/amplify.ts
- web/user/yarn.lock
> feat(web/admin): changing pinpoint config

- web/admin/src/store/auth.ts
- web/admin/src/store/producer.ts
- web/admin/src/types/exception.ts
- web/admin/test/helpers/auth-helpter.ts
- web/admin/test/helpers/axios-helpter.ts
- web/admin/test/store/auth.spec.ts
- web/admin/test/store/producer.spec.ts
- テストのHelperを定義
- 例外クラスの再設計
- Producer Storeのテストを記述
> producer store のテストを追記

- docs/swagger/admin/components/schemas/v1/notification.request.yaml
- docs/swagger/admin/components/schemas/v1/notification.response.yaml
- web/admin/src/types/api/api.ts
- TargetTypeの値の意味が変わったのでswaggerを修正
- make swagger
一覧取得APIの実装
> docs: add notification description

- api/.golangci.yaml
- api/mock/pkg/stripe/client.go
- api/pkg/stripe/card.go
- api/pkg/stripe/client.go
- api/pkg/stripe/payment.go
Stripeクライアント周りの実装について、今後の決済追加時の修正が少なくなるよう修正しました。
> fix(stripe): fix stripe client

- api/internal/store/entity/promotion.go
- api/internal/store/entity/promotion_test.go
- infra/mysql/schema/2022080801-stores-create-promotions.sql
> feat(store): define promotion entity

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/handler/promotion_test.go
- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/gateway/admin/v1/handler/uploader_test.go
- api/internal/gateway/admin/v1/request/promotion.go
- api/internal/gateway/admin/v1/response/promotion.go
- api/internal/store/entity/promotion.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
- api/mock/store/service.go
- docs/swagger/admin/components/schemas/v1/promotion.request.yaml
- docs/swagger/admin/components/schemas/v1/promotion.response.yaml
- docs/swagger/admin/components/schemas/v1/upload.request.yaml
- docs/swagger/admin/components/schemas/v1/upload.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/promotions/_promotionId/index.yaml
- docs/swagger/admin/paths/v1/promotions/index.yaml
- docs/swagger/admin/paths/v1/upload/products/icon.yaml
- docs/swagger/admin/paths/v1/upload/products/image.yaml
- docs/swagger/admin/paths/v1/upload/products/video.yaml
- web/admin/src/types/api/api.ts
> feat(store): define promotion interface

- api/internal/store/database/database.go
- api/internal/store/database/promotion.go
- api/internal/store/database/promotion_test.go
- api/internal/store/service/service_test.go
- api/mock/store/database/database.go
> feat(store): implement promotion logic

- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/handler/promotion_test.go
- api/internal/gateway/admin/v1/service/promotion.go
- api/internal/gateway/admin/v1/service/promotion_test.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
> feat(store): implement create promotion api

- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/user/v1/handler/api_test.go
- api/internal/messenger/service/service_test.go
- api/internal/store/service/service_test.go
- api/internal/user/service/service_test.go
テスト時に使用するhandler, serviceの生成方法を変更しました
> refactor(*): refactor test handler and service

- api/internal/gateway/admin/v1/handler/auth.go
- api/internal/gateway/admin/v1/handler/auth_test.go
- api/internal/gateway/admin/v1/request/auth.go
- api/internal/user/database/admin_auth.go
- api/internal/user/database/admin_auth_test.go
- api/internal/user/database/database.go
- api/internal/user/entity/admin_auth.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/admin_auth.go
- api/internal/user/service/admin_auth_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- docs/swagger/admin/components/schemas/v1/auth.request.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/auth/device.yaml
- infra/mysql/schema/2022081301-users-add-column.sql
- web/admin/src/types/api/api.ts
Firebase Cloud Messaging経由でプッシュ通知を送るため、デバイス情報を登録するためのAPIを実装しました。
> feat(user): implement register admin device api

- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/handler/promotion_test.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
> feat(store): implement get promotion api

- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/handler/promotion_test.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
> feat(store): implement update promotion api

- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/handler/promotion_test.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
> feat(store): implement delete promotion api

- web/admin/src/store/auth.ts
- web/admin/src/store/category.ts
- web/admin/src/store/product-type.ts
- web/admin/src/types/exception.ts
> Fix: fixed errorhandling

- web/admin/src/components/organisms/TheCategoryList.vue
- web/admin/src/pages/categories/index.vue
- web/admin/src/store/category.ts
> Add: added category update

- .github/workflows/ci-backend-for-all.yaml
- .github/workflows/ci-web-admin-for-all.yaml
- .github/workflows/ci-web-user-for-all.yaml
- .github/workflows/pr-labeler.yaml
workflow関連のライブラリ更新
* close: https://github.com/and-period/furumaru/pull/259
* close: https://github.com/and-period/furumaru/pull/260
> chore(workflow): update dependencies

- docs/swagger/yarn.lock
docs関連のライブラリ更新
- close: #268 
- close: #267
> chore(docs): update dependencies

- web/user/yarn.lock
購入者用Web関連のライブラリ更新
* close: https://github.com/and-period/furumaru/pull/261
* close: https://github.com/and-period/furumaru/pull/263
* close: https://github.com/and-period/furumaru/pull/264
* close: https://github.com/and-period/furumaru/pull/269
* close: https://github.com/and-period/furumaru/pull/270
> chore(web/user): update dependencies

- web/admin/package.json
- web/admin/yarn.lock
管理者Web関連のライブラリ更新
* close: https://github.com/and-period/furumaru/pull/262
* close: https://github.com/and-period/furumaru/pull/265
* close: https://github.com/and-period/furumaru/pull/266
* close: https://github.com/and-period/furumaru/pull/271
* close: https://github.com/and-period/furumaru/pull/272
> chore(web/admin): update dependencies

- web/admin/package.json
- web/admin/src/pages/livestreaming.vue
- web/admin/yarn.lock
ライブ配信の検証をするために、映像配信確認用のモックを作成しました。
> feat(web/admin): add broadcast client mock

- web/admin/nuxt.config.ts
- web/admin/src/plugins/google-analytics.ts
- Firebase Analytics(Google Analytics)の導入
- SPAだとページ遷移のイベントが取れないのでrouter側で手動送信する
> Google Analyticsの最低限の設定

- web/admin/package.json
- web/admin/src/pages/livestreaming/index.vue
- web/admin/src/pages/livestreaming/view.vue
- web/admin/yarn.lock
配信周りの検証を進めるために、視聴画面のモックを作成しました。
> feat(web/admin): add live viewing client

- api/internal/gateway/user/v1/handler/auth.go
- api/internal/gateway/user/v1/handler/auth_test.go
- api/internal/user/database/admin_auth_test.go
- api/internal/user/service/user.go
- api/internal/user/service/user_test.go
初回登録時の設定用APIが何度もたたけるような状態になっていたため、１度しかたたけないよう修正しました。
> fix(user): fix initialize user logic

- web/user/yarn.lock
今週分のフロントエンド(user)ライブラリ更新
* close: https://github.com/and-period/furumaru/pull/284
* close: https://github.com/and-period/furumaru/pull/286
* close: https://github.com/and-period/furumaru/pull/289
* close: https://github.com/and-period/furumaru/pull/290
* close: https://github.com/and-period/furumaru/pull/292
> chore(*): update libraries for user web

- web/admin/package.json
- web/admin/yarn.lock
今週分のフロントエンド(admin)のライブラリ更新
* close: https://github.com/and-period/furumaru/pull/293
* close: https://github.com/and-period/furumaru/pull/294
* close: https://github.com/and-period/furumaru/pull/295
* close: https://github.com/and-period/furumaru/pull/296
* close: https://github.com/and-period/furumaru/pull/297
> chore(web/admin): update dependencies for admin web

- api/internal/messenger/database/database.go
- api/internal/messenger/database/notification.go
- api/internal/messenger/database/notification_test.go
- api/internal/messenger/input.go
- api/internal/messenger/service/notification.go
- api/internal/messenger/service/notification_test.go
- api/mock/messenger/database/database.go
- ListNotificationsのサービス層実装
- ListNotificationsのためにCountメソッド実装
- mock生成
- それぞれのテスト実装
- swagger実装
- gateway実装
> Feat(messenger): ListNotifications ServiceLayer

- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/cmd/user/router.go
アラート通知の詳細部分が文字化けしてしまうバグについて、Responseの書き込みが上手くできていないことに起因して文字化けしてしまっていたため、正しく書き込みができるよう修正しました。
> fix(api): fix error log format

- web/admin/src/pages/products/index.vue
- web/admin/src/store/product.ts
- web/admin/test/store/product.spec.ts
- 商品ページで一覧取得をAPIから行うようにした。
- 現状は関数だけ作った形。
以下は商品登録後に取り組む。
> 商品一覧取得のAPI連携

- docs/swagger/admin/components/schemas/v1/notification.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/notifications/index.yaml
- web/admin/src/types/api/api.ts
- ListNotificationsのswagger作成
- handler作成
> Docs: list notifications swagger

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/notification_test.go
- api/internal/gateway/admin/v1/response/admin.go
- api/internal/gateway/admin/v1/response/notification.go
- api/internal/gateway/admin/v1/service/administrator.go
- api/internal/gateway/admin/v1/service/administrator_test.go
- api/internal/gateway/admin/v1/service/notification.go
- api/internal/gateway/admin/v1/service/notification_test.go
- api/internal/messenger/service.go
- api/internal/user/service/admin.go
- api/internal/user/service/admin_test.go
- api/mock/messenger/service.go
- gateway層の実装
- mock追加
- administratorのMap()追加
- Delete
- Update
> Feat: ListNotifications Gateway

- web/admin/package.json
- web/admin/src/layouts/default.vue
- web/admin/src/pages/events.vue
- web/admin/src/pages/promotions/index.vue
- web/admin/src/store/promotion.ts
- web/admin/yarn.lock
> Add: added promotion ui

- api/internal/messenger/input.go
- api/internal/messenger/service/notification.go
- api/internal/messenger/service/notification_test.go
> feat: add DeleteNotification ServiceLayer

- api/go.mod
- api/go.sum
0825分のバックエンドライブラリ更新
- close: #312 
- close: #313 
- close: #314 
- close: #315
- close: #317
> Chore(*): update libraries for backend

- web/admin/yarn.lock
0825分のフロントエンド(admin)ライブラリ更新
- close: #310 
- close: #319 
- close: #321
- close: #323 
- close: #325
> Chore(*): Update libraries for admin web

- docs/swagger/yarn.lock
0825分のdocsライブラリ更新
- close: #311 
- close: #322
> Chore(*): Update for docs

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/notification_test.go
- api/internal/messenger/service.go
- api/mock/messenger/service.go
- DeleteNotification用の権限を追加
- serviceにDeleteを追加
- mock作成
- DeleteNotificationのhandler作成
> Feat(messenger): DeleteNotification gateway

- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/notifications/_notificationId/index.yaml
- web/admin/src/types/api/api.ts
> feat: add delete_notification swagger

- api/internal/gateway/admin/v1/request/product.go
商品関連リクエストのjsonタグ名が誤っている箇所を修正しました
> fix(gateway): fix json tag in product request'

- api/internal/store/entity/product.go
- api/internal/store/entity/product_test.go
- api/internal/store/entity/shipping.go
- api/internal/store/entity/shipping_test.go
JSON型でnullを入れるのを許容しているカラムについて、nullの時はエラーに倒さず空のSliceで埋めるよう修正しました。
> fix(store): fix fill from json input

- api/internal/messenger/database/database.go
- api/internal/messenger/database/notification.go
- api/internal/messenger/database/notification_test.go
- api/internal/messenger/entity/notification.go
- api/internal/messenger/entity/notification_test.go
- api/mock/messenger/database/database.go
- Marshalメソッドの実装
- UpdateNotificationのdatabase層の実装
- make mockgen
> Feat(messenger): UpdateNotification database layer

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/notification.go
- api/internal/messenger/service/notification_test.go
- api/mock/messenger/service.go
> Feat(messenger): UpdateNotification service layer

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/notification_test.go
- api/internal/gateway/admin/v1/request/notification.go
- Updateの権限追加
- Update用の型追加
- UpdateNotificationのgateway層実装
> Feat(messenger): Implement UpdateNotification gateway layer

- web/admin/src/components/organisms/ThePromotionForm.vue
- web/admin/src/components/templates/ThePromotionCreateFormPage.vue
- web/admin/src/pages/promotions/add.vue
- web/admin/src/pages/promotions/index.vue
セール情報登録の実装
やまちゃんが、時間指定のUIのCSSをきっと変えてくれる
> Add: added promotion create ui

- web/admin/nuxt.config.ts
- web/admin/src/assets/variables.scss
- Vuetifyのデフォルトの表示が英語で見栄えが悪いのでロケールの設定をした。
- `v-card`のelevationの設定がされている箇所とされてない箇所で違いが目立つのでsccs変数でまとめて設定した
> Vuetifyのlocaleの設定とscss変数を設定する

- web/admin/src/components/organisms/ThePromotionForm.vue
> Add: added promotion validation

- api/mock/pkg/ivs/client.go
- api/pkg/ivs/channel.go
- api/pkg/ivs/client.go
> pkg(IVS): Add GetChannel method

- web/admin/src/components/organisms/TheCategoryList.vue
- web/admin/src/components/organisms/TheProductTypeList.vue
- web/admin/src/lib/hooks/index.ts
- web/admin/src/lib/hooks/usePagination.ts
- web/admin/src/pages/categories/index.vue
- web/admin/src/pages/products/index.vue
- web/admin/src/store/category.ts
- web/admin/src/store/product-type.ts
- web/admin/src/store/product.ts
- ページネーション用のカスタムフックを作成
- 商品一覧の部分をサーバサイドページネーションで実装
- カテゴリ・品目の部分をサーバサイドページネーションで実装
- 品目編集機能の実装
> ページネーションの部分を修正

- api/mock/pkg/ivs/client.go
- api/pkg/ivs/channel.go
- api/pkg/ivs/client.go
> pkg(IVS) Add DeleteChannel method

- infra/mysql/schema/2022091001-stores-create-schedules.sql
- infra/mysql/schema/2022091002-stores-create-lives.sql
- schedulesテーブルの追加
- livesテーブルの追加
https://calmato.kibe.la/notes/727#:~:text=%E3%83%95%E3%83%AD%E3%83%BC-,%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E8%A8%AD%E8%A8%88,-sql
> Database(stores): create table schedules and lives

- docs/swagger/admin/components/schemas/v1/administrator.response.yaml
- docs/swagger/admin/components/schemas/v1/category.response.yaml
- docs/swagger/admin/components/schemas/v1/contact.response.yaml
- docs/swagger/admin/components/schemas/v1/coordinator.response.yaml
- docs/swagger/admin/components/schemas/v1/message.response.yaml
- docs/swagger/admin/components/schemas/v1/notification.response.yaml
- docs/swagger/admin/components/schemas/v1/producer.response.yaml
- docs/swagger/admin/components/schemas/v1/product.response.yaml
- docs/swagger/admin/components/schemas/v1/product_type.response.yaml
- docs/swagger/admin/components/schemas/v1/promotion.response.yaml
- docs/swagger/admin/components/schemas/v1/shipping.response.yaml
- web/admin/src/types/api/api.ts
- UpdatedAtの説明を修正
- make swagger
> Fix: change updatedAt description

- web/admin/src/assets/variables.scss
- web/admin/src/pages/settings.vue
- web/admin/src/store/auth.ts
- 設定画面から「サインアウト」を押したときにサインアウトするようにした
- 設定画面のリストのレイアウトの調整
> feat: サインアウト機能の実装

- web/admin/src/pages/producers/index.vue
- web/admin/src/store/producer.ts
- 生産者管理画面のページネーション機能をlimitとoffsetのサーバサイドページネーションで実装
> 生産者管理の部分にサーバページネーションを追加

- api/internal/store/entity/schdule_test.go
- api/internal/store/entity/schedule.go
- 配信の開催スケジュールentityを実装
- テスト実装
https://calmato.kibe.la/notes/727
> Feat(store): create live schedule entity

- web/admin/src/pages/notifications.vue
- web/admin/src/pages/notifications/index.vue
- web/admin/src/pages/promotions/index.vue
- web/admin/src/store/notification.ts
> Add: added notification list

- api/internal/store/entity/schdule_test.go
- api/internal/store/entity/schedule.go
> fix(store): typo ThumbnailURL

- api/internal/gateway/cmd/admin/config.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/cmd/user/config.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/router.go
- api/pkg/slack/client.go
* 連絡ツールをLINEからSlackへ移行するにあたり、アラート通知をSlackへ流すよう改修しました。
> feat(gateway): implement slack alert function

- api/hack/_once/replace-admin-tables/main.go
- api/internal/user/entity/admin.go
- api/internal/user/entity/admin_auth.go
- api/internal/user/entity/administrator.go
- api/internal/user/entity/coordinator.go
- api/internal/user/entity/producer.go
- infra/mysql/schema/2022092401-users-replace-admins.sql
* ユーザーDBの設計変更に伴う移行対応
* まずは管理者側の対応から進めています
> feat(user): replace admin tables

- web/admin/src/pages/customers.vue
- web/admin/src/pages/customers/edit/id.vue
- web/admin/src/pages/customers/index.vue
> 顧客一覧（ベタ打ち）

- web/admin/src/pages/products/index.vue
> fix: 商品登録のボタン色を変更

- api/internal/store/entity/live.go
- api/internal/store/entity/live_test.go
- Liveのentityを実装
https://calmato.kibe.la/notes/727
> feat(store): implement live entity

- web/admin/src/pages/notifications/index.vue
- web/admin/src/store/notification.ts
> Add: added notification delete

- api/internal/store/entity/order.go
- api/internal/store/entity/order_activity.go
- api/internal/store/entity/order_fulfillment.go
- api/internal/store/entity/order_item.go
- api/internal/store/entity/order_payment.go
- api/internal/store/entity/payment_card.go
- api/internal/store/entity/stripe_user.go
- infra/mysql/schema/2022100601-stores-create-payments.sql
- infra/mysql/schema/2022100701-stores-create-orders.sql
* 注文管理用のDDL, エンティティ定義を追加しました
* https://calmato.kibe.la/notes/734#%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E8%A8%AD%E8%A8%88
> feat(store): define order entity

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/notification_test.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/notification.go
- api/internal/messenger/service/notification_test.go
- api/mock/messenger/service.go
- docs/swagger/admin/components/schemas/v1/notification.request.yaml
- docs/swagger/admin/paths/v1/notifications/_notificationId/index.yaml
- web/admin/src/types/api/api.ts
- GetNotificationのservice層実装
- GetNotificationのgateway層実装
- swagger実装
> feat(messenger): added GetNotification

- api/internal/store/database/database.go
- api/internal/store/database/order.go
- api/internal/store/database/order_activity.go
- api/internal/store/database/order_activity_test.go
- api/internal/store/database/order_fulfillment.go
- api/internal/store/database/order_fulfillment_test.go
- api/internal/store/database/order_item.go
- api/internal/store/database/order_item_test.go
- api/internal/store/database/order_payment.go
- api/internal/store/database/order_payment_test.go
- api/internal/store/database/order_test.go
- api/internal/store/entity/order.go
- api/internal/store/entity/order_activity.go
- api/internal/store/entity/order_activity_test.go
- api/internal/store/entity/order_fulfillment.go
- api/internal/store/entity/order_fulfillment_test.go
- api/internal/store/entity/order_item.go
- api/internal/store/entity/order_item_test.go
- api/internal/store/entity/order_payment.go
- api/internal/store/entity/order_payment_test.go
- api/internal/store/entity/order_test.go
- api/internal/store/service/service_test.go
- api/mock/store/database/database.go
- infra/mysql/schema/2022101001-stores-alter-table.sql
> feat(store): implement database logic for order

- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/order.go
- api/internal/store/service/order_test.go
- api/mock/store/service.go
> feat(store): implement get order

- api/internal/gateway/admin/v1/response/order.go
- api/internal/gateway/admin/v1/response/user.go
- api/internal/gateway/admin/v1/service/order.go
- api/internal/gateway/admin/v1/service/order_fulfillment.go
- api/internal/gateway/admin/v1/service/order_fulfillment_test.go
- api/internal/gateway/admin/v1/service/order_item.go
- api/internal/gateway/admin/v1/service/order_item_test.go
- api/internal/gateway/admin/v1/service/order_payment.go
- api/internal/gateway/admin/v1/service/order_payment_test.go
- api/internal/gateway/admin/v1/service/order_refund.go
- api/internal/gateway/admin/v1/service/order_refund_test.go
- api/internal/gateway/admin/v1/service/order_test.go
- api/internal/gateway/admin/v1/service/user.go
- api/internal/gateway/admin/v1/service/user_test.go
- api/internal/store/entity/order.go
- api/internal/store/service/order_test.go
- api/internal/user/entity/user.go
- api/internal/user/entity/user_test.go
- api/pkg/jst/jst.go
* 管理者用APIでレスポンスとして返す注文情報関連エンティティを実装しました
> feat(gateway): implement order entity

- web/admin/src/components/organisms/ThePromotionForm.vue
- web/admin/src/components/templates/ThePromotionCreateFormPage.vue
- web/admin/src/pages/promotions/add.vue
- web/admin/src/store/promotion.ts
> Add: added promotion create

- docs/swagger/admin/components/schemas/v1/schedule.request.yaml
- docs/swagger/admin/components/schemas/v1/schedule.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/schedules/index.yaml
- web/admin/src/types/api/api.ts
- createSchedule用のswagger作成
https://calmato.kibe.la/notes/727#%E9%96%8B%E5%82%AC%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E7%99%BB%E9%8C%B2
> docs(store): added createSchedule swagger

- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- api/internal/gateway/admin/v1/service/auth.go
- api/internal/gateway/admin/v1/service/auth_test.go
- api/internal/user/database/database.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/input.go
- api/internal/user/service/producer.go
> fix(gateway): filter access for producer api

- api/internal/user/input.go
* CoordinatorIDを基に生産者一覧を取得できる様にしました
> feat(user): list producers with coordinator id

- api/.golangci.yaml
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_test.go
- api/internal/gateway/admin/v1/service/producer.go
- api/internal/store/database/database.go
- api/internal/store/database/product_test.go
- api/internal/store/input.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- docs/swagger/admin/paths/v1/producers/_producerId/email.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/index.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/password.yaml
- docs/swagger/admin/paths/v1/products/_productId/index.yaml
- docs/swagger/admin/paths/v1/products/index.yaml
- web/admin/src/types/api/api.ts
* 商品関連APIについて、コーディネータごとに閲覧できるデータの制限ができるようにしました
> feat(gateway): filter products api

- api/internal/store/database/database.go
- api/internal/store/database/order.go
- api/internal/store/database/order_test.go
- api/internal/store/input.go
- api/internal/store/service/order.go
- api/internal/store/service/order_test.go
* 注文履歴をCoordinatorIDで絞り込みできるようにしました
> feat(store): add field to list orders api

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/order.go
- api/internal/gateway/admin/v1/handler/order_test.go
- api/internal/gateway/admin/v1/response/order.go
- api/internal/gateway/admin/v1/service/order.go
- api/internal/gateway/admin/v1/service/order_test.go
- api/internal/gateway/admin/v1/service/product.go
- api/internal/gateway/admin/v1/service/product_test.go
- api/internal/store/service.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- api/mock/store/service.go
- docs/swagger/admin/components/schemas/v1/order.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/index.yaml
- docs/swagger/admin/paths/v1/orders/index.yaml
- web/admin/src/types/api/api.ts
* 注文一覧,詳細取得APIの実装 (ソート機能のみ未実装)
> feat(gateway): implement get orders api

- web/admin/src/assets/variables.scss
- web/admin/src/lib/formatter/day.ts
- web/admin/src/lib/formatter/index.ts
- web/admin/src/lib/formatter/money.ts
- web/admin/src/pages/settings.vue
- web/admin/src/pages/shippings/index.vue
- web/admin/src/store/shippings.ts
> feat: 配送情報一覧ページを実装

- web/admin/src/pages/notifications/index.vue
- web/admin/src/pages/promotions/index.vue
- web/admin/src/store/promotion.ts
> Add: added promotion delete

- api/internal/user/database/database.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/producer.go
- api/mock/user/database/database.go
- api/mock/user/service.go
> feat(user): implement-related producer

- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- api/internal/user/database/database.go
- api/internal/user/database/producer_test.go
- api/internal/user/input.go
- docs/swagger/admin/paths/v1/producers/index.yaml
- web/admin/src/types/api/api.ts
* コーディネータに関連付けされていない生産者一覧を取得できるように
> feat(gateway): add filter to list producers api

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- api/internal/gateway/admin/v1/request/producer.go
- docs/swagger/admin/components/schemas/v1/producer.request.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/relationship.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): implement related producer api

- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
* 生産者関連付け周りのエラーハンドリング追加
* 生産者関連付け周りのテストコード追加
> fix(user): fix related producer

- api/internal/gateway/admin/v1/handler/order.go
- api/internal/gateway/admin/v1/handler/order_test.go
- api/internal/store/database/database.go
- api/internal/store/database/order_test.go
- api/internal/store/entity/order.go
- api/internal/store/input.go
- docs/swagger/admin/paths/v1/orders/index.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): add order by query for list orders

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/order.go
> feat(gateway): changing filter access

- web/admin/src/pages/shippings/index.vue
> 配送情報の表示を修正

- Makefile
- api/Makefile
- docs/swagger/Makefile
* Makefileのhelpコマンド作ったら便利そうなので作成しました
> chore(*): add command description

- docs/swagger/package.json
- docs/swagger/yarn.lock
今週分のAPI仕様書ライブラリ更新対応
* close: https://github.com/and-period/furumaru/pull/372
* close: https://github.com/and-period/furumaru/pull/395
* close: https://github.com/and-period/furumaru/pull/396
* close: https://github.com/and-period/furumaru/pull/397
* close: https://github.com/and-period/furumaru/pull/445
> chore(docs): update dependencies 

- web/admin/src/pages/shippings/index.vue
> style: lintの警告に対応

- web/admin/src/layouts/default.vue
- web/admin/src/pages/contacts/index.vue
- web/admin/src/pages/coordinators/add.vue
- web/admin/src/pages/coordinators/edit/_id.vue
- web/admin/src/pages/coordinators/index.vue
- web/admin/src/pages/customers/index.vue
- web/admin/src/store/coordinator.ts
> ’コーディネータ管理の大枠’

- api/internal/store/database/database.go
- api/internal/store/database/order.go
- api/internal/store/database/order_test.go
- api/internal/store/entity/order.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/order.go
- api/internal/store/service/order_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
管理画面の顧客管理ページにて注文履歴を集計した結果を出す必要があるため、注文履歴を集計した結果を返すMethodを作成しました。
> feat(store): implement aggregate orders

- api/internal/user/service/administrator.go
- api/internal/user/service/administrator_test.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
> refactor(user): refactor update admin service

- api/internal/gateway/admin/v1/handler/product.go
* gatewayから商品一覧(ID指定)取得処理をプライベートメソッドとして切り出しました
> feat(gateway): split get products method

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/schedule.go
- api/internal/gateway/admin/v1/handler/schedule_test.go
- api/internal/gateway/admin/v1/request/schedule.go
- api/internal/gateway/admin/v1/response/live.go
- api/internal/gateway/admin/v1/response/schedule.go
- api/internal/gateway/admin/v1/service/live.go
- api/internal/gateway/admin/v1/service/live_test.go
- api/internal/gateway/admin/v1/service/producer.go
- api/internal/gateway/admin/v1/service/producer_test.go
- api/internal/gateway/admin/v1/service/schedule.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- 権限を追加
- producerのNameメソッドを追加
- request,responseを追加
- gateway層を実装
productsが詰められなくてテスト落ちる
```
--- Expected
+++ Actual
@@ -11,39 +11,3 @@
(string) (len=12) "producerName": (string) (len=12) "&. 管理者",
-   (string) (len=8) "products": ([]interface {}) (len=1) {
-    (map[string]interface {}) (len=25) {
-     (string) (len=10) "box100Rate": (float64) 30,
-     (string) (len=9) "box60Rate": (float64) 50,
-     (string) (len=9) "box80Rate": (float64) 40,
-     (string) (len=10) "categoryId": (string) (len=11) "category-id",
-     (string) (len=12) "categoryName": (string) (len=6) "野菜",
-     (string) (len=9) "createdAt": (float64) 1.6409628e+09,
-     (string) (len=12) "deliveryType": (float64) 1,
-     (string) (len=11) "description": (string) (len=48) "新鮮なじゃがいもをお届けします。",
-     (string) …
```
> Feat(store): implement CreateSchedule gateway layer

- web/admin/src/constants/prefectures.ts
- web/admin/src/lib/prefectures/helper.ts
- web/admin/src/lib/prefectures/index.ts
- web/admin/src/pages/shippings/add.vue
- web/admin/src/pages/shippings/index.vue
- web/admin/src/store/shippings.ts
- web/admin/src/types/exception.ts
> 配送情報新規登録画面の実装

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/user.go
- api/internal/gateway/admin/v1/handler/user_test.go
- api/internal/gateway/admin/v1/response/user.go
- api/internal/gateway/admin/v1/service/user.go
- api/internal/gateway/admin/v1/service/user_test.go
- api/internal/store/entity/order.go
- api/internal/store/entity/order_test.go
- docs/swagger/admin/components/schemas/v1/user.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/users/index.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): implement list users api

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/user.go
- api/internal/gateway/admin/v1/handler/user_test.go
- api/internal/gateway/admin/v1/response/user.go
- api/internal/gateway/admin/v1/service/user.go
- docs/swagger/admin/components/schemas/v1/user.response.yaml
> feat(gateway): implement get user api

- api/internal/user/database/database.go
- api/internal/user/database/member.go
- api/internal/user/database/member_test.go
- api/internal/user/entity/user.go
- api/internal/user/entity/user_test.go
- api/internal/user/service/user.go
- api/internal/user/service/user_test.go
- api/mock/user/database/database.go
- infra/mysql/schema/2022102701-users-alter-column-users.sql
> refactor(user): refactor create user logic

- api/internal/user/database/admin.go
- api/internal/user/database/administrator.go
- api/internal/user/database/administrator_test.go
- api/internal/user/database/coordinator.go
- api/internal/user/database/coordinator_test.go
- api/internal/user/database/database.go
- api/internal/user/database/member_test.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/entity/admin.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/administrator.go
- api/internal/user/service/administrator_test.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- infra/mysql/schema/2022102702-users-alter-column-admins.sql
> feat(user): implement delete admin

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/administrator.go
- api/internal/gateway/admin/v1/handler/administrator_test.go
- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/coordinator_test.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- docs/swagger/admin/paths/v1/administrators/_adminId/index.yaml
- docs/swagger/admin/paths/v1/coordinators/_coordinatorId/index.yaml
- docs/swagger/admin/paths/v1/producers/_producerId/index.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): implement delete admin api

- web/admin/src/pages/coordinators/add.vue
- web/admin/src/pages/coordinators/edit/_id.vue
- web/admin/src/pages/coordinators/index.vue
- web/admin/src/store/coordinator.ts
> 画像アップロード機能

- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/coordinator_test.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/gateway/admin/v1/handler/producer_test.go
- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/gateway/admin/v1/handler/uploader_test.go
- api/internal/gateway/cmd/admin/config.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/store/service/shipping_test.go
* Gateway側でのファイルアップロードロジックをMedia Moduleへ寄せるための処理になります
> feat(gateway): setup media service

- web/admin/src/components/organisms/TheProductTypeList.vue
- web/admin/src/pages/categories/index.vue
- web/admin/src/store/product-type.ts
> Add: added product type icon

- web/admin/src/components/organisms/TheShippingForm.vue
- web/admin/src/pages/shippings/add.vue
- web/admin/src/pages/shippings/edit/_id.vue
- web/admin/src/pages/shippings/index.vue
- web/admin/src/store/shippings.ts
- 配送情報編集ページの実装
- フォームのコンポーネントを作成
- 配送情報新規登録のページをコンポーネントに置き換え
> 配送情報編集機能の実装

- docs/swagger/admin/components/schemas/v1/live.response.yaml
- docs/swagger/admin/components/schemas/v1/schedule.request.yaml
- docs/swagger/admin/components/schemas/v1/schedule.response.yaml
- docs/swagger/admin/openapi.yaml
- web/admin/src/types/api/api.ts
- scheduleに配信設定周りを追加
- scheduleのresponseにlivesを追加
- liveのresponseを追加
> Docs(store):fix create_schedule swagger

- web/admin/src/layouts/default.vue
- web/admin/src/pages/settings.vue
> いらないところをマスクしたりした

- .github/workflows/ci-docs-for-all.yaml
- .github/workflows/ci-web-admin-for-all.yaml
- .github/workflows/ci-web-user-for-all.yaml
* GitHub Actionsの書き方で deprecated になっている箇所があったため修正しました
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore(github): fixed github output

- api/internal/gateway/cmd/admin/config.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/media/entity/payload.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/resize.go
- api/internal/media/service/resize_test.go
- api/internal/media/service/service.go
- api/internal/media/service/service_test.go
- api/mock/media/service.go
- infra/terraform/env/stg/05-sqs/02-media.tf
> feat(media): implement resize method

- api/internal/gateway/cmd/admin/registry.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- api/internal/user/service/service.go
- api/internal/user/service/service_test.go
> feat(user): implement resize coordinator media request

- web/admin/src/pages/producers/edit/_id.vue
- web/admin/src/store/producer.ts
- web/admin/src/types/api/api.ts
> 生産者更新機能を実装

- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/notification_test.go
- api/internal/gateway/admin/v1/handler/product_type.go
- api/internal/gateway/admin/v1/handler/product_type_test.go
- api/internal/gateway/admin/v1/handler/user.go
- api/internal/gateway/admin/v1/handler/user_test.go
- api/pkg/set/v2/set.go
- api/pkg/set/v2/set_test.go
set パッケージ内でsliceを生成する処理について、ゼロ値は含まれないように修正
(プラスでリスト取得周りのAPI修正しています)
> fix(set): fix slice method

- api/mock/pkg/ivs/client.go
- api/pkg/ivs/client.go
- api/pkg/ivs/stream.go
- ivsのpkgにgetStreamメソッドを追加しました。下記二つを主に使用予定
- 視聴者数(ViewerCount)
- 配信を再生するためのURL(PlaybackUrl)
https://calmato.kibe.la/notes/727#%E8%A6%96%E8%81%B4%E8%80%85%E6%95%B0%E3%82%92%E5%8F%96%E5%BE%97
> feat: added getStream to ivs pkg

- api/internal/user/service/producer.go
未関連生産者のみ取得するためのフラグをDB層へ渡せていなかったため修正
> fix(user): fix list producers

- infra/terraform/env/shared/01-ecr/05-media-resizer.tf
> feat(terraform): create sqs resource

- api/internal/media/entity/regulation.go
- api/internal/media/service/generate.go
* 一時ストレージへのファイルアップロードがうまくできていなかったため修正しました。
> fix(media): fix upload tmp storage logic

- api/internal/media/resizer/coordinator.go
- api/internal/media/resizer/coordinator_test.go
- api/internal/media/resizer/resizer.go
- api/internal/media/resizer/resizer_test.go
* コーディネータのリサイズ後の情報をDBヘ保管するための処理を実装しました。
> feat(media): implement resize coordinator

- api/internal/user/database/admin.go
- api/internal/user/database/administrator.go
- api/internal/user/database/coordinator.go
- api/internal/user/database/customer.go
- api/internal/user/database/guest.go
- api/internal/user/database/member.go
- api/internal/user/database/producer.go
- api/internal/user/database/user.go
- api/pkg/database/client.go
> refactor(user): refactor user database query

- api/internal/store/database/category.go
- api/internal/store/database/order.go
- api/internal/store/database/order_activity.go
- api/internal/store/database/order_fulfillment.go
- api/internal/store/database/order_item.go
- api/internal/store/database/order_payment.go
- api/internal/store/database/product.go
- api/internal/store/database/product_type.go
- api/internal/store/database/promotion.go
- api/internal/store/database/shipping.go
> refactor(store): refactor store database query

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/notification.go
- api/internal/user/database/administrator.go
- api/internal/user/database/coordinator.go
- api/internal/user/database/producer.go
- api/internal/user/database/user.go
> refactor(api): refactor count query

- api/internal/store/database/live.go
- api/internal/store/database/live_product.go
> refactor(store): refactor select query

- api/internal/store/database/database.go
- api/internal/store/database/product.go
- api/internal/store/database/product_test.go
- api/internal/store/entity/product.go
- api/internal/store/entity/product_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
> feat(store): implement update product media

- api/internal/user/database/database.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/entity/coordinator_test.go
- api/internal/user/entity/producer.go
- api/internal/user/entity/producer_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- infra/mysql/schema/2022110901-users-alter-column.sql
> feat(user): implement update producer images

- api/internal/media/cmd/resizer/registry.go
- api/internal/media/resizer/producer.go
- api/internal/media/resizer/producer_test.go
- api/internal/media/resizer/product.go
- api/internal/media/resizer/product_test.go
- api/internal/media/resizer/resizer.go
- api/internal/media/resizer/resizer_test.go
> feat(media): implement resize product and producer

- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
> feat(user): implement resize producer media request

- api/internal/gateway/cmd/admin/registry.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
- api/internal/store/service/service.go
- api/internal/store/service/service_test.go
> feat(store): add upload product media logic

- api/internal/store/database/database.go
- api/internal/store/database/product_type.go
- api/internal/store/database/product_type_test.go
- api/internal/store/entity/product_type.go
- api/internal/store/entity/product_type_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/product_type.go
- api/internal/store/service/product_type_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- infra/mysql/schema/2022111401-stores-alter-column.sql
> feat(store): implement update product type icons

- api/internal/store/database/product.go
- api/internal/store/database/shipping.go
> fix(store): fix get product logic

- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/admin/v1/handler/product_type.go
- api/internal/gateway/admin/v1/handler/product_type_test.go
- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/gateway/admin/v1/handler/uploader_test.go
- api/internal/gateway/admin/v1/response/product_type.go
- api/internal/gateway/admin/v1/service/product_type.go
- api/internal/gateway/admin/v1/service/product_type_test.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/media/resizer/product_type.go
- api/internal/media/resizer/product_type_test.go
- api/internal/media/resizer/resizer.go
- api/internal/media/resizer/resizer_test.go
- api/internal/store/service/product_type.go
- api/internal/store/service/product_type_test.go
- docs/swagger/admin/components/schemas/v1/product_type.response.yaml
- web/admin/src/types/api/api.ts
> feat(*): implement resize product type icons

- web/admin/nuxt.config.ts
- web/admin/src/plugins/api-error-handler.ts
- web/admin/src/plugins/auth.ts
- web/admin/src/store/coordinator.ts
- web/admin/src/types/exception.ts
- web/admin/src/types/plugins/index.d.ts
- コーディーネーター削除の機能を作るつもりが気づいたら、共通のエラーハンドリング基盤を作っていた（）
> feat: piniaのカスタムプラグインで共通のエラーハンドラーを実装

- api/pkg/postalcode/client.go
- api/pkg/postalcode/search.go
ZipCloud側からのレスポンスが text/plain で返ってくるためcontent-typeを見る処理をやめました
> fix(postalcode): fix response content type

- api/internal/store/entity/address.go
- api/internal/store/entity/address_test.go
- infra/mysql/schema/2022111701-stores-create-addresses.sql
> feat(store): define address entity

- api/internal/store/database/category.go
- api/internal/store/database/product_type.go
> refactor(store): remove category fields

- api/internal/gateway/admin/v1/handler/shipping.go
> refactor(gateway): get shipping api

- web/admin/src/store/auth.ts
- Cookieに値を入れる際に secure 属性をつけた
> Cookieの設定を更新

- api/internal/gateway/admin/v1/handler/order.go
- api/internal/gateway/admin/v1/handler/order_test.go
- api/internal/store/database/address.go
- api/internal/store/database/address_test.go
- api/internal/store/database/database.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/address.go
- api/internal/store/service/address_test.go
- api/internal/store/service/service_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
> feat(store): implement multi get addresses

- README.md
- web/admin/src/components/organisms/TheCoordinatorCreateForm.vue
- web/admin/src/components/organisms/TheCoordinatorEditForm.vue
- web/admin/src/components/organisms/TheNotificationForm.vue
- web/admin/src/pages/coordinators/add.vue
- web/admin/src/pages/coordinators/edit/_id.vue
- web/admin/src/pages/notifications/index.vue
- コーディネータ登録と編集の部分のフォームをコンポーネントに切り出した
- 型定義で色々と誤りがあったので修正した。
> refactor: コーディネータ登録と編集の部分のフォームをリファクタリング

- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/notification_test.go
* 管理画面のデバッグをしていて、お知らせ画面はデフォルトで掲載開始日時の降順にしても良いかなと思ったので修正
> feat(gateway): add default order by notifications

- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/handler/promotion_test.go
* 管理画面のデバッグをしていて、セール画面もデフォルトで開始日時の降順にしても良いかなと思ったので修正
> feat(gateway): add default order by promotions

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/message.go
- api/internal/messenger/database/notification.go
- api/internal/store/database/category.go
- api/internal/store/database/order.go
- api/internal/store/database/product.go
- api/internal/store/database/product_type.go
- api/internal/store/database/promotion.go
- api/internal/store/database/shipping.go
- api/internal/user/database/administrator.go
- api/internal/user/database/coordinator.go
- api/internal/user/database/producer.go
- api/internal/user/database/user.go
- api/pkg/database/client.go
* COUNTクエリについて、テーブル名指定ではなくモデル指定にすることで `deleted_at` の有無によってWHERE句へ条件を追加する処理をたしました。
> fix(database): fix count query

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/message.go
- api/internal/messenger/database/notification.go
- api/internal/messenger/database/received_queue.go
- api/internal/messenger/database/schedule.go
- api/internal/store/database/category.go
- api/internal/store/database/product.go
- api/internal/store/database/product_type.go
- api/internal/store/database/promotion.go
- api/internal/store/database/schedule.go
- api/internal/store/database/shipping.go
- api/internal/user/database/admin.go
- api/internal/user/database/administrator.go
- api/internal/user/database/coordinator.go
- api/internal/user/database/member.go
- api/internal/user/database/producer.go
- api/internal/user/database/user.go
- api/pkg/database/client.go
- api/pkg/database/client_test.go
* トランザクションを作成するメソッドについて、返り値の1つ目が不要そう(使ったことがない)ため削除しました
> refactor(database): refactor transaction method

- web/admin/src/pages/coordinators/index.vue
- web/admin/src/store/coordinator.ts
- コーディネータ削除機能の実装
- エラー時にメッセージを出すようにした
- 成功時にポップアップを出すようにした
> コーディネータ削除機能の実装

- web/admin/src/pages/producers/index.vue
- web/admin/src/store/producer.ts
> 生産者削除機能の実装

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_test.go
- docs/swagger/admin/paths/v1/products/_productId/index.yaml
- web/admin/src/types/api/api.ts
> feat(gateway): implement delete product api

- docs/swagger/admin/components/schemas/v1/live.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/schedules/_scheduleId/lives/_liveId/index.yaml
- web/admin/src/types/api/api.ts
- getLive用のpathとtagを追加
- getLiveメソッドのindex.yaml追加
- responseにIVS周りの値を追加
> Docs:  make getLive swagger

- api/internal/store/entity/rehearsal.go
- infra/terraform/env/stg/06-dynamodb/00-locals.tf
- infra/terraform/env/stg/06-dynamodb/00-main.tf
- infra/terraform/env/stg/06-dynamodb/01-rehearsals.tf
- infra/terraform/env/stg/06-dynamodb/99-variables.tf
- infra/terraform/modules/dynamodb/01-table.tf
- infra/terraform/modules/dynamodb/99-variables.tf
> feat(terraform): create dynamodb resource

- api/internal/gateway/cmd/admin/registry.go
* admin gatewayの起動時設定として、DynamoDBクライアントの生成用設定を追加しました
> feat(gateway): add dynamodb client

- api/internal/store/database/database.go
- api/internal/store/database/live.go
- api/internal/store/database/live_test.go
- api/internal/store/database/schedule.go
- api/internal/store/input.go
- api/mock/store/database/database.go
- UpdateLiveのDB層実装
- Schedule内の一括インサートを修正
- UpdateLiveのテスト実装
https://calmato.kibe.la/notes/727
> Feat(store): implement UpdateLive database layer

- .github/dependabot.yaml
- .github/labeler.yaml
- .github/workflows/ci-function-for-all.yaml
- func/.gitignore
- func/.golangci.yaml
- func/Makefile
- func/ivs-cleaner/main.go
> feat(func): add github workflows

- infra/terraform/env/stg/07-ec2/user_data/nat-instance.sh
> fix(terraform): fix ec2 user data

- infra/mysql/schema/2023010401-stores-change-column.sql
> fix(store): fix payment card column name

- infra/mysql/schema/2023010402-stores-alter-column.sql
> fix(store): fix payment card primary key

- web/user/nuxt.config.ts
- web/user/package.json
- web/user/tsconfig.json
- web/user/vitest.config.ts
- web/user/yarn.lock
* テストで使用するライブラリの変更
* 未使用ライブラリ, 実装の削除
* TypeCheck用のコマンドを追加 -> CI対応は後日実施
> chore(user): update dependencies

- api/internal/store/database/live.go
- api/internal/store/database/schedule.go
- api/internal/store/database/schedule_test.go
- GetScheduleのdatabase層実装
https://calmato.kibe.la/notes/727
- Service
- Gateway
- Swagger
> feat(store): implement GetSchedule database layer

- docs/swagger/admin/components/schemas/v1/message.response.yaml
- web/admin/nuxt.config.ts
- web/admin/src/layouts/default.vue
- web/admin/src/middleware/notification.ts
- web/admin/src/store/message.ts
- web/admin/src/types/api/api.ts
> feat(admin): add notification badge

- api/internal/messenger/database/database.go
- api/internal/store/database/database.go
ORDER BYクエリに予約語が入っているときにSyntax Errorが発生してしまうため、クエリの形式を修正しました。
> fix(api): fix order by query

- api/internal/store/database/database.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/schedule.go
- api/internal/store/service/schedule_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- DatabaseにGetメソッド追加
- ServiceにGetScheduleメソッド追加
- モック作成
- GetScheduleのService層実装
> Feat(store): implement GetSchedule service layer

- web/admin/src/layouts/default.vue
> fix(admin): fix notification badge

- api/internal/user/database/admin.go
- api/internal/user/database/admin_test.go
- api/internal/user/database/administrator_test.go
- api/internal/user/database/coordinator_test.go
- api/internal/user/database/database_test.go
- api/internal/user/database/member.go
- api/internal/user/database/member_test.go
- api/internal/user/database/producer_test.go
- api/internal/user/database/user_test.go
> refactor(user): refactor user db test

- api/internal/messenger/database/contact_test.go
- api/internal/messenger/database/database_test.go
- api/internal/messenger/database/message_template_test.go
- api/internal/messenger/database/message_test.go
- api/internal/messenger/database/notification_test.go
- api/internal/messenger/database/push_template_test.go
- api/internal/messenger/database/received_queue_test.go
- api/internal/messenger/database/report_template_test.go
- api/internal/messenger/database/schedule_test.go
> refactor(messenger): refactor messenger db test

- api/internal/store/database/address_test.go
- api/internal/store/database/category.go
- api/internal/store/database/category_test.go
- api/internal/store/database/database_test.go
- api/internal/store/database/live_product_test.go
- api/internal/store/database/live_test.go
- api/internal/store/database/order_test.go
- api/internal/store/database/product_test.go
- api/internal/store/database/product_type_test.go
- api/internal/store/database/promotion.go
- api/internal/store/database/promotion_test.go
- api/internal/store/database/schedule_test.go
- api/internal/store/database/shipping_test.go
> refactor(store): refactor store db test

- web/admin/src/pages/coordinators/index.vue
- web/admin/src/pages/notifications/index.vue
- web/admin/src/pages/orders/index.vue
- web/admin/src/pages/producers/index.vue
- web/admin/src/pages/products/index.vue
- web/admin/src/pages/promotions/index.vue
- web/admin/src/pages/shippings/index.vue
> feat(admin): changing table header layout

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/schedule.go
- api/internal/gateway/admin/v1/handler/schedule_test.go
- api/internal/store/database/database.go
- api/internal/store/database/live.go
- api/internal/store/database/live_test.go
- api/internal/store/entity/live.go
- api/internal/store/entity/live_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/live.go
- api/internal/store/service/live_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- GetScheduleの権限を追加
- getIVSDetailsメソッドを追加
- EntityにLivesからIDの配列を取得するメソッドを追加
- Liveの一括取得を実装
- MultiGet
- ListByScheduleID
- GetScheduleのgateway
swagger
> Feat(store): Implement GetSchedule gateway

- web/admin/src/lib/hooks/usePagination.ts
- web/admin/src/pages/contacts/index.vue
- web/admin/src/store/contact.ts
> feat(admin): implement pagination for contact table

- web/user/nuxt.config.ts
- web/user/package.json
- web/user/src/components/templates/TheSignInPage.vue
- web/user/src/locales/en_us.json
- web/user/src/locales/ja_jp.json
- web/user/src/pages/signin.vue
- web/user/src/plugins/api-client.ts
- web/user/src/plugins/api-error-handler.ts
- web/user/src/plugins/helpter/factory.ts
- web/user/src/plugins/i18n.ts
- web/user/src/store/auth.ts
- web/user/src/types/exception.ts
- web/user/src/types/locales/i18n.ts
- web/user/src/types/plugins/index.d.ts
- web/user/tsconfig.json
- web/user/yarn.lock
- piniaのセットアップ
- authStoreにログインの関数を実装
> piniaのセットアップとログイン機能の実装

- .github/workflows/ci-backend-for-all.yaml
- .github/workflows/ci-function-for-all.yaml
- api/.golangci.yaml
- api/Makefile
- api/internal/gateway/admin/v1/service/postal_code_test.go
- func/.golangci.yaml
- func/Makefile
- infra/docker/api/Dockerfile.development
- infra/docker/api/gateway/admin/Dockerfile
- infra/docker/api/gateway/user/Dockerfile
- infra/docker/api/hack/Dockerfile
- infra/docker/api/media/resizer/Dockerfile
- infra/docker/api/messenger/scheduler/Dockerfile
- infra/docker/api/messenger/worker/Dockerfile
> chore(infra): update dependencies

- web/admin/src/pages/contacts/index.vue
- web/admin/src/store/contact.ts
> feat(admin): 問い合わせ一覧のソート機能を実装

- web/user/package.json
- web/user/yarn.lock
- Nuxt v3.3.2にアップデート
- 依存のエラーが発生したのでpostcss-custom-propertiesを追加した
> chore: web/user を Nuxt v3.3.2にアップデート

- func/go.mod
- func/go.sum
今週のライブラリ更新
* close: https://github.com/and-period/furumaru/pull/805
* close: https://github.com/and-period/furumaru/pull/806
* close: https://github.com/and-period/furumaru/pull/807
> chore(func): update dependencies

- api/internal/store/input.go
> fix(store): fix time validation

- web/admin/src/pages/accounts/email/index.vue
* メールアドレス変更フォームのラベル変更
* https://calmato.atlassian.net/browse/FA-27?atlOrigin=eyJpIjoiNDk0N2I5ZmRiYTk1NGY2YTgyZGRjZGJjOGJmOGY1NzQiLCJwIjoiaiJ9
> fix(admin): メールアドレス変更フォームのラベル変更

- web/admin/src/pages/notifications/index.vue
- web/admin/src/store/notification.ts
* お知らせ一覧のページネーション実装
* https://calmato.atlassian.net/browse/FA-15?atlOrigin=eyJpIjoiZTEwNjc3MTRiNTZmNGJmMDgxMzQ3OGRlMDVhNTM4M2EiLCJwIjoiaiJ9
> fix(admin): お知らせ一覧のページネーション実装

- api/internal/store/input.go
* プロモーション登録/更新時のバリデーション修正
* https://calmato.atlassian.net/browse/FA-19?atlOrigin=eyJpIjoiMGJiYzk1ZDY0YTdmNGMzNmI4NjdiY2ExYzQwMzY0MjQiLCJwIjoiaiJ9
> fix(store): プロモーション登録/更新時のバリデーション修正

- web/admin/src/pages/contacts/edit/_id.vue
[お問い合わせ編集の電話番号のフォーマットを整える
](https://calmato.atlassian.net/browse/FA-14)
の対応
> Fix: fixed FA-14

- web/admin/src/pages/customers/index.vue
- web/admin/src/store/customer.ts
[顧客管理で住所の代わりに電話番号を表示する](https://calmato.atlassian.net/browse/FA-12)
の実装
データ変更ありで、
https://calmato.atlassian.net/browse/FA-30
ここで対応する
> Fix: fixed FA-12

- web/admin/src/pages/contacts/edit/_id.vue
- web/admin/src/pages/coordinators/edit/_id.vue
- web/admin/src/pages/customers/index.vue
[お問い合わせの編集後に遷移する場所がおかしい](https://calmato.atlassian.net/browse/FA-1)
の対応
> Fix: fixed FA-1

- web/admin/src/middleware/auth.global.ts
- web/admin/src/store/auth.ts
アクセストークンが有効期限切れになったあと正しくリフレッシュしてくれない問題の修正
> feat(admin): トークンの有効性検証を追加

- web/admin/package.json
- web/admin/src/layouts/default.vue
- web/admin/yarn.lock
> fix(admin): fix navigation bar

- web/admin/src/lib/formatter/index.ts
- web/admin/src/lib/formatter/phone-number.ts
- web/admin/src/pages/producers/edit/[id].vue
- 生産者編集画面で電話番号のフォーマットが異なる問題に対応した
> 生産者編集画面で電話番号のフォーマットが異なる問題に対応した

- web/admin/src/components/templates/ProductList.vue
- web/admin/src/pages/products/index.vue
- web/admin/src/store/product.ts
* １ファイルのコード量が多く可読性悪いため分割
* クリックイベントが正しく動作していなかったため修正
* エラーのポップアップを追加
* 商品画像を四角に変更: https://calmato.atlassian.net/browse/FA-6?atlOrigin=eyJpIjoiMzgxMDJjZTA2OGRkNGY5OWIxZmUyMDBlMzY4ZWE1ODkiLCJwIjoiaiJ9
* 商品削除機能の実装: https://calmato.atlassian.net/browse/FA-9?atlOrigin=eyJpIjoiODdlZTM0NDU5YzUwNGMxYWIxNTQ0YjFmYmZlNjc3OGMiLCJwIjoiaiJ9
> fix(admin): 商品一覧関連の修正

- web/admin/src/components/templates/CategoryList.vue
- web/admin/src/components/templates/OrderList.vue
- web/admin/src/pages/orders/index.vue
> refactor(admin): 注文一覧のリファクタ

- web/admin/src/components/templates/ProductList.vue
- web/admin/src/lib/helpers/image.ts
- web/admin/src/lib/helpers/index.ts
- web/admin/src/pages/coordinators/index.vue
- web/admin/src/pages/producers/index.vue
リサイズ済み画像の取得処理について、各ファイルに書くと変更が必要なときの対応が困るので共通化しました。
> feat(admin): add helper fot images

- web/admin/src/components/organisms/PromotionForm.vue
- web/admin/src/pages/promotions/edit/[id].vue
> Refactoring

- api/internal/user/service/admin_auth.go
- api/internal/user/service/admin_auth_test.go
管理者IDを検索する際のカラム名指定が誤っていたため修正しました。
> fix(admin): fix column name for admin

- api/internal/gateway/admin/v1/handler/product.go
close済みのcontextを使用している箇所があったため修正しました。
> fix(admin): fix create product handler

- web/admin/src/components/organisms/ProductForm.vue
- web/admin/src/pages/products/[id].vue
- web/admin/src/pages/products/add.vue
- 削除する画像がサムネイルとして選択されていた場合は先頭の画像をサムネイル画像にする
> 商品画像の削除時に対象がサムネイル画像としてセットされていた場合に処理を追加

- web/admin/src/components/templates/OrderList.vue
- web/admin/src/pages/orders/index.vue
> fix(admin): 注文一覧画面のpropsが正しく渡せていなかった箇所を修正

- web/admin/src/components/organisms/NotificationForm.vue
- web/admin/src/components/organisms/PromotionForm.vue
- web/admin/src/components/templates/NotificationCreateFormPage.vue
- web/admin/src/components/templates/NotificationEditFormPage.vue
- web/admin/src/components/templates/PromotionCreateFormPage.vue
- web/admin/src/components/templates/PromotionEditFormPage.vue
- web/admin/src/lib/formatter/day.ts
- web/admin/src/pages/notifications/add.vue
- web/admin/src/pages/notifications/edit/[id].vue
- web/admin/src/pages/notifications/index.vue
- web/admin/src/pages/orders/[id].vue
- web/admin/src/pages/promotions/add.vue
- web/admin/src/pages/promotions/edit/[id].vue
- web/admin/src/pages/promotions/index.vue
- dayjsがbuild時に読めないのでimportの仕方を変更した
> 本番サーバでセール情報が開けない問題に対応

- infra/docker/web/amplify/Dockerfile
> feat(infra): update dockerfile for amplify

- web/admin/.gitignore
- web/admin/bin/update-version.ts
- web/admin/package.json
- web/admin/src/pages/settings.vue
- web/admin/src/pages/version.vue
- web/admin/tsconfig.script.json
- web/admin/yarn.lock
- `yarn build`前に実行される`prebuild`コマンドを定義して、バージョン情報を`version.json`に吐き出すようにした。
- バージョン情報ページを作成し、`version.json`から値を読み取るようにした。
> アプリケーションのバージョン情報を記載したページの実装

- infra/mysql/schema/2023050701-users-recreate-index.sql
> feat(mysql): recreate index for guests

- docs/swagger/admin/openapi.yaml
- docs/swagger/user/openapi.yaml
> feat(docs): add staging api domain

- web/admin/src/components/templates/CustomerList.vue
- web/admin/src/components/templates/CustomerShow.vue
* 顧客管理ページの表示項目変更
* https://calmato.atlassian.net/browse/FA-63?atlOrigin=eyJpIjoiMGE5ZjBkZGQxMTJlNDJmOTgzOWI3YWFjODU4Yzc3YjIiLCJwIjoiaiJ9
> feat(admin): 顧客管理ページの表示項目変更

- docs/swagger/Makefile
- infra/docker/docs/amplify/Dockerfile
- infra/terraform/env/shared/01-ecr/06-docs.tf
> feat(docs): APIドキュメントをホスティング環境へデプロイできるように

- web/user/src/components/atoms/cards/TheCardTitle.vue
- web/user/src/components/templates/TheSignInPage.vue
- web/user/src/components/templates/TheSignUpPage.vue
- web/user/src/components/templates/TheUserRegisterPage.vue
- web/user/src/components/templates/TheVerifyCodePage.vue
- web/user/src/layouts/auth.vue
- タイトルの文字の太さを調整した
- ロゴとフォームの位置を上辺でそろえるように修正した
> ユーザー登録系ページのレイアウト調整

- web/user/src/layouts/auth.vue
- 認証系画面でoverflowの設定がなくレイアウトが崩れて見えていたので修正
> 認証系画面でoverflowの設定を追加

- api/internal/messenger/entity/contact.go
- api/internal/messenger/entity/contact_category_test.go
- api/internal/messenger/entity/contact_catogory.go
- api/internal/messenger/entity/contact_test.go
- contact_categoryのentity
- contactのentity
- それぞれのテスト
databaseの実装
tableがuserIdをnull許容にしてるのをどう対応しようか考えて
この形になったが果たしてこれは適切なのか疑問
> Feat create contact entity

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact.go
- api/internal/messenger/service/contact_category.go
- api/mock/messenger/service.go
GetContactのservice層
GetContactCategoryのservice層
型名とか関数名はContactCategoryにしてあるので
中身の変数は縮めてcategoryIDにしてます
> Create get contact service

- api/internal/messenger/database/database.go
- api/internal/messenger/database/database_test.go
- api/internal/messenger/database/thread.go
- api/internal/messenger/database/thread_test.go
- api/mock/messenger/database/database.go
Threadの以下メソッドのdb層実装
- Get
- ListByContactID
> Feat list and get thread database layer

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/thread.go
- api/mock/messenger/service.go
Threadの
GetとListByContactID
service層実装
> Create list thread service

- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/pages/accounts/email/index.vue
- web/admin/src/pages/accounts/email/verification.vue
- web/admin/src/pages/accounts/password/index.vue
- web/admin/src/pages/categories/index.vue
- web/admin/src/pages/coordinators/add.vue
- web/admin/src/pages/coordinators/edit/[id].vue
- web/admin/src/pages/notifications/add.vue
- web/admin/src/pages/notifications/edit/[id].vue
- web/admin/src/pages/orders/index.vue
- web/admin/src/pages/producers/add.vue
- web/admin/src/pages/producers/edit/[id].vue
- web/admin/src/pages/products/[id].vue
- web/admin/src/pages/products/add.vue
- web/admin/src/pages/promotions/add.vue
- web/admin/src/pages/promotions/edit/[id].vue
- web/admin/src/pages/shippings/add.vue
- web/admin/src/pages/shippings/edit/[id].vue
- web/admin/src/pages/signin.vue
- web/admin/src/store/coordinator.ts
> refactor(admin): エラー処理の統一とコーディネータ周りの修正

- web/admin/src/components/templates/AdministratorList.vue
- web/admin/src/components/templates/SystemTop.vue
- web/admin/src/layouts/default.vue
- web/admin/src/pages/administrators/index.vue
- web/admin/src/pages/settings.vue
- web/admin/src/pages/system.vue
> feat(admin): メニューバーの整理

- web/admin/src/components/templates/AdministratorList.vue
- web/admin/src/pages/administrators/index.vue
- web/admin/src/store/administrator.ts
> feat(admin): 管理者一覧ページの実装

- web/admin/src/components/templates/AdministratorEdit.vue
- web/admin/src/components/templates/AdministratorList.vue
- web/admin/src/components/templates/AdministratorNew.vue
- web/admin/src/pages/administrators/[id]/index.vue
- web/admin/src/pages/administrators/index.vue
- web/admin/src/pages/administrators/new.vue
- web/admin/src/store/administrator.ts
> feat(admin): 管理者機能の実装

- web/admin/src/components/templates/AdministratorEdit.vue
- web/admin/src/components/templates/AdministratorNew.vue
- web/admin/src/components/templates/AuthEditEmail.vue
- web/admin/src/components/templates/AuthEditPassword.vue
- web/admin/src/components/templates/AuthVerifyEmail.vue
- web/admin/src/pages/accounts/email/index.vue
- web/admin/src/pages/accounts/email/verification.vue
- web/admin/src/pages/accounts/password/index.vue
- web/admin/src/store/auth.ts
> refactor(admin): アカウント周りのリファクタ

- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/contact.go
- api/internal/gateway/admin/v1/handler/thread.go
- api/internal/gateway/admin/v1/response/contact.go
- api/internal/gateway/admin/v1/service/contact.go
> implement GetContact handler

- api/internal/messenger/database/database.go
- api/internal/messenger/database/thread.go
- api/internal/messenger/database/thread_test.go
- api/mock/messenger/database/database.go
createThreadのdatabase層を実装
service層
handler層
createContactのhandler層
> Feat: create thread database

- web/admin/src/components/molecules/ImageSelectForm.vue
- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/components/templates/CoordinatorList.vue
- web/admin/src/components/templates/CoordinatorNew.vue
- web/admin/src/pages/coordinators/[id]/index.vue
- web/admin/src/pages/coordinators/index.vue
- web/admin/src/pages/coordinators/new.vue
* https://calmato.atlassian.net/browse/FA-72?atlOrigin=eyJpIjoiNWUzN2JhYjNkZmQyNDkyNWI0NzMxNTk3MjUzM2ZhNzYiLCJwIjoiaiJ9
> fix(admin): コーディネータ機能改修後の不具合修正

- api/internal/messenger/entity/thread.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/thread.go
- api/mock/messenger/service.go
CreateThreadのService層実装
CreateThreadのhandler
CreateContactのhandler
> Feat create thread service

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/thread.go
- api/internal/gateway/admin/v1/request/thread.go
CreateThreadのhandler実装
CreateContactのhandler実装
> Feat create thread handler

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/response/coordinator.go
- api/internal/gateway/admin/v1/response/promotion.go
- api/internal/gateway/admin/v1/service/coordinator.go
- api/internal/user/database/database.go
- api/internal/user/database/producer.go
- api/internal/user/database/producer_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- docs/swagger/admin/components/schemas/v1/coordinator.response.yaml
- docs/swagger/admin/components/schemas/v1/promotion.response.yaml
- web/admin/src/components/templates/CoordinatorList.vue
- web/admin/src/components/templates/ProducerList.vue
- web/admin/src/components/templates/PromotionEdit.vue
- web/admin/src/components/templates/PromotionList.vue
- web/admin/src/components/templates/PromotionNew.vue
- web/admin/src/types/api/api.ts
> feat(*): 紐づけ生産者数の追加

- api/internal/messenger/database/database.go
- api/internal/messenger/database/thread.go
- api/internal/messenger/database/thread_test.go
- api/mock/messenger/database/database.go
UpdateThreadのdb層実装
service層
handler層
> Feat update thread db

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/thread.go
- api/mock/messenger/service.go
UpdateThreadのservice層実装
handler層
> Feat update thread service

- api/internal/messenger/database/database.go
- api/internal/messenger/database/thread.go
- api/internal/messenger/database/thread_test.go
- api/mock/messenger/database/database.go
DeleteThreadのDB層実装
service層
handler層
> Feat: DeleteThread database layer

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/thread.go
- api/mock/messenger/service.go
DeleteThreadのservice層の実装
handler
> Feat: implement DeleteThread service layer

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/thread.go
DeleteThreadのhandler実装
- Contact
- Update
- Delete
- List
- ContactCategory
- List
- ContactRead
- Create
- Update
- Get
> Feat: implement DeleteThread handler

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/contact_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
UpdateContactのdb層実装
https://calmato.atlassian.net/wiki/spaces/~6065f64f1613f3006814a4bc/pages/23330842#Contact
service層
handler層
rebaseのためforce pushしましたすみません
> Feat: implement UpdateContact database layer

- api/internal/gateway/admin/v1/response/product.go
- api/internal/store/database/product.go
- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/components/templates/CoordinatorNew.vue
- web/admin/src/components/templates/ProductEdit.vue
- web/admin/src/components/templates/ProductList.vue
- web/admin/src/components/templates/ProductNew.vue
- web/admin/src/pages/products/[id]/index.vue
> fix(admin): 商品関連のバグ修正

- web/admin/src/components/templates/CustomerEdit.vue
- web/admin/src/components/templates/CustomerList.vue
> feat(admin): 顧客管理画面の実装

- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/messenger/entity/notification.go
- web/admin/src/components/templates/NotificationList.vue
- web/admin/src/components/templates/PromotionEdit.vue
- web/admin/src/components/templates/PromotionNew.vue
> fix(admin): お知らせ一覧と入力画面のUI修正

- api/internal/gateway/admin/v1/handler/administrator.go
- api/internal/gateway/admin/v1/handler/auth.go
- api/internal/gateway/admin/v1/response/auth.go
- api/internal/gateway/admin/v1/service/administrator.go
- api/internal/gateway/admin/v1/service/auth.go
- api/internal/gateway/admin/v1/service/coordinator.go
- api/internal/gateway/admin/v1/service/producer.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/user/registry.go
- docs/swagger/admin/components/schemas/v1/auth.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/auth/user/index.yaml
- docs/swagger/user/components/schemas/v1/auth.response.yaml
- web/admin/package.json
- web/admin/src/components/templates/NotificationEdit.vue
- web/admin/src/components/templates/NotificationNew.vue
- web/admin/src/components/templates/PromotionEdit.vue
- web/admin/src/components/templates/PromotionNew.vue
- web/admin/src/layouts/default.vue
- web/admin/src/middleware/auth.global.ts
- web/admin/src/pages/producers/new.vue
- web/admin/src/store/auth.ts
- web/admin/src/types/api/api.ts
- web/admin/yarn.lock
- web/user/src/types/api/models/AuthUserResponse.ts
> feat(*): ログインユーザー情報取得周りの実装

- api/internal/gateway/admin/v1/handler/admin.go
- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/gateway/admin/v1/service/notification.go
- api/internal/gateway/admin/v1/service/notification_test.go
- api/internal/gateway/admin/v1/service/promotion.go
- api/internal/gateway/admin/v1/service/promotion_test.go
- api/internal/messenger/cmd/scheduler/registry.go
- api/internal/messenger/entity/notification.go
- api/internal/messenger/entity/notification_test.go
- api/internal/messenger/service/notify.go
- api/internal/store/database/database.go
- api/internal/store/database/promotion.go
- api/internal/store/database/promotion_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
> fix(admin): セール関連のタイトルが表示される様に

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact.go
- api/mock/messenger/service.go
UpdateContactのservice層実装
handler
> Feat: implement UpdateContact service

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/contact.go
- api/internal/gateway/admin/v1/request/contact.go
UpdateContactのhandler実装
DeleteContact
> Feat: implement UpdateContact handler

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/contact_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
DeleteContactのDB層実装
service
hendler
> Feat: implement DeleteConatct db layer

- api/.tool-versions
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact.go
- api/mock/messenger/service.go
DeleteContactのservice層実装
handler
> Feat:  implement DeleteContact service layer

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/contact.go
> Feat: implement DeleteContact handler

- api/internal/messenger/database/contact_category.go
- api/internal/messenger/database/contact_category_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
ListContactCategoriesのDB層実装
service
handler
> Feat: implement  ListContactCategories db layer

- api/internal/gateway/admin/v1/handler/auth.go
- api/internal/gateway/admin/v1/request/auth.go
- api/internal/user/database/admin.go
- api/internal/user/database/admin_test.go
- api/internal/user/database/database.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/admin.go
- api/internal/user/service/admin_test.go
- api/mock/user/database/database.go
- api/mock/user/service.go
- docs/swagger/admin/components/schemas/v1/auth.request.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/auth/forgot-password/index.yaml
- docs/swagger/admin/paths/v1/auth/forgot-password/verified.yaml
- web/admin/src/types/api/api.ts
> feat(api): 管理者のパスワードリセットAPIを実装

- api/internal/messenger/entity/contact_read.go
- api/internal/messenger/entity/contact_read_test.go
ContactReadのentity実装
db
service
handler
> Feat: implement ContactRead entity

- api/internal/messenger/database/contact.go
- api/internal/messenger/database/contact_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
ListContactsのDB層実装
Countの実装
service
handler
> Feat:  implement ListContacts db layer

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact.go
- api/mock/messenger/service.go
ListContactsのservice層実装
handler
> Feat list contacts database

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/contact.go
- api/internal/gateway/admin/v1/response/contact.go
- api/internal/gateway/admin/v1/service/contact.go
ListContactsのhandler実装
ContactRead
ContactCategory
> Feat : implement ListContacts handler

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact_category.go
- api/mock/messenger/service.go
ListCntactCategoriesのservice層実装
handler
> Feat : implement ListContactCategories service

- api/internal/messenger/database/contact_read.go
- api/internal/messenger/database/contact_read_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
- infra/mysql/schema/2023062701-messengers-alter-column.sql
contact_readsのFK修正
CreateContactReadのdb層作成
service
handler
> Feat: implement CreateContactRead db layer

- api/internal/messenger/database/contact_category.go
- api/internal/messenger/database/contact_category_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
CreateContactCategoryのdb層実装
service
handler
> Feat: implement CreateContactCategory database layer

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/contact_category.go
- api/internal/gateway/admin/v1/response/contact_category.go
ListContactCategoriesのhandler実装
ContactCategories
ContactRead
> Feat: implement ListContactCategories handler

- api/internal/messenger/database/database.go
- api/internal/messenger/database/database_test.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact_read.go
- api/mock/messenger/service.go
CeateContactReadのservice層実装
handler
> Feat: implement CreateContactCead service layer

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/contact_read.go
- api/internal/gateway/admin/v1/request/contact_read.go
- api/internal/gateway/admin/v1/response/contact_read.go
- api/internal/gateway/admin/v1/service/contact_read.go
CreateContactReadのhandler実装
Get
> Feat: implement CreateContactRead handler layer

- api/internal/messenger/database/contact_read.go
- api/internal/messenger/database/contact_read_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
ContactReadのReadフラグを更新するAPIのDB層実装
service
handler
> Feat: UpdateContactReadFlag db layer

- api/internal/messenger/database/contact_read.go
- api/internal/messenger/database/contact_read_test.go
- api/internal/messenger/database/database.go
- api/mock/messenger/database/database.go
GetContactReadのDB層
handler
service
> Feat get contact read db

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/contact_read.go
- api/mock/messenger/service.go
GetContactReadのService層実装
handler
> Feat: implement GetContacRead service

- api/internal/messenger/input.go
- api/internal/messenger/service/thread.go
CreateThreadとListThreadsを呼んだ時に、ContactReadのReadフラグを更新するように追加
Notifyの繋ぎ込み
> Feat:  add updateContactReadFlag to thread

- api/internal/messenger/input.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/thread.go
> Feat: implement Notify recieved contact

- .github/workflows/pr-auto-approve-for-dependabot.yaml
> feat(workflow): Dependabot用のワークフローを追加

- web/admin/src/components/templates/ProductList.vue
> feat(admin): 商品一覧画面のステータス表示を変更

- web/admin/src/layouts/auth.vue
- web/admin/src/layouts/default.vue
> fix(admin): サインイン画面でスナックバーが出るように

- web/admin/src/components/templates/ProductEdit.vue
- web/admin/src/components/templates/ProductNew.vue
- web/admin/src/pages/products/[id]/index.vue
- web/admin/src/pages/products/new.vue
- web/admin/src/store/category.ts
- web/admin/src/store/product-tag.ts
- web/admin/src/store/product-type.ts
> feat(admin): 商品関連の検索ロジックを実装

- docs/swagger/admin/components/schemas/v1/thread.request.yaml
- docs/swagger/admin/components/schemas/v1/thread.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/contacts/_contactId/threads/_threadId/index.yaml
- docs/swagger/admin/paths/v1/contacts/_contactId/threads/index.yaml
- web/admin/src/types/api/api.ts
Thread用のSwagger実装
https://calmato.atlassian.net/wiki/spaces/~6065f64f1613f3006814a4bc/pages/23330842#Thread
contact
contactCatgeory
> Docs: add Thread swagger

- docs/swagger/admin/components/schemas/v1/contact-category.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/contact-categories/_contactCategoryId/index.yaml
- docs/swagger/admin/paths/v1/contact-categories/index.yaml
- web/admin/src/types/api/api.ts
お問い合わせ種別APIのswagger作成
https://calmato.atlassian.net/wiki/spaces/~6065f64f1613f3006814a4bc/pages/23330842#Thread
Contact
> Docs:  add contact category swagger

- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/service/product.go
- web/admin/src/components/templates/NotificationList.vue
- web/admin/src/pages/notifications/index.vue
- web/admin/src/pages/products/[id]/index.vue
- web/admin/src/pages/products/new.vue
- web/admin/src/store/product-type.ts
> fix(admin): レスポンス構造変更後のバグ修正

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/live.go
- api/internal/store/database/database.go
- api/internal/store/database/live.go
- api/internal/store/database/live_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/live.go
- api/internal/store/service/live_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- docs/swagger/admin/paths/v1/schedules/_scheduleId/lives/_liveId/index.yaml
- web/admin/src/components/organisms/LiveList.vue
- web/admin/src/components/organisms/ScheduleShow.vue
- web/admin/src/components/organisms/ScheduleStreaming.vue
- web/admin/src/components/templates/ScheduleShow.vue
- web/admin/src/pages/schedules/[id]/index.vue
- web/admin/src/store/live.ts
- web/admin/src/store/product.ts
- web/admin/src/store/schedule.ts
- web/admin/src/types/api/api.ts
> feat(admin): ライブ配信スケジュール周りの実装

- api/internal/media/resizer/image.go
- api/internal/media/resizer/image_test.go
> fix(media): 画像リサイズ処理の修正

- web/admin/src/components/templates/CategoryList.vue
- web/admin/src/components/templates/NotificationList.vue
- web/admin/src/components/templates/ProducerList.vue
- web/admin/src/components/templates/ProductList.vue
- web/admin/src/components/templates/ProductTagList.vue
- web/admin/src/components/templates/PromotionList.vue
- web/admin/src/components/templates/ScheduleList.vue
- web/admin/src/components/templates/ShippingList.vue
- web/admin/src/layouts/default.vue
- web/admin/src/pages/categories/index.vue
- web/admin/src/pages/notifications/index.vue
- web/admin/src/pages/producers/index.vue
- web/admin/src/pages/product-tags/index.vue
- web/admin/src/pages/products/index.vue
- web/admin/src/pages/promotions/index.vue
- web/admin/src/pages/schedules/index.vue
- web/admin/src/pages/shippings/index.vue
- web/admin/src/pages/system.vue
- web/admin/src/store/auth.ts
- web/admin/src/types/props/setting.ts
> feat(admin): サイドバーを権限によって出し分け

- api/internal/messenger/entity/thread_test.go
> fix(messenger): テストが落ちている箇所の修正

- api/internal/gateway/admin/v1/handler/shipping.go
- api/internal/gateway/admin/v1/request/shipping.go
- api/internal/gateway/admin/v1/response/shipping.go
- api/internal/gateway/admin/v1/service/shipping.go
- api/internal/store/database/database.go
- api/internal/store/database/live_test.go
- api/internal/store/database/order_test.go
- api/internal/store/database/schedule_test.go
- api/internal/store/database/shipping.go
- api/internal/store/database/shipping_test.go
- api/internal/store/entity/shipping.go
- api/internal/store/entity/shipping_test.go
- api/internal/store/input.go
- api/internal/store/service/shipping.go
- api/internal/store/service/shipping_test.go
- docs/swagger/admin/components/schemas/entity/shipping.yaml
- docs/swagger/admin/components/schemas/v1/shipping.request.yaml
- docs/swagger/admin/components/schemas/v1/shipping.response.yaml
- infra/mysql/schema/2023072501-stores-alter-column.sql
- web/admin/src/types/api/api.ts
> fix(store): 仕様変更に伴う配送設定エンティティの修正

- web/user/src/components/molecules/TheCarousel.vue
> fix: 4kサイズでも320pxにする

- api/internal/gateway/admin/v1/handler/shipping.go
- api/internal/gateway/admin/v1/response/shipping.go
- api/internal/store/entity/shipping.go
- api/internal/store/entity/shipping_test.go
- docs/swagger/admin/components/schemas/v1/shipping.response.yaml
- docs/swagger/admin/paths/v1/shippings/_shippingId/index.yaml
- web/admin/src/components/templates/ShippingList.vue
- web/admin/src/components/templates/ShippingNew.vue
- web/admin/src/pages/shippings/index.vue
- web/admin/src/pages/shippings/new.vue
- web/admin/src/store/shipping.ts
- web/admin/src/types/api/api.ts
> feat(store): 配送設定関連APIの修正

- web/admin/package.json
- web/admin/yarn.lock
Reverts and-period/furumaru#1173
> Revert "chore(deps): bump @pinia/nuxt from 0.4.9 to 0.4.11 in /web/admin"

- web/admin/src/components/molecules/ShippingRateForm.vue
- web/admin/src/components/organisms/CategoryList.vue
- web/admin/src/components/organisms/ProductTypeList.vue
- web/admin/src/components/templates/NotificationEdit.vue
- web/admin/src/components/templates/NotificationList.vue
- web/admin/src/components/templates/ProductTagList.vue
- web/admin/src/components/templates/PromotionEdit.vue
- web/admin/src/components/templates/PromotionList.vue
- web/admin/src/components/templates/ShippingList.vue
- web/admin/src/components/templates/ShippingNew.vue
- web/admin/src/pages/notifications/[id]/index.vue
- web/admin/src/pages/promotions/[id]/index.vue
- web/admin/src/pages/system.vue
> fix(admin): コーディネータ権限時の表示修正

- api/config/gateway/admin/rbac/policy.csv
> fix(api): コーディネータの権限周りの整理

- .github/workflows/ci-backend-for-all.yaml
- .github/workflows/ci-function-for-all.yaml
- api/.tool-versions
- func/.tool-versions
- infra/docker/api/Dockerfile.development
- infra/docker/api/gateway/admin/Dockerfile
- infra/docker/api/gateway/user/Dockerfile
- infra/docker/api/hack/Dockerfile
- infra/docker/api/media/resizer/Dockerfile
- infra/docker/api/messenger/scheduler/Dockerfile
- infra/docker/api/messenger/worker/Dockerfile
> chore(api): upgrade golang v1.20.6

- web/admin/src/components/molecules/ShippingRateForm.vue
- web/admin/src/components/templates/ShippingEdit.vue
- web/admin/src/components/templates/ShippingList.vue
- web/admin/src/components/templates/ShippingNew.vue
> fix(admin): 配送設定ページのUI修正

- api/internal/store/database/database.go
- api/internal/store/database/schedule.go
- api/internal/store/database/schedule_test.go
- api/internal/store/service/schedule.go
- api/internal/store/service/schedule_test.go
- api/mock/store/database/database.go
> feat(store): ライブ配信登録ロジックの追加

- web/admin/.eslintrc.cjs
- web/admin/src/components/organisms/LiveList.vue
- web/admin/src/components/organisms/ScheduleStreaming.vue
- web/admin/src/components/templates/ScheduleShow.vue
- web/admin/src/pages/schedules/[id]/index.vue
- web/admin/src/plugins/api-client.ts
- web/admin/src/store/broadcast.ts
- web/admin/src/store/index.ts
> feat(admin): ライブ配信視聴用のプレイヤーを追加

- infra/terraform/env/shared/02-route53/02-and-preiod-co-jp.tf
> feat(terraform): サブドメインの追加

- api/internal/store/cmd/scheduler/registry.go
- api/internal/store/cmd/updater/registry.go
- api/internal/store/database/broadcast_test.go
- infra/terraform/env/shared/01-ecr/07-store-scheduler.tf
- infra/terraform/env/shared/01-ecr/08-store-updater.tf
> fix(store): 参照先DBが誤っている箇所を修正

- web/user/src/components/organisms/purchase/TheMarcheCartItem.vue
- web/user/src/components/organisms/purchase/TheRecommendItem.vue
- web/user/src/constants/mock/purchase.ts
> 商品レコメンド部分をモックで配置

- api/internal/store/broadcast/updater/const.go
- api/internal/store/broadcast/updater/creator.go
- api/internal/store/broadcast/updater/remover.go
> feat(store): ライブ配信関連のジョブを実装

- infra/serverless/serverless.yml
- 作成したリソース情報を登録するLambdaを呼び出すステップを追加
- StateMachine名に環境名を含めるように修正
> feat: Add lambda to medialive sls

- infra/serverless/serverless.yml
InputでScheduleIdを受け取って出力するように変更
```
{
"RtmpInput": {
"StreamName": "/live/a"
},
"MP4Input": {
"OpeningVideoUrl": "s3://furumaru-stg/products/video/j3dwM2igpXhSdqVKgSheAM.mp4"
},
"ChannelInput": {
"Name": "kaito1002",
"StartTime": "2023-08-16T12:00:00Z",
"InputLossImageSlateUri": "s3://furumaru-stg/products/image/dcJHPTVgr1hPfJ7WatWy1n.png"
},
"ScheduleId": "hoge"
}
```
> feat: add ScheduleId to ResultSelector

- infra/serverless/serverless.yml
BatchUpdateScheduleと
それに使用する値を計算するCalculateMP4Timeを削除
> feat: remove BatchUpdateSchedule

- infra/serverless/serverless.yml
ライブ配信リソース作成用のコンフィグを更新
* Lambdaに渡される値を追加・更新
> feat(serverless): ライブ配信リソース作成用のコンフィグを更新

- infra/serverless/serverless.yml
> feat(serverless): アーカイブ映像用の出力グループを追加

- .github/workflows/cd-serverless-for-main.yaml
- infra/serverless/serverless.yml
Credentialの渡し方を修正した上で、mainへのマージ時にserverless deployするようにしました
> fead(severless): change credendtials setting

- infra/serverless/serverless.yml
DescribeChannelがNotFoundの際、終了させる
直接Endに繋げなかったのでPassを経由している
> feat: add not found handling

- .github/workflows/cd-gateway-for-stg.yaml
- .github/workflows/cd-media-for-stg.yaml
- .github/workflows/cd-messenger-for-stg.yaml
> fix(workflow): ビルド時の引数追加

- docs/swagger/admin/components/schemas/v1/shipping.request.yaml
- docs/swagger/admin/components/schemas/v1/shipping.response.yaml
- web/admin/src/components/templates/ShippingNew.vue
- web/admin/src/pages/shippings/new.vue
- web/admin/src/types/api/api.ts
> fix(admin): タイポの修正

- .github/workflows/cd-media-for-stg.yaml
- api/internal/gateway/cmd/admin/config.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/komoju/handler/api.go
- api/internal/gateway/komoju/handler/event.go
> feat(admin): KOMOJU用のWebhookエンドポイント追加

- web/user/src/components/molecules/TheCarousel.vue
- web/user/src/components/molecules/TheLiveItem.vue
- web/user/src/components/molecules/TheProductListItem.vue
- web/user/src/pages/index.vue
- トップページをスマートフォンなどのモバイル端末の表示に対応した。
> fix: トップページのレスポンシブ対応

- api/internal/gateway/admin/v1/handler/product.go
> fix(api): 商品更新APIの修正

- api/Makefile
- api/internal/media/database/database.go
- api/internal/media/database/mysql/broadcast.go
- api/internal/media/database/mysql/broadcast_test.go
- api/internal/media/entity/broadcast.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/broadcast_test.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/schedule.go
- api/internal/store/database/mysql/schedule_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/schedule.go
- api/internal/store/service/schedule_test.go
- api/mock/media/database/database.go
- api/mock/media/service.go
- api/mock/store/database/database.go
- api/mock/store/service.go
> feat(api): トップページ用API実装用のモジュール実装

- api/internal/gateway/cmd/user/registry.go
> feat(api): user-gatewayの起動時設定を修正

- api/internal/gateway/user/v1/handler/top.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/schedule.go
- api/internal/store/input.go
- api/internal/store/service/schedule.go
> fix(api): 開催スケジュール取得メソッドの修正

- api/internal/store/database/mysql/schedule.go
- docs/swagger/admin/components/schemas/v1/schedule.request.yaml
- web/admin/src/components/templates/ScheduleList.vue
- web/admin/src/pages/schedules/index.vue
- web/admin/src/store/schedule.ts
- web/admin/src/types/api/api.ts
> feat(admin): マルシェ承認機能の実装

- api/internal/gateway/user/v1/handler/category.go
- api/internal/gateway/user/v1/handler/coordinator.go
- api/internal/gateway/user/v1/handler/producer.go
- api/internal/gateway/user/v1/handler/product.go
- api/internal/gateway/user/v1/handler/product_tag.go
- api/internal/gateway/user/v1/handler/product_type.go
- api/internal/gateway/user/v1/service/category.go
- api/internal/gateway/user/v1/service/category_test.go
- api/internal/gateway/user/v1/service/coordinator.go
- api/internal/gateway/user/v1/service/coordinator_test.go
- api/internal/gateway/user/v1/service/producer.go
- api/internal/gateway/user/v1/service/producer_test.go
- api/internal/gateway/user/v1/service/product.go
- api/internal/gateway/user/v1/service/product_tag.go
- api/internal/gateway/user/v1/service/product_tag_test.go
- api/internal/gateway/user/v1/service/product_test.go
- api/internal/gateway/user/v1/service/product_type.go
- api/internal/gateway/user/v1/service/product_type_test.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/product.go
- api/internal/store/input.go
- api/internal/store/service/product.go
> feat(api): 商品関連APIの実装

- web/admin/src/components/templates/ProductList.vue
> fix(admin): 商品一覧ページのタイポ修正

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/request/coordinator.go
- api/internal/gateway/admin/v1/response/coordinator.go
- api/internal/gateway/admin/v1/service/coordinator.go
- api/internal/gateway/admin/v1/service/coordinator_test.go
- api/internal/store/entity/cart_test.go
- api/internal/user/database/database.go
- api/internal/user/database/mysql/coordinator.go
- api/internal/user/database/mysql/coordinator_test.go
- api/internal/user/entity/coordinator.go
- api/internal/user/entity/coordinator_test.go
- api/internal/user/input.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- docs/swagger/admin/components/schemas/entity/coordinator.yaml
- docs/swagger/admin/components/schemas/v1/coordinator.request.yaml
- infra/mysql/schema/2023102602-users-add-column-coorfdinator.sql
- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/components/templates/CoordinatorNew.vue
- web/admin/src/components/templates/ProductEdit.vue
- web/admin/src/components/templates/ProductNew.vue
- web/admin/src/pages/coordinators/[id]/index.vue
- web/admin/src/pages/coordinators/new.vue
- web/admin/src/types/api/api.ts
> feat(user): コーディネータ情報に営業日を追加

- api/internal/store/entity/cart.go
- api/internal/store/entity/cart_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/cart.go
- api/internal/store/service/cart_test.go
- api/internal/store/service/service.go
- api/internal/store/service/service_test.go
- api/mock/pkg/dynamodb/client.go
- api/mock/store/service.go
- api/pkg/dynamodb/client.go
> feat(store): カート操作ロジックの実装

- web/user/.eslintrc.cjs
- web/user/src/layouts/default.vue
- 縮むときは30px以下までスクロール値が戻ってから状態が変化するように修正
> ヘッダーの挙動を再修正

- web/user/src/components/organisms/purchase/TheMarcheCartItem.vue
- web/user/src/pages/purchase/index.vue
- web/user/src/pages/v1/purchase/address.vue
- web/user/src/pages/v1/purchase/complete.vue
- web/user/src/pages/v1/purchase/confirmation.vue
https://www.figma.com/file/FooG44xvYKEhicxTcp1FZm/furumaru?node-id=626%3A2186&mode=dev
> Add: added user information input form

- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/user/v1/handler/api.go
- api/internal/gateway/user/v1/handler/cart.go
- api/internal/gateway/user/v1/handler/product.go
- api/internal/gateway/user/v1/response/cart.go
- api/internal/gateway/user/v1/service/cart.go
- api/internal/gateway/user/v1/service/cart_test.go
- api/internal/gateway/user/v1/service/order.go
- api/internal/gateway/user/v1/service/order_test.go
- api/internal/store/entity/cart.go
- api/internal/store/entity/cart_test.go
- api/internal/store/entity/product.go
- api/internal/store/entity/product_test.go
- docs/swagger/user/components/schemas/entity/cart.yaml
- web/user/src/types/api/models/Cart.ts
> feat(api): カート関連APIの実装

- api/internal/media/service.go
- api/internal/messenger/service.go
- api/internal/store/service.go
- api/internal/user/service.go
> refactor(api): インターフェースのコメント文の書き方を修正

- docs/swagger/user/components/schemas/codes/schedule.yaml
- web/user/src/types/api/models/ScheduleStatus.ts
> fix(api): 開催状況のステータスを追加

- api/internal/gateway/user/v1/service/live.go
- api/internal/gateway/user/v1/service/live_test.go
- api/internal/gateway/user/v1/service/schedule.go
- api/internal/gateway/user/v1/service/schedule_test.go
- api/internal/gateway/user/v1/service/top.go
- api/internal/gateway/user/v1/service/top_test.go
> feat(api): マルシェ情報関連のエンティティ操作ロジックを実装

- api/internal/gateway/user/v1/handler/schedule.go
- api/internal/gateway/user/v1/handler/top.go
- api/internal/media/database/database.go
- api/internal/media/database/mysql/broadcast.go
- api/internal/media/input.go
- api/internal/media/service/broadcast.go
- api/internal/store/input.go
> feat(api): マルシェ開催スケジュール取得APIの実装

- api/internal/gateway/user/v1/service/address.go
- api/internal/gateway/user/v1/service/address_test.go
> feat(api): アドレス帳周りのエンティティロジックを実装

- api/internal/messenger/cmd/worker/registry.go
- api/internal/messenger/cmd/worker/worker.go
- api/internal/messenger/worker/push.go
- api/internal/messenger/worker/worker.go
- api/internal/messenger/worker/worker_test.go
> fix(messenger): Firebaseの認証情報を複数つめられるように

- api/internal/gateway/user/v1/handler/top.go
- api/internal/media/broadcast/scheduler/closer.go
- api/internal/media/broadcast/scheduler/starter.go
- api/internal/store/input.go
> fix(store): 一覧取得時のバリデーション修正

- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/admin/v1/handler/api_test.go
- api/internal/gateway/cmd/admin/admin.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/router.go
- api/internal/gateway/cmd/user/user.go
- api/internal/gateway/komoju/handler/api.go
- api/internal/gateway/user/v1/handler/api.go
- api/internal/gateway/user/v1/handler/api_test.go
- api/pkg/sentry/option.go
- api/pkg/sentry/option_test.go
> fix(api): エラーハンドリングの修正

- api/go.mod
- api/go.sum
- api/internal/user/entity/member.go
- api/internal/user/service/admin_test.go
- api/internal/user/service/service.go
- api/internal/user/service/user_test.go
- api/mock/pkg/validator/validator.go
- api/pkg/validator/validator.go
- api/pkg/validator/validator_test.go
> fix(api): パスワードのバリデーションを修正

- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/komoju/handler/api.go
- api/internal/gateway/user/v1/handler/api.go
- api/internal/media/cmd/resizer/registry.go
- api/internal/media/cmd/scheduler/registry.go
- api/internal/media/cmd/updater/registry.go
- api/internal/messenger/cmd/scheduler/registry.go
- api/internal/messenger/cmd/worker/registry.go
- api/pkg/log/logger.go
- api/pkg/log/logger_test.go
- api/pkg/log/setnry.go
- api/pkg/sentry/option.go
> feat(api): Sentryアラートにサーバー名と環境を出すように

- web/user/nuxt.config.ts
- web/user/src/pages/about.vue
- web/user/src/pages/index.vue
- web/user/src/pages/items/[...id].vue
- web/user/src/pages/items/index.vue
- ページコンポーネントに`title`タグを設定してみた。
- `generate`でどのような挙動をするかのチェックをしたい。
> titleタグを設定

- web/admin/src/components/organisms/ProductTypeList.vue
- web/admin/src/components/templates/AdministratorList.vue
- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/components/templates/CoordinatorList.vue
- web/admin/src/components/templates/CoordinatorNew.vue
- web/admin/src/pages/coordinators/new.vue
コーディネーター画面と、管理者画面に遷移できなかったので修正
> Fix: fixed coordinator / administrator list

- web/user/src/layouts/default.vue
- web/user/src/pages/contact.vue
> Add: added contact page

- api/internal/gateway/user/v1/handler/api.go
> fix(api): Cookieの送受信をSecureに変更

- api/internal/media/resizer/resizer.go
- api/internal/media/resizer/resizer_test.go
> fix(media): マルシェ開催スケジュールのサムネイルリサイズ機能を実装

- web/admin/src/components/molecules/ShippingRateForm.vue
- web/admin/src/components/organisms/CategoryList.vue
- web/admin/src/components/organisms/ProductTypeList.vue
- web/admin/src/components/organisms/RelatedProducerList.vue
- web/admin/src/components/templates/ContactList.vue
- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/components/templates/CustomerList.vue
- web/admin/src/components/templates/NotificationList.vue
- web/admin/src/components/templates/OrderList.vue
- web/admin/src/components/templates/OrderShow.vue
- web/admin/src/components/templates/ProductList.vue
- web/admin/src/components/templates/ProductTagList.vue
- web/admin/src/components/templates/PromotionList.vue
- web/admin/src/components/templates/ScheduleList.vue
- web/admin/src/components/templates/ShippingEdit.vue
- web/admin/src/components/templates/ShippingList.vue
> fix(admin): テーブル周りの型定義エラーを修正

- api/internal/user/service/user.go
- api/internal/user/service/user_test.go
> fix(user): ユーザ登録時のコード検証APIを修正

- api/internal/gateway/user/v1/handler/checkout.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- api/mock/store/service.go
> feat(api): PayPay支払い機能の追加

- api/internal/store/entity/order_payment.go
- api/internal/store/entity/order_payment_test.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
> fix(api): KOMOJUのリクエスト値を修正

- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/komoju/handler/api.go
- api/internal/gateway/komoju/handler/event.go
- api/internal/gateway/komoju/handler/payment.go
- api/internal/gateway/komoju/request/payment.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/order.go
- api/internal/store/database/mysql/order_test.go
- api/internal/store/entity/cart.go
- api/internal/store/entity/cart_test.go
- api/internal/store/entity/order_payment.go
- api/internal/store/entity/order_payment_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- infra/mysql/schema/2023111401-stores-add-column-order-payment.sql
> feat(gateway): KOMOJUからの支払い完了Webhookを受信できるように

- api/internal/store/database/database.go
- api/internal/store/database/mysql/mysql.go
- api/internal/store/database/mysql/mysql_test.go
- api/internal/store/database/mysql/payment_system.go
- api/internal/store/database/mysql/payment_system_test.go
- api/internal/store/entity/payment_system.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/payment_system.go
- api/internal/store/service/payment_system_test.go
- api/internal/store/service/service_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- infra/mysql/schema/2023111402-stores-create-payment-systems.sql
> feat(store): 決済種別毎の利用可否情報を定義

- api/internal/gateway/admin/v1/service/order_payment.go
- api/internal/gateway/admin/v1/service/order_payment_test.go
- api/internal/gateway/admin/v1/service/order_refund.go
- api/internal/gateway/admin/v1/service/order_refund_test.go
- api/internal/gateway/komoju/handler/event.go
- api/internal/gateway/komoju/handler/payment.go
- api/internal/store/database/mysql/order.go
- api/internal/store/database/mysql/order_test.go
- api/internal/store/entity/order_payment.go
- api/internal/store/entity/order_payment_test.go
- api/internal/store/input.go
- api/internal/store/komoju/code.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- docs/swagger/admin/components/schemas/codes/order_payment.yaml
- docs/swagger/admin/components/schemas/codes/order_refund.yaml
- infra/mysql/schema/2023111403-stores-add-column-order-payment.sql
- web/admin/src/types/api/api.ts
> fix(store): 支払い関連イベントの追加

- api/internal/gateway/user/v1/handler/checkout.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- api/mock/store/service.go
> feat(store): QR決済関連の支払い機能を追加

- web/admin/src/components/templates/PaymentSystemList.vue
- web/admin/src/constants/index.ts
- web/admin/src/constants/payments.ts
- web/admin/src/pages/payment-systems/index.vue
- web/admin/src/types/api/api.ts
> feat(admin): 決済メンテページの実装

- api/internal/gateway/admin/v1/handler/order.go
- api/internal/store/entity/order_payment.go
- api/internal/store/entity/order_payment_test.go
- api/internal/store/input.go
- api/internal/store/komoju/komoju.go
- api/internal/store/komoju/payment/payment.go
- api/internal/store/komoju/payment/payment_test.go
- api/internal/store/service.go
- api/internal/store/service/order.go
- api/internal/store/service/order_test.go
- api/mock/store/komoju/komoju.go
- api/mock/store/service.go
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/cancel.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/capture.yaml
- web/admin/src/types/api/api.ts
> feat(api): 注文確定APIの実装

- api/internal/store/service/category.go
- api/internal/store/service/category_test.go
- docs/swagger/admin/paths/v1/categories/_categoryId/index.yaml
> fix(store): カテゴリ削除処理の修正

- infra/serverless/env/stg.yaml
- infra/serverless/serverless.yml
サブネットIDを新規構築されたものに修正
lambdaのArnを修正
> Infra: ライブ配信リソースの修正

- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/messenger/service/service_test.go
- api/internal/user/database/database.go
- api/internal/user/database/mysql/user.go
- api/internal/user/input.go
- api/internal/user/service/user.go
- api/internal/user/service/user_test.go
- api/mock/messenger/service.go
> feat(messenger): ユーザーへのお知らせ通知を実装

- .github/dependabot.yaml
- web/user/package.json
- web/user/yarn.lock
This reverts commit 338e92edd3bcf60e282b2baf6c950408693704e1.
> Revert "chore(deps-dev): bump @nuxtjs/i18n in /web/user (#1571)"

- web/user/src/components/atoms/live/TheLiveVideoPlayer.vue
- web/user/src/components/molecules/TheLiveTimelineItem.vue
- web/user/src/pages/live/[...id].vue
> ライブ画面のスマートフォン向けのUIに対応

- api/config/messenger/mailer/dev.yaml
- api/config/messenger/mailer/stg.yaml
- api/internal/messenger/entity/mail_config.go
- api/internal/messenger/entity/mail_config_test.go
- api/internal/messenger/entity/payload.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/user/entity/address.go
- api/internal/user/entity/address_test.go
> feat(messenger): 支払い完了時の通知を追加

- api/internal/gateway/user/v1/response/coordinator.go
- api/internal/gateway/user/v1/service/coordinator.go
- api/internal/gateway/user/v1/service/coordinator_test.go
- docs/swagger/user/components/schemas/entity/coordinator.yaml
- docs/swagger/user/components/schemas/v1/product.response.yaml
- web/user/src/types/api/models/Coordinator.ts
> feat(api): コーディネータ関連のレスポンスに営業日を追加

- web/user/src/components/organisms/header/TheAppHeader.vue
- web/user/src/components/organisms/header/TheCartItem.vue
- web/user/src/components/organisms/header/TheCartProductItem.vue
- web/user/src/components/organisms/header/ThePcCartMenu.vue
- web/user/src/layouts/default.vue
- web/user/src/store/shopping.ts
> 買い物カゴからの商品削除機能の実装

- web/user/src/components/organisms/purchase/TheMarcheCartItem.vue
- web/user/src/pages/purchase/index.vue
> 買い物カゴページのスマートフォン表示に対応

- web/user/src/pages/items/[...id].vue
- web/user/src/store/product.ts
> Add: added product detail other work

- api/internal/store/database/database.go
- api/internal/store/database/mysql/product.go
- api/internal/store/service/product_tag.go
- api/internal/store/service/product_tag_test.go
> fix(store): 商品タグ削除時の処理を修正

- web/user/src/pages/about.vue
> aboutページのスマートフォン向けレイアウト調整

- docs/swagger/admin/paths/v1/product-tags/_productTagId/index.yaml
- web/admin/src/types/api/api.ts
- web/user/src/types/api/index.ts
- web/user/src/types/api/models/DeliveryType.ts
- web/user/src/types/api/models/ImageSize.ts
- web/user/src/types/api/models/PaymentMethodType.ts
- web/user/src/types/api/models/PaymentSystemStatus.ts
- web/user/src/types/api/models/Prefecture.ts
- web/user/src/types/api/models/ProductStatus.ts
- web/user/src/types/api/models/ScheduleStatus.ts
- web/user/src/types/api/models/ShippingSize.ts
- web/user/src/types/api/models/ShippingType.ts
- web/user/src/types/api/models/StorageMethodType.ts
- web/user/src/types/api/models/index.ts
> fix(admin): 商品タグ削除APIへ投げる処理を修正

- api/internal/gateway/admin/v1/response/address.go
- api/internal/gateway/admin/v1/service/address.go
- api/internal/gateway/admin/v1/service/address_test.go
> fix(api): アドレス帳関連のレスポンスを修正

- api/internal/gateway/admin/v1/handler/user.go
- api/internal/gateway/admin/v1/response/user.go
- api/internal/gateway/admin/v1/service/user.go
- api/internal/gateway/admin/v1/service/user_test.go
- docs/swagger/admin/components/schemas/entity/user.yaml
- docs/swagger/admin/components/schemas/v1/user.response.yaml
- docs/swagger/admin/openapi.yaml
- web/admin/src/components/templates/CustomerList.vue
- web/admin/src/pages/customers/index.vue
- web/admin/src/store/customer.ts
- web/admin/src/types/api/api.ts
> fix(admin): 顧客一覧APIのレスポンスの型定義

- web/user/src/components/atoms/live/TheLiveVideoPlayer.vue
- web/user/src/pages/live/[...id].vue
> Add: added promotion asset

- api/internal/gateway/admin/v1/handler/user.go
- api/internal/gateway/admin/v1/response/user.go
- api/internal/gateway/admin/v1/service/user_order.go
- api/internal/gateway/admin/v1/service/user_order_test.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/order.go
- api/internal/store/input.go
- api/internal/store/service/order.go
- docs/swagger/admin/components/schemas/entity/user.yaml
- docs/swagger/admin/components/schemas/v1/user.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/users/_userId/index.yaml
- docs/swagger/admin/paths/v1/users/_userId/orders/index.yaml
- web/admin/src/types/api/api.ts
> feat(api): ユーザーごとの注文履歴一覧取得APIを実装

- api/internal/gateway/admin/v1/handler/user.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/order.go
- api/internal/store/database/mysql/order_test.go
- api/internal/store/input.go
- api/internal/store/service/order.go
- api/internal/store/service/order_test.go
- api/mock/store/database/database.go
> fix(api): 顧客一覧に表示する情報のフィルタリング

- web/user/src/components/atoms/live/TheLiveVideoPlayer.vue
> Fix: fixed player full size when we use iphone

- api/internal/gateway/admin/v1/handler/user.go
- api/internal/gateway/admin/v1/response/user.go
- docs/swagger/admin/components/schemas/v1/user.response.yaml
- docs/swagger/user/components/schemas/v1/checkout.request.yaml
- web/admin/src/types/api/api.ts
- web/user/src/types/api/models/CheckoutRequest.ts
> feat(api): 購入合計金額を返すように

- web/admin/src/pages/accounts/index.vue
> fix(admin): サインアウト後の遷移先を修正

- web/admin/src/components/organisms/LiveList.vue
- web/admin/src/components/templates/ScheduleShow.vue
> fix(admin): 商品選択プルダウンの修正

- web/admin/src/components/templates/CustomerEdit.vue
- web/admin/src/components/templates/CustomerList.vue
- web/admin/src/pages/customers/[id]/index.vue
- web/admin/src/pages/customers/index.vue
- web/admin/src/store/customer.ts
- web/admin/src/types/api/api.ts
> feat(admin): 顧客詳細ページの実装

- api/internal/media/broadcast/scheduler/closer.go
- api/internal/media/broadcast/scheduler/const.go
- api/internal/media/broadcast/scheduler/scheduler.go
- api/internal/media/cmd/scheduler/registry.go
- api/internal/media/database/database.go
- api/internal/media/database/mysql/broadcast.go
- api/internal/media/database/mysql/broadcast_test.go
- api/mock/pkg/storage/client.go
- api/pkg/storage/client.go
- api/pkg/storage/client_test.go
> feat(media): アーカイブ動画の登録処理を実装

- api/internal/gateway/admin/v1/response/order.go
- api/internal/gateway/admin/v1/service/order_fulfillment.go
- api/internal/gateway/admin/v1/service/order_fulfillment_test.go
- api/internal/gateway/user/v1/response/cart.go
- api/internal/gateway/user/v1/service/cart.go
- api/internal/gateway/user/v1/service/cart_test.go
- docs/swagger/admin/components/schemas/entity/order.yaml
- docs/swagger/admin/components/schemas/v1/order.response.yaml
- docs/swagger/user/components/schemas/entity/cart.yaml
- docs/swagger/user/components/schemas/v1/cart.response.yaml
- web/admin/src/components/templates/OrderShow.vue
- web/admin/src/types/api/api.ts
- web/user/src/types/api/models/Cart.ts
> feat(api): 注文関連のレスポンスに占有率を追加

- api/internal/media/broadcast/scheduler/const.go
- api/internal/media/broadcast/scheduler/scheduler.go
- api/internal/media/database/mysql/broadcast.go
- api/internal/media/entity/regulation.go
- api/internal/media/entity/regulation_test.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/broadcast_test.go
- api/mock/media/service.go
> feat(media): アーカイブ動画アップロード処理の実装

- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/broadcast_test.go
- api/internal/media/service/service.go
- api/internal/media/service/service_test.go
- api/mock/media/service.go
- api/mock/pkg/medialive/client.go
- api/pkg/medialive/client.go
- api/pkg/medialive/schedule.go
> feat(media): ふた絵の操作ロジックを実装

- api/internal/gateway/admin/v1/handler/broadcast.go
- api/internal/media/broadcast/scheduler/const.go
- api/internal/media/broadcast/scheduler/starter.go
- api/internal/media/entity/regulation.go
- api/internal/media/entity/regulation_test.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/broadcast_test.go
- api/internal/media/service/service.go
- api/internal/media/service/service_test.go
- api/mock/media/service.go
- api/mock/pkg/storage/client.go
- api/pkg/medialive/schedule.go
- api/pkg/storage/client.go
- api/pkg/storage/client_test.go
- docs/swagger/admin/components/schemas/v1/broadcast.request.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/schedules/_scheduleId/broadcasts/mp4.yaml
- docs/swagger/admin/paths/v1/schedules/_scheduleId/broadcasts/rtmp.yaml
- infra/serverless/serverless.yml
- web/admin/src/types/api/api.ts
> feat(media): ライブ配信時のMP4入力を動的に指定できるように

- web/user/src/pages/v1/purchase/confirmation.vue
Add: added purchase confirmation mobile page
> Add: added purchase confirmation mobile page

- web/user/src/pages/v1/purchase/complete.vue
added purchase complete moblie page
> Add: added purchase complete moblie page

- api/go.mod
- api/go.sum
Reverts and-period/furumaru#1666
> Revert "chore(deps): bump github.com/aws/aws-sdk-go-v2 from 1.23.2 to 1.23.4 in /api"

- web/admin/src/components/molecules/VideoSelectForm.vue
https://calmato.atlassian.net/issues/FA-104?filter=10010
の修正
> Fix: fixed FA-104

- web/admin/src/components/molecules/AddressForm.vue
- web/admin/src/components/organisms/CoordinatorShow.vue
> Fix: fixed FA-103

- web/admin/src/components/molecules/AddressForm.vue
- web/admin/src/components/organisms/CoordinatorShow.vue
> fix: s/prefectureCode/prefecture

- api/internal/store/database/database.go
- api/internal/store/database/mysql/product.go
- api/internal/store/database/mysql/product_test.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- api/mock/store/database/database.go
> feat(store): 注文時の商品減算処理を追加

- web/admin/src/components/organisms/CoordinatorShow.vue
- web/admin/src/components/templates/CoordinatorEdit.vue
- web/admin/src/components/templates/CoordinatorNew.vue
- web/admin/src/pages/coordinators/[id]/index.vue
- web/admin/src/pages/coordinators/new.vue
> fix(admin): コーディネータ編集ページで取り扱い品目の検索ができるように

- web/admin/src/components/templates/ProductNew.vue
> fix(admin): 都道府県入力フォームをv-autocompleteを使用するように変更

- api/internal/store/entity/live.go
- api/internal/store/entity/live_test.go
- api/internal/store/service/live.go
- api/internal/store/service/live_test.go
> fix(store): ライブスケジュールの重複チェックを実装

- web/admin/src/pages/administrators/index.vue
> Fix: fixed system admin page

- api/config/gateway/admin/rbac/policy.csv
- api/internal/gateway/admin/v1/handler/order.go
- api/internal/gateway/admin/v1/request/order.go
- api/internal/gateway/admin/v1/response/order.go
- api/internal/gateway/admin/v1/service/order.go
- api/internal/gateway/admin/v1/service/order_test.go
- api/internal/store/entity/order.go
- api/internal/store/entity/order_fulfillment.go
- api/internal/store/entity/order_fulfillment_test.go
- docs/swagger/admin/components/schemas/codes/order.yaml
- docs/swagger/admin/components/schemas/entity/order.yaml
- docs/swagger/admin/components/schemas/v1/order.request.yaml
- docs/swagger/admin/components/schemas/v1/order.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/complete.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/draft.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/fulfillments/_fulfillmentId/index.yaml
- docs/swagger/admin/paths/v1/orders/_orderId/refund.yaml
- infra/mysql/schema/2023120301-stores-add-column-orders.sql
- web/admin/src/components/templates/OrderList.vue
- web/admin/src/components/templates/OrderShow.vue
- web/admin/src/types/api/api.ts
> feat(api): 配送関連APIの定義を追加

- api/internal/store/service/checkout.go
> fix(store): コーディネータの配送設定取得処理を修正

- api/internal/media/broadcast/scheduler/closer.go
- api/internal/media/broadcast/scheduler/const.go
> feat(media): 配信リソース削除処理の実装

- docs/swagger/user/components/schemas/entity/cart.yaml
- docs/swagger/user/paths/v1/addresses/_addressId/index.yaml
- docs/swagger/user/paths/v1/addresses/index.yaml
- web/user/src/types/api/apis/AddressApi.ts
- web/user/src/types/api/index.ts
- web/user/src/types/api/models/Cart.ts
- web/user/src/types/api/models/DeliveryType.ts
- web/user/src/types/api/models/ImageSize.ts
- web/user/src/types/api/models/PaymentMethodType.ts
- web/user/src/types/api/models/PaymentSystemStatus.ts
- web/user/src/types/api/models/Prefecture.ts
- web/user/src/types/api/models/ProductStatus.ts
- web/user/src/types/api/models/ScheduleStatus.ts
- web/user/src/types/api/models/ShippingSize.ts
- web/user/src/types/api/models/ShippingType.ts
- web/user/src/types/api/models/StorageMethodType.ts
- web/user/src/types/api/models/Weekday.ts
- web/user/src/types/api/models/index.ts
- web/user/src/types/store/shopping.ts
> fix(docs): 型の定義の詳細化

- web/admin/src/components/templates/OrderShow.vue
- web/admin/src/pages/orders/[id]/index.vue
> fix(admin): 注文詳細画面のレビュー反映

- .github/workflows/pr-labeler.yaml
> fix: Labelerのバージョンをv4に固定にする

- api/internal/gateway/user/v1/handler/cart.go
- api/internal/gateway/util/metadata.go
- api/internal/gateway/util/request.go
- api/internal/gateway/util/request_test.go
- api/internal/store/entity/order_payment.go
- api/internal/store/entity/order_payment_summary.go
- api/internal/store/entity/order_payment_summary_test.go
- api/internal/store/input.go
- api/internal/store/service/cart.go
- api/internal/store/service/cart_test.go
- docs/swagger/user/openapi.yaml
- docs/swagger/user/paths/v1/carts/_coordinatorId/index.yaml
- web/user/src/types/api/apis/CartApi.ts
> fix(api): カートの中身を計算するAPIの修正

- web/user/src/components/atoms/TheAlertBox.vue
- web/user/src/components/molecules/TheAlert.vue
- web/user/src/components/molecules/TheArchiveItem.vue
- web/user/src/components/organisms/purchase/TheMarcheCartItem.vue
- web/user/src/pages/index.vue
- web/user/src/pages/purchase/index.vue
- web/user/src/pages/v1/purchase/address.vue
- web/user/src/pages/v1/purchase/confirmation.vue
- web/user/src/store/home.ts
- web/user/src/store/shopping.ts
> 購入手続きフローでの買い物カゴAPIとの連携

- web/user/src/components/molecules/TheSnackbar.vue
> Fix: fixed snackbar mobile size

- infra/serverless/serverless.yml
> feat(serverless): ポーリング処理の設定調整

- api/internal/gateway/user/v1/handler/cart.go
- api/internal/gateway/user/v1/handler/checkout.go
- api/internal/gateway/user/v1/handler/promotion.go
- api/internal/gateway/user/v1/request/checkout.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/promotion.go
- api/internal/store/database/mysql/promotion_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/cart.go
- api/internal/store/service/cart_test.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- api/internal/store/service/promotion.go
- api/internal/store/service/promotion_test.go
- api/mock/store/database/database.go
- api/mock/store/service.go
- docs/swagger/user/components/schemas/v1/checkout.request.yaml
- docs/swagger/user/paths/v1/carts/_coordinatorId/index.yaml
- web/user/src/types/api/apis/CartApi.ts
- web/user/src/types/api/models/CheckoutRequest.ts
> feat(store): プロモーションコードで割引情報が引けるように

- api/pkg/validator/validator.go
- api/pkg/validator/validator_test.go
> fix(validator): バリデーションの不整合を修正

- web/user/src/components/organisms/TheSignUpForm.vue
- web/user/src/pages/signup.vue
> サインアップフォームを更新

- web/user/src/components/molecules/TheProductListItem.vue
> 商品一覧で長い商品名に対応できるように3行で3点リーダにするようにする

- api/internal/gateway/user/v1/handler/live.go
- api/internal/gateway/user/v1/handler/product.go
- api/internal/store/entity/live.go
- api/internal/store/input.go
- api/internal/store/service/live.go
- api/internal/store/service/live_test.go
- api/pkg/set/set.go
- api/pkg/set/set_test.go
> fix(store): マルシェ開催スケジュールから非公開商品情報を除外

- api/internal/gateway/user/v1/response/product.go
- api/internal/gateway/user/v1/service/product.go
- api/internal/gateway/user/v1/service/product_test.go
- api/internal/store/database/mysql/product_test.go
- api/internal/store/entity/product.go
- api/internal/store/entity/product_test.go
- docs/swagger/user/components/schemas/entity/product.yaml
- docs/swagger/user/components/schemas/v1/product.response.yaml
- web/user/src/types/api/models/Product.ts
> feat(store): 商品情報にサムネイルを追加

- docs/swagger/user/components/schemas/v1/schedule.response.yaml
- web/user/src/types/api/models/ScheduleResponse.ts
> fix(docs): 開催スケジュールレスポンスのtypo修正

- api/internal/media/broadcast/scheduler/starter.go
> fix(media): 配信開始時のスケジュール設定を一律同じ設定に

- infra/serverless/serverless.yml
> feat(serverless): HLSセグメント関連の設定変更

- infra/serverless/serverless.yml
> feat: MediaStoreの削除失敗時にRetry処理するように修正

- web/user/src/components/molecules/TheLiveTimelineItem.vue
- web/user/src/components/molecules/TheLiveTimelineProduct.vue
- web/user/src/components/molecules/TheSnackbar.vue
- web/user/src/components/organisms/TheLiveTimeline.vue
- web/user/src/lib/price.ts
- web/user/src/pages/live/[...id].vue
> ライブ画面から商品追加できるようにする

- api/internal/gateway/user/v1/handler/cart.go
- api/internal/gateway/user/v1/handler/checkout.go
- api/internal/gateway/user/v1/request/checkout.go
- api/internal/gateway/user/v1/response/cart.go
- api/internal/store/entity/order.go
- api/internal/store/entity/order_test.go
- api/internal/store/input.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
- docs/swagger/user/components/schemas/v1/cart.response.yaml
- docs/swagger/user/components/schemas/v1/checkout.request.yaml
- web/user/src/types/api/models/CalcCartResponse.ts
- web/user/src/types/api/models/CheckoutRequest.ts
> fix(store): 支払いAPIの重複実行抑止対策

- api/internal/user/database/mysql/admin.go
- api/internal/user/database/mysql/administrator.go
- api/internal/user/database/mysql/coordinator.go
- api/internal/user/database/mysql/guest.go
- api/internal/user/database/mysql/member.go
- api/internal/user/database/mysql/producer.go
- api/internal/user/database/mysql/user.go
- api/internal/user/entity/administrator.go
- api/internal/user/entity/coordinator.go
- api/internal/user/entity/guest.go
- api/internal/user/entity/member.go
- api/internal/user/entity/producer.go
- api/internal/user/entity/user.go
- api/internal/user/service/administrator.go
- api/internal/user/service/user.go
- infra/mysql/schema/2023121601-users-drop-columns.sql
> fix(user): 状態を重複して持ってしまっている箇所の修正

- web/user/src/store/shopping.ts
> 占有率の表示がおかしい問題に対応

- api/internal/gateway/admin/v1/service/product.go
- api/internal/gateway/admin/v1/service/product_test.go
- api/internal/store/database/mysql/product.go
- api/internal/store/entity/product.go
- api/internal/store/entity/product_test.go
- docs/swagger/admin/components/schemas/codes/product.yaml
- web/admin/src/components/templates/ProductEdit.vue
- web/admin/src/components/templates/ProductList.vue
- web/admin/src/types/api/api.ts
> feat(admin): 商品ステータスにアーカイブ済みを追加

- api/internal/store/database/mysql/schedule.go
> feat(store): 開催スケジュールのデフォルト並び順を指定

- web/user/src/app.vue
- web/user/src/components/atoms/TheTextInput.vue
- web/user/src/components/molecules/TheSnackbar.vue
- web/user/src/layouts/default.vue
- スナックバーの位置がスクロール位置に依らずに上部に表示されるように調整した
- Inputタグのデザイン修正
> スマホ向けのUIUX改善

- web/user/src/components/molecules/TheDropdownWithIcon.vue
> スマートフォンでカゴの部分が右にはみ出るのを修正

- web/user/src/components/organisms/TheNewAddressForm.vue
> selectタグのデザインを調整する

- web/user/src/components/organisms/TheNewAddressForm.vue
> selectタグの背景色を調整する

- api/internal/gateway/user/v1/handler/live.go
> fix(api): 配信タイムスケジュールがなくてもライブ表示されるように

- web/user/src/pages/live/[...id].vue
> fix: ライブ配信中かの判定条件を変更

- web/user/package.json
- web/user/yarn.lock
> chore(user): ライブラリの更新

- infra/serverless/serverless.yml
> feat(serverless): MediaLiveの設定を修正

- api/internal/gateway/cmd/admin/router.go
- api/internal/gateway/cmd/user/router.go
> feat(api): アクセスログの内容を調整

- web/admin/package.json
- web/admin/src/components/organisms/CategoryList.vue
- web/admin/src/components/organisms/ProductTypeList.vue
- web/admin/src/components/organisms/RelatedProducerList.vue
- web/admin/src/components/templates/AdministratorList.vue
- web/admin/src/components/templates/ContactList.vue
- web/admin/src/components/templates/CustomerList.vue
- web/admin/src/components/templates/CustomerShow.vue
- web/admin/src/components/templates/NotificationList.vue
- web/admin/src/components/templates/OrderList.vue
- web/admin/src/components/templates/OrderShow.vue
- web/admin/src/components/templates/PaymentSystemList.vue
- web/admin/src/components/templates/ProducerList.vue
- web/admin/src/components/templates/ProductList.vue
- web/admin/src/components/templates/ProductTagList.vue
- web/admin/src/components/templates/PromotionList.vue
- web/admin/src/components/templates/ScheduleList.vue
- web/admin/src/components/templates/ShippingList.vue
- web/admin/src/pages/contacts/index.vue
- web/admin/src/pages/product-tags/index.vue
- web/admin/src/pages/promotions/index.vue
- web/admin/yarn.lock
> chore(admin): update dependencies

- api/internal/store/service/order.go
- api/internal/store/service/order_test.go
> feat(store): 発送完了通知の呼び出し処理を追加

- .github/labeler.yaml
- .github/workflows/pr-labeler.yaml
> chore(workflow): PRラベル付与ワークフローの修正

- api/internal/messenger/database/mysql/schedule.go
- api/internal/messenger/entity/schedule.go
- api/internal/messenger/entity/schedule_test.go
- api/internal/messenger/scheduler/notification.go
- infra/mysql/schema/2023122901-messengers-add-column-schedules.sql
> feat(messenger): 予約通知の締め切り時間を設定

- api/internal/messenger/database/database.go
- api/internal/messenger/database/mysql/schedule.go
- api/internal/messenger/database/mysql/schedule_test.go
- api/internal/messenger/entity/schedule.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/reserve.go
- api/internal/messenger/service/reserve_test.go
- api/mock/messenger/database/database.go
- api/mock/messenger/service.go
> feat(messenger): 通知の送信予約用APIの実装

- api/internal/messenger/entity/schedule.go
- api/internal/messenger/scheduler/scheduler.go
- api/internal/messenger/scheduler/scheduler_test.go
- api/internal/messenger/scheduler/start_live.go
- api/internal/messenger/scheduler/start_live_test.go
> feat(messenger): 通知スケジューラジョブの処理を修正

- api/internal/messenger/service/notification.go
- api/internal/messenger/service/notification_test.go
> feat(messenger): お知らせの送信予約処理を追加

- web/admin/src/plugins/axios.ts
- web/admin/src/store/coordinator.ts
- web/admin/src/store/producer.ts
- web/admin/src/store/product-type.ts
- web/admin/src/store/product.ts
- web/admin/src/store/schedule.ts
> fix(admin): リクエストタイムアウトを延長

- web/admin/src/pages/products/[id]/index.vue
> fix(admin): 商品更新ボタンがアクティベート状態にならない不具合を修正

- web/admin/src/components/templates/PromotionEdit.vue
- web/admin/src/components/templates/PromotionList.vue
> fix(admin): セール情報のステータスを修正

- web/user/src/pages/v1/purchase/complete.vue
- web/user/src/pages/v1/purchase/confirmation.vue
> feat(user): 購入フローにデバッグログを追加

- api/internal/gateway/user/v1/handler/coordinator.go
- api/internal/gateway/user/v1/handler/producer.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/product.go
- api/internal/store/input.go
- api/internal/store/service/product.go
- api/internal/store/service/product_test.go
> fix(api): 商品取得時に販売終了しているものは除外されるように

- infra/mysql/schema/2024010201-stores-add-index.sql
- infra/mysql/schema/2024010202-users-add-index.sql
> feat(database): 全文検索用のインデックス追加

- api/internal/store/database/mysql/category.go
- api/internal/store/database/mysql/category_test.go
- api/internal/store/database/mysql/mysql_test.go
- api/internal/store/database/mysql/product.go
- api/internal/store/database/mysql/product_tag.go
- api/internal/store/database/mysql/product_tag_test.go
- api/internal/store/database/mysql/product_type.go
- api/internal/store/database/mysql/product_type_test.go
- api/internal/store/database/mysql/promotion.go
> fix(store): 検索クエリの修正

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/producer.go
- api/internal/user/database/database.go
- api/internal/user/database/mysql/coordinator.go
- api/internal/user/database/mysql/coordinator_test.go
- api/internal/user/database/mysql/producer.go
- api/internal/user/database/mysql/producer_test.go
- api/internal/user/input.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/producer.go
> fix(user): 検索クエリの修正

- api/internal/messenger/entity/mail_config.go
- api/internal/messenger/entity/mail_config_test.go
- api/internal/messenger/service/notify_test.go
> feat(messenger): 支払い完了通知に注文番号を追加

- api/internal/store/entity/credit_card.go
- api/internal/store/entity/credit_card_test.go
- api/internal/store/input.go
- api/internal/store/komoju/errors.go
- api/internal/store/komoju/errors_test.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
> fix(store): クレジットカードのバリデーション実装

- web/user/src/components/molecules/TheCoordinatorArchiveItem.vue
- web/user/src/components/molecules/TheCoordinatorLiveItem.vue
- web/user/src/components/molecules/TheCoordinatorProductList.vue
- web/user/src/components/molecules/TheProducerList.vue
- web/user/src/pages/coordinator/[...id].vue
> Add: added coordinator moblie page

- web/user/src/components/molecules/TheProductListItem.vue
> Fix: fixed coordinator page routing

- web/user/src/pages/items/[...id].vue
> Fix: fixed moblie layout

- web/user/src/pages/coordinator/[...id].vue
> Fix: fixed coordinator live item

- api/internal/store/komoju/api.go
- api/internal/store/komoju/api_test.go
- api/internal/store/komoju/errors.go
- api/internal/store/komoju/errors_test.go
- api/internal/store/komoju/payment/payment_test.go
- api/internal/store/komoju/session/session_test.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_test.go
> fix(store): 支払いAPIのエラーハンドリング修正

- web/user/src/components/molecules/TheLiveTimelineItem.vue
> fix: dayjsのunixのimportの仕方を変更

- web/user/src/pages/items/[...id].vue
> feat: 商品詳細ページで複数画像を選択できるようにした

- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-media-for-prd.yaml
- .github/workflows/cd-messenger-for-prd.yaml
- api/hack/create-admin/main.go
> feat(workflow): バックエンドの本番デプロイ用のワークフロー追加

- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-messenger-for-prd.yaml
> fix(workflow): 本番デプロイ用のワークフローを修正

- web/user/src/pages/coordinator/[...id].vue
> コーディネーターページをSSRするようにした

- web/user/src/components/molecules/TheLiveItem.vue
- web/user/src/pages/live/[...id].vue
> ライブ視聴ページの修正

- web/user/src/components/molecules/TheCoordinatorLiveItem.vue
> Fix: fixed coordinator live item css

- infra/serverless/env/prd.yaml
prdにStepfunctionsをデプロイするために環境変数を追加
> feat(servereless): prd用の環境変数を追加

- api/internal/gateway/cmd/admin/registry.go
> feat(api): NewRelicにラベル付きメトリクスを送信するように

- web/user/src/components/molecules/TheLiveItem.vue
- web/user/src/pages/index.vue
- コンポーネント内でdayjsの利用方法を修正した
- トップページのコンポーザブルを`useAsyncData`に変更した。
> トップページをSSRできるように修正

- web/user/src/middleware/auth.ts
- web/user/src/pages/account/index.vue
- 認証を要求するページでログイン画面にリダイレクトさせる処理を行う`auth`のミドルウェアを用意した
- `/account`のページで上記のミドルウェアを使うようにした
> 認証されていない状態でマイページアクセスできないようにする

- web/user/src/components/molecules/TheCoordinatorLiveItem.vue
> Fix: fixed dayjs

- api/internal/messenger/entity/mail_config.go
- api/internal/messenger/entity/mail_config_test.go
- api/internal/messenger/entity/received_queue_test.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/messenger/worker/mailer.go
- api/internal/messenger/worker/mailer_test.go
- api/internal/messenger/worker/worker_test.go
- api/internal/store/entity/product.go
- api/internal/store/entity/product_test.go
- api/internal/user/entity/address.go
- api/internal/user/entity/address_test.go
生成される値でネスト構造を許容していなかったが、商品一覧情報の連携などでネストが必要になったため
> fix(messenger): メールの動的変数生成ロジックの修正

- web/admin/src/components/organisms/LiveList.vue
- web/admin/src/pages/products/[id]/index.vue
- デフォルトで設定されるサムネイル画像の判定処理を修正した。
> fix: デフォルトで設定されるサムネイル画像の判定処理を変更

- api/internal/user/database/database.go
- api/internal/user/database/mysql/coordinator.go
- api/internal/user/database/mysql/coordinator_test.go
- api/internal/user/database/mysql/producer.go
- api/internal/user/database/mysql/producer_test.go
- api/internal/user/input.go
- api/internal/user/service/coordinator.go
- api/internal/user/service/coordinator_test.go
- api/internal/user/service/producer.go
- api/internal/user/service/producer_test.go
- api/mock/user/database/database.go
> feat(user): 退会済み管理者を取得できるように

- web/user/src/pages/signup.vue
- web/user/src/pages/v1/purchase/auth.vue
- web/user/src/pages/verify.vue
- 購入時に新規アカウント作成をした場合にも購入フローが進められるようにクエリパラメータの受け渡しを修正した。
> fix: 購入時に新規アカウント作成をした場合にも購入フローが進むように修正

- web/user/src/pages/account/index.vue
> feat:注文履歴、アドレス帳が0件の場合にページネーション部分を非表示にしてメッセージを出すように変更

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/order.go
- api/internal/gateway/user/v1/handler/coordinator.go
- api/internal/gateway/user/v1/handler/order.go
> fix(api): コーディネータが退会済みの場合の対応

- web/user/src/components/atoms/live/TheLiveVideoPlayer.vue
- web/user/src/components/molecules/TheCoordinatorArchiveItem.vue
- web/user/src/components/molecules/TheCoordinatorLiveItem.vue
- web/user/src/components/molecules/TheCoordinatorProductList.vue
- web/user/src/components/molecules/TheProducerList.vue
- web/user/src/pages/coordinator/[...id].vue
- web/user/src/pages/live/[...id].vue
- コーディネーター詳細画面で商品詳細画面に遷移できるようにした。
- ライブ配信画面からコーディネーター詳細画面に遷移できるようにした
> コーディネーター詳細周りの整備

- web/user/src/components/organisms/TheNewAddressForm.vue
- web/user/src/pages/account/index.vue
> Fix default address maessage

- web/user/src/components/organisms/purchase/TheMarcheCartItem.vue
> fix: 配送地と配送元の情報を修正

- api/internal/gateway/user/v1/handler/order.go
> fix(api): 並列実行時のwait処理を追加

- web/user/src/lib/order.ts
- web/user/src/pages/account/index.vue
- web/user/src/pages/account/orders/[...id].vue
- web/user/src/store/order.ts
- web/user/src/store/shopping.ts
- web/user/src/types/store/order.ts
> 注文履歴詳細画面の実装

- web/user/src/middleware/auth.global.ts
- web/user/src/store/auth.ts
> fix: リフレッシュトークンが期限切れの場合に500エラーになる問題への対応

- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/messenger/worker/mailer.go
- api/internal/messenger/worker/mailer_test.go
- api/internal/user/database/database.go
- api/internal/user/database/mysql/user.go
- api/internal/user/input.go
- api/internal/user/service/user.go
- api/internal/user/service/user_test.go
> fix(messenger): 生産者と仮登録ユーザーにメール送信されないように

- api/internal/store/database/mysql/live.go
> fix(store): ライブスケジュールのソート順序を修正

- api/internal/store/komoju/session/session.go
- api/internal/store/komoju/session/session_test.go
> fix(store): 3Dセキュアの必須指定を削除

- api/internal/store/komoju/session/session.go
- api/internal/store/komoju/session/session_test.go
> fix(store): クレジットカード決済のKOMOJU連携値を変更

- web/user/src/pages/v1/purchase/confirmation.vue
> fix: クレジットカードのフォームの改善とカード名義の変更

- api/internal/store/entity/credit_card.go
- api/internal/store/entity/credit_card_test.go
- api/internal/store/service/checkout.go
> fix(store): クレジットカードの処理を修正

- api/internal/store/komoju/komoju.go
- api/internal/store/komoju/session/session_test.go
> fix(store): 3Dセキュア認証結果のパース処理を修正

- web/user/src/app.vue
> fix: new relic

- web/user/src/pages/v1/purchase/complete.vue
> feat: 決済完了画面でのエラーハンドリングを追加

- api/internal/gateway/admin/v1/handler/user.go
- api/internal/user/database/database.go
- api/internal/user/database/mysql/user.go
- api/internal/user/input.go
- api/internal/user/service/user.go
> fix(user): ユーザー一覧取得クエリの修正

- api/internal/user/database/mysql/user.go
> fix(users): クエリのテーブル指定の誤りを修正

- api/internal/store/input.go
> feat(store): ライブ配信関連のバリデーションを修正

- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/media/entity/regulation.go
- api/internal/media/entity/regulation_test.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/generate.go
- api/internal/media/service/generate_test.go
- api/mock/media/service.go
- api/mock/pkg/storage/client.go
- api/pkg/storage/client.go
- docs/swagger/admin/paths/v1/upload/coordinators/thumbnail.yaml
- web/admin/src/types/api/api.ts
> feat(media): アップロード用の署名付きURL取得機能を実装

- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/gateway/admin/v1/request/uploader.go
- api/internal/gateway/admin/v1/response/uploader.go
- api/internal/media/entity/regulation.go
- api/internal/media/entity/regulation_test.go
- api/internal/media/input.go
- api/internal/media/service/generate.go
- api/internal/media/service/generate_test.go
- docs/swagger/admin/components/schemas/v1/upload.request.yaml
- docs/swagger/admin/components/schemas/v1/upload.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/upload/coordinators/thumbnail.yaml
- web/admin/src/pages/coordinators/[id]/index.vue
- web/admin/src/pages/coordinators/new.vue
- web/admin/src/store/coordinator.ts
- web/admin/src/types/api/api.ts
> fix(media): コーディネータのサムネイル画像アップロード方法の改修

- api/internal/media/cmd/cmd.go
- api/internal/media/cmd/uploader/registry.go
- api/internal/media/cmd/uploader/uploader.go
- api/internal/media/entity/regulation.go
- api/internal/media/entity/regulation_test.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/generate.go
- api/internal/media/uploader/uploader.go
- api/mock/pkg/storage/client.go
- api/pkg/storage/client.go
> feat(media): ファイルバリデーション用のワーカー実装

- web/admin/src/types/validations/shipping.ts
> Fix: fixed price validate

- web/user/nuxt.config.ts
> Fix: fiexed ogp url

- api/internal/gateway/admin/v1/handler/uploader.go
- api/internal/gateway/admin/v1/response/uploader.go
- api/internal/gateway/admin/v1/service/upload_status.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/upload.go
- api/internal/media/service/upload_test.go
- api/mock/media/service.go
- docs/swagger/admin/components/schemas/codes/upload.yaml
- docs/swagger/admin/components/schemas/v1/upload.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/upload/state.yaml
- web/admin/src/types/api/api.ts
> feat(media): ファイルアップロード状態が取得できるように

- api/internal/media/database/database.go
- api/internal/media/database/mysql/broadcast.go
- api/internal/media/entity/broadcast.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/broadcast_test.go
- infra/mysql/schema/2024012901-media-add-columns.sql
> feat(media): アーカイブ映像の編集フラグを追加

- api/internal/gateway/user/v1/handler/address.go
- api/internal/gateway/user/v1/handler/api.go
- api/internal/gateway/user/v1/handler/api_test.go
- api/internal/gateway/user/v1/handler/auth.go
- api/internal/gateway/user/v1/handler/checkout.go
- api/internal/gateway/user/v1/handler/order.go
- api/internal/gateway/user/v1/handler/schedule.go
- api/internal/media/database/database.go
- api/internal/media/database/mysql/broadcast_viewer_log.go
- api/internal/media/database/mysql/broadcast_viewer_log_test.go
- api/internal/media/database/mysql/mysql_test.go
- api/internal/media/entity/broadcast_viewer_log.go
- api/internal/media/entity/broadcast_viewer_log_test.go
- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/media/service/broadcast_viewer_log.go
- api/internal/media/service/broadcast_viewer_log_test.go
- api/internal/media/service/service_test.go
- api/mock/media/database/database.go
- api/mock/media/service.go
- infra/mysql/schema/2024012902-media-create-broadcast-viewer-logs.sql
> feat(media): ライブ配信の視聴ログ取得機能を実装

- web/user/src/components/atoms/live/TheLiveDescription.vue
- web/user/src/components/atoms/live/TheLiveVideoPlayer.vue
- web/user/src/lib/dayjs.ts
- web/user/src/pages/live/[...id].vue
> スマートフォンのライブ画面で動画部分固定にして商品部分をスクロールできるようにする

- api/internal/messenger/entity/report_config.go
- api/internal/messenger/entity/url.go
- api/internal/messenger/entity/url_test.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
> feat(messenger): 支払い完了時にLINE通知が来るように

- api/internal/media/entity/regulation.go
> feat(media): アーカイブ映像の制約を調整

- web/user/nuxt.config.ts
- web/user/src/app.vue
- web/user/src/pages/v1/purchase/complete.vue
- web/user/src/public/meta/pixel-code-purchase.js
- web/user/src/public/meta/pixel-code.js
- 本番環境でだけmeta pixel codeが使われるように挿入した。
> meta pixel codeを仕込む

- api/internal/gateway/user/v1/handler/live_comment.go
- docs/swagger/user/paths/v1/schedules/_scheduleId/comments/index.yaml
- web/user/src/types/api/apis/ScheduleApi.ts
> fix(api): 認証なしでもライブ配信コメントが取得できるように

- web/user/src/components/molecules/TheLiveTimelineProduct.vue
- web/user/src/components/molecules/TheProductListItem.vue
- web/user/src/lib/product.ts
- web/user/src/pages/items/index.vue
> 販売終了した商品のUIを更新

- api/internal/store/service/cart.go
- api/internal/store/service/cart_test.go
> fix(store): カート追加時のバリデーション修正

- api/internal/gateway/user/v1/service/live_product.go
- api/internal/gateway/user/v1/service/live_product_test.go
> fix(gateway): ライブ配信ページの商品の並び順を修正

- api/internal/gateway/user/v1/service/order.go
- api/internal/gateway/user/v1/service/order_test.go
> feat(gateway): 注文ステータス追加に伴う改修

- web/user/src/components/organisms/purchase/TheMarcheCartItem.vue
> Fix: fixed sentence based on nishikawa sister

- api/internal/store/entity/product.go
> fix(store): 商品のソートキーを修正

- .github/workflows/_backend_build_and_push.yaml
- .github/workflows/_backend_deploy_ecr.yaml
- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-gateway-for-stg.yaml
- .github/workflows/cd-media-for-prd.yaml
- .github/workflows/cd-media-for-stg.yaml
- .github/workflows/cd-messenger-for-prd.yaml
- .github/workflows/cd-messenger-for-stg.yaml
- .github/workflows/cd-serverless-for-main.yaml
- .github/workflows/cd-web-admin-for-prd.yaml
- .github/workflows/cd-web-user-for-prd.yaml
> fix(workflow): GitHub Actionsの一部共通化をした箇所の修正

- .github/workflows/_backend_build_and_push.yaml
- .github/workflows/_backend_deploy_ecr.yaml
- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-gateway-for-stg.yaml
> fix: 共通化したjobへの変数の渡し方を修正

- .github/workflows/cd-gateway-for-stg.yaml
> fix(workflow): gatewayのstg環境デプロイジョブを修正

- web/user/src/types/api/index.ts
- web/user/src/types/api/models/DeliveryType.ts
- web/user/src/types/api/models/DiscountType.ts
- web/user/src/types/api/models/FulfillmentStatus.ts
- web/user/src/types/api/models/ImageSize.ts
- web/user/src/types/api/models/OrderRefundType.ts
- web/user/src/types/api/models/OrderStatus.ts
- web/user/src/types/api/models/PaymentMethodType.ts
- web/user/src/types/api/models/PaymentStatus.ts
- web/user/src/types/api/models/PaymentSystemStatus.ts
- web/user/src/types/api/models/Prefecture.ts
- web/user/src/types/api/models/ProductStatus.ts
- web/user/src/types/api/models/PromotionStatus.ts
- web/user/src/types/api/models/ScheduleStatus.ts
- web/user/src/types/api/models/ShippingCarrier.ts
- web/user/src/types/api/models/ShippingSize.ts
- web/user/src/types/api/models/ShippingType.ts
- web/user/src/types/api/models/StorageMethodType.ts
- web/user/src/types/api/models/UploadStatus.ts
- web/user/src/types/api/models/Weekday.ts
- web/user/src/types/api/models/index.ts
> fix(user): Linterにより修正されている自動生成ファイルの修正

- api/internal/gateway/cmd/user/registry.go
> fix(gateway): 起動時処理の修正

- .github/workflows/_build_and_push.yaml
- .github/workflows/_deploy_ecs.yaml
- .github/workflows/cd-gateway-for-stg.yaml
> revert(workflow): environmentの検証をもとに戻す

- web/admin/src/components/organisms/ScheduleShow.vue
- web/admin/src/components/organisms/ScheduleStreaming.vue
- web/admin/src/components/templates/ScheduleNew.vue
> feat(admin): ライブ配信画像でjpegアップロードができるように

- .github/workflows/cd-func-for-prd.yaml
- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-media-for-prd.yaml
- .github/workflows/cd-messenger-for-prd.yaml
- .github/workflows/cd-web-admin-for-prd.yaml
- .github/workflows/cd-web-user-for-prd.yaml
- .github/workflows/pr-release.yaml
> fix(workflow): リリースタグ作成ジョブでPATを使わないように

- .github/workflows/pr-openai-review.yaml
> fix(workflow): OpenAIのレビュー対象からcalmato-devを削除

- .github/workflows/cd-func-for-prd.yaml
- .github/workflows/cd-func-for-stg.yaml
- .github/workflows/pr-release.yaml
- func/bin/update-cloudfront-distribution.sh
- func/cloudfront-origin-response/Makefile
> fix(workflow): Lambda@Edgeのデプロイフローを修正

- func/cloudfront-origin-response/src/app.ts
> fix(func): オリジンレスポンスの処理を修正

- web/user/src/pages/items/index.vue
- web/user/src/store/product.ts
> fix:すべての商品画面のローディング状態に使うステータスをuseAsyncDataの返り値にする

- web/user/src/pages/items/[...id].vue
> fix: 買い物カゴに入れるボタンの参照する状態変数を修正

- api/internal/media/entity/url.go
- api/internal/media/entity/url_test.go
> fix(media): youtube認証時のリダイレクトURLを変更

- api/pkg/youtube/service.go
> fix(media): YouTube配信とストリーム設定の関連付け処理を修正

- api/config/gateway/admin/rbac/policy.csv
> fix(gateway): ライブ配信削除APIの権限設定

- web/admin/src/pages/schedules/index.vue
> fix(admin): ライブ配信削除後、モーダルが非表示になるように

- CHANGELOG.md
This pull request is for the next release as v1.11.16 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v1.11.16 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v1.11.15" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v1.11.16

- web/admin/src/pages/auth/youtube/callback.vue
> fix(admin): Google認証後の処理を修正

- func/cloudfront-origin-response/src/app.ts
> fix(func): 画像リサイズ処理の引数取得処理を修正

- web/admin/src/layouts/default.vue
> Fix: fixed 29 line

- web/user/src/components/molecules/TheArchiveItem.vue
https://github.com/and-period/furumaru/pull/2243
> fix(user): dayjsのインポート箇所のエラー修正

- func/cloudfront-origin-response/src/app.ts
> feat(func): S3へのアップロード検証用のデバッグログ追加

- func/cloudfront-origin-response/src/app.ts
> fix(func): バックアップ用の画像保存先pathの修正

- func/cloudfront-origin-response/src/app.ts
> fix(func): ディレクトリパスの修正

- func/cloudfront-origin-response/src/app.ts
> feat(func): 縦か横どちらかのみ指定の場合に4:3のアスペクト比になるように

- web/user/nuxt.config.ts
- web/user/package.json
- web/user/yarn.lock
> setup: gtapの設定を明示的に書いてみる

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): Cognitoユーザープールの移行関数の修正

- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/experiences/index.yaml
- web/admin/src/types/api/api.ts
> fix(docs): 体験一覧APIの定義を修正

- api/config/gateway/admin/rbac/policy.csv
> fix(gateway): オンデマンド配信関連APIの権限追加

- api/internal/gateway/admin/v1/handler/coordinator.go
- api/internal/gateway/admin/v1/handler/experience.go
- api/internal/gateway/admin/v1/handler/notification.go
- api/internal/gateway/admin/v1/handler/order.go
- api/internal/gateway/admin/v1/handler/product.go
- api/internal/gateway/admin/v1/handler/product_type.go
- api/internal/gateway/admin/v1/handler/schedule.go
- api/internal/gateway/admin/v1/handler/video.go
- api/internal/gateway/user/v1/handler/product.go
> fix: 空配列を返すように

- api/internal/gateway/admin/v1/handler/order.go
> fix(gateway): 商品注文履歴取得APIの修正

- web/user/src/locales/ja_jp.json
> fix: topのボタン文言修正

- func/cognito-migrate-user-pool/src/app.ts
Reverts and-period/furumaru#2438
> Revert "fix(func): 移行前のユーザーがパスワードリセットした際の処理を修正"

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): 移行前のユーザーがパスワードリセットした際の処理を修正

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): パスワードリセット時に詰めるusernameを修正

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): Cognitoのマイグレーション時に詰めるステータスを修正

- func/cognito-migrate-user-pool/src/app.ts
Reverts and-period/furumaru#2443
> Revert "fix(func): Cognitoのマイグレーション時に詰めるステータスを修正"

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): forceAliasCreationをtrueにしてみる

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): desiredDeliveryMediumsの設定

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): finalUserStatusの設定

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): usernameを書き換えない

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): subを追加

- func/cognito-migrate-user-pool/src/app.ts
> fix(func): usernameを削除

- api/internal/gateway/cmd/admin/registry.go
- api/internal/user/entity/admin.go
- api/internal/user/entity/user.go
> fix(user): cognito idの管理方法を修正

- api/internal/messenger/cmd/scheduler/registry.go
- api/internal/messenger/cmd/worker/registry.go
> fix(user): バッチ処理のDBクライアントを差し替え

- CHANGELOG.md
This pull request is for the next release as v3.0.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v2.0.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v3.0.0

- web/admin/src/middleware/auth.global.ts
- web/admin/src/pages/health.vue
- web/user/src/pages/health.vue
webページにヘルスチェックのエンドポイントがなく、ホームを叩くたびにDynamoDBへのリクエストが走りコスト増になっているため、ヘルスチェック用のエンドポイントを追加します。
> feat(web): ヘルスチェック用のページを作成

- web/user/src/layouts/health.vue
- web/user/src/pages/health.vue
> fix(user): 外形監視用のページではcart情報を取らない

- web/user/src/pages/health.vue
> fix(user): 外形監視用のページのscriptを修正

- CHANGELOG.md
This pull request is for the next release as v3.0.4 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.0.4 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.0.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v3.0.4

- api/internal/gateway/user/v1/handler/api.go
- api/internal/gateway/user/v1/handler/cart.go
> feat(api): UserAgentがnodeの場合はいくつか処理をスキップするように

- api/internal/gateway/admin/v1/handler/spot.go
- api/internal/gateway/admin/v1/response/spot.go
- api/internal/gateway/admin/v1/service/spot.go
- api/internal/gateway/admin/v1/service/spot_test.go
- docs/swagger/admin/components/schemas/v1/spot.response.yaml
- web/admin/src/types/api/api.ts
> feat(admin): 管理者側のスポットAPIの実装

- api/internal/media/broadcast/updater/starter.go
> fix(media): 配信エンドポイントの指定を修正

- docs/swagger/admin/paths/v1/spots/index.yaml
- docs/swagger/user/paths/v1/spots/index.yaml
- web/admin/src/types/api/api.ts
- web/user/src/types/api/apis/SpotApi.ts
- web/user/src/types/api/models/index.ts
> fix(docs): APIドキュメントの修正

- infra/serverless/serverless.yml
> feat(serverless): regionを直で指定する

- .github/workflows/cd-serverless-for-main.yaml
- infra/serverless/serverless.yml
> Upgrade serveless v4

- infra/tidb/schema/stores/2024128001-add-column-spot-types.sql
> feat(store): TiDB用のDDL追加

- api/internal/store/entity/shipping_revision.go
- api/internal/store/entity/shipping_revision_test.go
> fix(store): 都道府県数をカウントしている箇所の修正

- api/internal/gateway/admin/v1/handler/promotion.go
- api/internal/store/database/database.go
- api/internal/store/input.go
- api/internal/store/service/promotion.go
> fix(store): プロモーション一覧APIのソート修正

- web/user/src/pages/index.vue
> Fix: fixed live open

- api/internal/store/database/tidb/tidb.go
> fix(store): DBのインジェクションを修正

- api/pkg/mysql/client_tidb.go
> fix(api): TiDB用のデフォルト設定を追加

- web/user/src/locales/en_us.json
- web/user/src/locales/ja_jp.json
> Fix: fixed cart message

- api/internal/user/database/tidb/coordinator.go
> fix(user): コーディネータの追加情報を詰める処理が漏れてたので修正

- api/internal/gateway/user/v1/handler/api.go
- api/internal/gateway/user/v1/handler/product_review.go
- api/internal/gateway/user/v1/request/product_review.go
- api/internal/gateway/user/v1/service/product_review.go
- api/internal/gateway/user/v1/service/product_review_test.go
- api/internal/store/database/database.go
- api/internal/store/database/mysql/mysql.go
- api/internal/store/database/mysql/mysql_test.go
- api/internal/store/database/mysql/product_review.go
- api/internal/store/database/mysql/product_review_test.go
- api/internal/store/database/tidb/tidb.go
- api/internal/store/entity/product_review_test.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/store/service/product_review.go
- api/internal/store/service/product_review_test.go
- api/internal/store/service/service_test.go
> feat(store): 商品レビュー機能の実装

- api/internal/gateway/user/v1/handler/live_comment.go
- api/internal/gateway/user/v1/handler/product_review.go
- docs/swagger/user/paths/v1/products/_productId/reviews/index.yaml
- docs/swagger/user/paths/v1/schedules/_scheduleId/comments/index.yaml
- web/user/src/types/api/apis/ProductApi.ts
- web/user/src/types/api/apis/ScheduleApi.ts
> fix(gateway): 商品レビュー一覧が404になる問題の修正

- api/internal/store/entity/product_review.go
- docs/swagger/user/paths/v1/products/_productId/reviews/index.yaml
- docs/swagger/user/paths/v1/spots/_spotId/index.yaml
- web/user/src/types/api/apis/SpotApi.ts
> fix(docs): api docsのtypo修正

- api/internal/gateway/admin/v1/handler/spot.go
- api/internal/gateway/user/v1/handler/spot.go
> fix(gateway): SpotTypeIdが渡せていなかったので修正

- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/user.go
> fix(gateway): user-gatewayでGoogle Map APIが利用できるように

- api/internal/gateway/admin/v1/handler/spot.go
> fix(gateway): スポット登録APIの修正

- api/internal/gateway/user/v1/handler/product_review.go
> fix(gateway): pathの修正

- api/internal/store/database/mysql/experience_review_reaction.go
- api/internal/store/database/mysql/experience_review_reaction_test.go
- api/internal/store/database/mysql/experience_review_test.go
- api/internal/store/service/experience_review.go
> fix(store): 体験レビュー関連の修正

- api/internal/gateway/user/v1/handler/coordinator.go
- api/internal/gateway/user/v1/handler/experience.go
- api/internal/gateway/user/v1/handler/producer.go
- api/internal/gateway/user/v1/handler/product.go
- api/internal/gateway/user/v1/response/coordinator.go
- api/internal/gateway/user/v1/response/producer.go
- docs/swagger/user/components/schemas/v1/coordinator.response.yaml
- docs/swagger/user/components/schemas/v1/producer.response.yaml
- web/user/src/types/api/models/CoordinatorResponse.ts
- web/user/src/types/api/models/ProducerResponse.ts
> feat(gateway): コーディネータ取得APIに体験情報を追加

- api/internal/media/input.go
- api/internal/media/service.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/store/input.go
- api/internal/store/service.go
- api/internal/user/input.go
- api/internal/user/service.go
> refactor(api): インターフェース定義の並び順を整理

- .github/workflows/_deploy_batch.yaml
- .github/workflows/cd-batch-for-prd.yaml
- .github/workflows/cd-batch-for-stg.yaml
- infra/docker/api/Dockerfile
- infra/docker/api/media-archive-updater/Dockerfile
> feat(workflow): AWS Batchのジョブ定義デプロイ用ワークフローを作成

- infra/docker/api/media-update-archive/Dockerfile
> fix(infra): 字幕追加ジョブのDockerfileを修正

- .github/workflows/_build_and_push.yaml
- infra/docker/api/media-update-archive/Dockerfile
> fix(workflow): キャッシュの持ち方を修正

- .github/workflows/_deploy_batch.yaml
> fix(workflow): ワークフローの修正

- api/go.mod
- api/go.sum
- api/hack/media-update-archive/main.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/user.go
- api/internal/media/service/broadcast.go
- api/internal/media/service/broadcast_test.go
- api/internal/media/service/service.go
- api/internal/media/service/service_test.go
- api/pkg/batch/client.go
> feat(media): 字幕付与処理を追加

- api/internal/gateway/cmd/admin/admin.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/gateway/cmd/user/registry.go
- api/internal/gateway/cmd/user/user.go
> fix(media): 起動時引数の修正

- .github/workflows/_build_and_push.yaml
- infra/docker/api/Dockerfile
- infra/docker/api/media-update-archive/Dockerfile
> feat(workflow): APIのコンテナイメージ作成フローを変更

- api/pkg/batch/client.go
> fix(batch): リクエストパラメータの修正

- infra/docker/api/Dockerfile
> fix(workflow): ファイルコピー周りの修正

- api/pkg/batch/client.go
> fix(batch): コンテナ名が必須のため追加

- api/pkg/storage/client.go
> fix(storage): keyの整形

- api/hack/media-update-archive/main.go
> fix(hack): アーカイブURLの変換

- infra/docker/api/media-update-archive/Dockerfile
> fix(infra): バッチ処理用のコンテナのベースイメージを変更

- infra/docker/api/media-update-archive/Dockerfile
> fix(infra): バッチ処理の実行用コンテナの設定を修正

- api/hack/media-update-archive/main.go
- api/pkg/storage/client.go
> fix(infra): ffmpegコマンド実行前にローカルへファイルを保存するように

- api/hack/media-update-archive/main.go
> fix(hack): S3オブジェクトキーの形式を修正

- CHANGELOG.md
This pull request is for the next release as v3.4.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v3.4.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v3.4.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v3.4.1

- api/internal/gateway/user/v1/handler/guest_checkout.go
> fix(gateway): 呼ぶメソッドが間違ってる箇所の修正

- docs/swagger/user/openapi.yaml
- docs/swagger/user/paths/v1/videos/_videoId/comments/index.yaml
- web/user/src/types/api/apis/VideoApi.ts
- web/user/src/types/api/models/index.ts
> fix(docs): オンデマンド配信へのコメント投稿APIのドキュメント追加

- api/internal/media/database/tidb/broadcast.go
- api/internal/messenger/database/tidb/notification.go
- api/internal/messenger/database/tidb/received_queue.go
- api/internal/store/database/tidb/experience.go
- api/internal/store/database/tidb/order.go
- api/internal/store/database/tidb/product.go
- api/internal/store/database/tidb/shipping.go
- api/internal/user/database/tidb/coordinator.go
> fix(store): jsonのunmarshal処理を修正

- .github/workflows/_database_migrate.yaml
- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-gateway-for-stg.yaml
- api/hack/database-migrate/main.go
- api/hack/database-seeds/common/common.go
- api/hack/database-seeds/main.go
- api/hack/database-seeds/master/role.go
- api/hack/database-seeds/user/execute.go
> feat(workflow): DBのマイグレーション処理を実装

- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-gateway-for-stg.yaml
> fix(workflow): secretsの内容を継承できるように

- .github/workflows/_database_migrate.yaml
- .github/workflows/cd-gateway-for-prd.yaml
- .github/workflows/cd-gateway-for-stg.yaml
> fix(workflow): GitHub ActionsのVariablesへのアクセス方法を変更

- api/internal/exception/exception.go
- api/internal/exception/exception_test.go
- api/internal/gateway/admin/v1/handler/api.go
- api/internal/gateway/cmd/admin/admin.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/user/entity/admin_auth.go
- api/internal/user/entity/admin_auth_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/admin_role.go
- api/internal/user/service/admin_role_test.go
- api/pkg/rbac/enforcer.go
> feat(gateway): 認可ロジックの移行

- api/internal/user/database/tidb/admin.go
> fix(user): 管理者詳細情報を詰める処理を追加

- api/internal/gateway/user/v1/service/schedule.go
> fix(gateway): Broadcastのパース処理でnil pointerになっている箇所の修正

- api/internal/store/database/tidb/order.go
- api/internal/store/database/tidb/order_test.go
> fix(store): 注文履歴一覧をcreated_atの降順で並び替え

- api/hack/database-seeds/master/report-template.csv
- api/internal/messenger/entity/mail_config.go
- api/internal/messenger/entity/payload.go
- api/internal/messenger/entity/report_config.go
- api/internal/messenger/input.go
- api/internal/messenger/service.go
- api/internal/messenger/service/notify.go
- api/internal/messenger/service/notify_test.go
- api/internal/store/service/checkout.go
- api/internal/store/service/checkout_event.go
- api/internal/store/service/checkout_event_test.go
- api/internal/store/service/checkout_test.go
> refactor(messenger): メソッド名の変更

- api/internal/gateway/user/v1/handler/product_review.go
> fix(gateway): 商品レビューがないときのハンドリング追加

- api/internal/gateway/cmd/admin/registry.go
> fix(gateway): di周りの修正

- api/internal/gateway/admin/v1/service/top_order.go
- api/internal/gateway/admin/v1/service/top_order_test.go
> fix(gateway): テストがエラーになっている箇所の修正

- api/internal/gateway/admin/v1/service/order_payment.go
- api/internal/gateway/admin/v1/service/order_payment_test.go
> fix(gateway): 決済種別を追加

- api/internal/store/database/tidb/order.go
> fix(store): 週単位の売上集計処理を修正

- web/user/src/lib/order.ts
> feat(user): 決済種別を追加

- web/admin/src/components/templates/HomeTop.vue
> fix(admin): トップページのUI修正

- api/internal/gateway/admin/v1/handler/auth.go
- api/internal/gateway/admin/v1/request/auth.go
- api/internal/gateway/admin/v1/response/auth.go
- api/internal/gateway/admin/v1/service/auth.go
- api/internal/gateway/admin/v1/service/auth_test.go
- api/internal/gateway/cmd/admin/admin.go
- api/internal/gateway/cmd/admin/registry.go
- api/internal/user/entity/admin_auth_provider.go
- api/internal/user/entity/admin_auth_provider_test.go
- api/internal/user/input.go
- api/internal/user/service.go
- api/internal/user/service/admin_auth.go
- api/internal/user/service/admin_auth_test.go
- api/internal/user/service/service.go
- api/pkg/cognito/auth.go
- api/pkg/cognito/client.go
- docs/swagger/admin/components/schemas/v1/auth.request.yaml
- docs/swagger/admin/components/schemas/v1/auth.response.yaml
- docs/swagger/admin/openapi.yaml
- docs/swagger/admin/paths/v1/auth/line.yaml
- web/admin/nuxt.config.ts
- web/admin/src/components/templates/AuthSignIn.vue
- web/admin/src/middleware/auth.global.ts
- web/admin/src/pages/accounts/providers/index.vue
- web/admin/src/pages/auth/line/callback.vue
- web/admin/src/pages/auth/line/connect.vue
- web/admin/src/pages/signin.vue
- web/admin/src/store/auth.ts
- web/admin/src/types/api/api.ts
> feat(user): LINEアカウント認証の実装

- infra/docker/api/Dockerfile
- infra/docker/api/Dockerfile.development
- infra/docker/api/hack/Dockerfile
- infra/docker/api/media-update-archive/Dockerfile
> hotfix(infra): コンテナイメージのバージョン修正

- api/internal/gateway/user/v1/handler/uploader.go
- api/internal/gateway/user/v1/response/uploader.go
- api/internal/media/entity/upload_event.go
- api/internal/media/entity/upload_event_test.go
- api/internal/media/service/upload.go
- api/internal/media/service/upload_test.go
- api/pkg/storage/client.go
- docs/swagger/admin/components/schemas/v1/upload.response.yaml
- web/admin/src/pages/version.vue
- web/admin/src/plugins/api-client.ts
- web/admin/src/plugins/google-analytics.ts
- web/admin/src/plugins/vuetify.ts
- web/admin/src/store/broadcast.ts
- web/admin/src/store/coordinator.ts
- web/admin/src/store/experience.ts
- web/admin/src/store/helper.ts
- web/admin/src/store/live.ts
- web/admin/src/store/notification.ts
- web/admin/src/store/order.ts
- web/admin/src/store/producer.ts
- web/admin/src/store/product-type.ts
- web/admin/src/store/product.ts
- web/admin/src/store/promotion.ts
- web/admin/src/store/schedule.ts
- web/admin/src/store/video.ts
- web/admin/src/types/api/api.ts
うまく動かないので、一度リバートしようと思います
Reverts and-period/furumaru#2753
> Revert "feat(media): 署名URL発行時のヘッダー情報も連携するように"

- docs/swagger/admin/paths/v1/coordinators/_coordinatorId/shippings/index.yaml
- web/admin/src/types/api/api.ts
> fix(docs): 配送関連のAPI仕様書を修正

- api/internal/gateway/admin/v1/handler/shipping.go
- api/internal/gateway/admin/v1/service/shipping.go
- api/internal/gateway/admin/v1/service/shipping_test.go
> feat(gateway): 配送設定更新APIの実装

- api/internal/gateway/admin/v1/response/shipping.go
> fix(gateway): omitemptyタグの削除

- web/admin/src/components/templates/OrderShow.vue
- web/admin/src/pages/orders/[id]/index.vue
- web/admin/src/pages/version.vue
- web/admin/src/plugins/api-client.ts
- web/admin/src/plugins/google-analytics.ts
- web/admin/src/store/broadcast.ts
- web/admin/src/store/coordinator.ts
- web/admin/src/store/experience.ts
- web/admin/src/store/live.ts
- web/admin/src/store/notification.ts
- web/admin/src/store/order.ts
- web/admin/src/store/producer.ts
- web/admin/src/store/product-type.ts
- web/admin/src/store/product.ts
- web/admin/src/store/promotion.ts
- web/admin/src/store/schedule.ts
> 注文詳細取得のロジックの改修

- api/internal/gateway/user/v1/handler/product.go
> fix(gateway): Google Merchant Center用のAPIの修正

- .github/workflows/cd-web-liff-for-prd.yaml
> feat(workflow): LIFFアプリの本番リリース用ワークフローを追加

- api/internal/user/service/facility_user.go
- api/internal/user/service/facility_user_test.go
> fix(user): 外部施設向け利用者登録時のバリデーション修正

- api/internal/gateway/user/v1/handler/coordinator.go
- api/internal/gateway/user/v1/types/coordinator.go
- docs/spec/swagger/user/v1/swagger.yaml
> feat: コーディネータ情報にオンデマンド映像情報も追加
